### ISSUE TITLE
Crashing when adding external converter (Cannot find module '../lib/exposes')

### ISSUE THREAD

**Issue by andreumarques** [zigbee2mqtt/hassio-zigbee2mqtt#105]
**Description of problem:**
// Please do a short description of the problem
Crashing on startup when adding [this](devices/tuya.js) external converter for a new PIR sensor Tuya Compatible.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
edge #7406 (4666ee7261063fb37ad24cf22afdf37a9038326d)
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
// replace this line with your pasted configuration
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.4.6
Supervisor: supervisor-2021.04.3
Operating System: Home Assistant OS 5.13
```

**Your logs from Home Assistant Supervisor**
```
> zigbee2mqtt@1.18.3-dev start /app
> node index.js
(node:566) UnhandledPromiseRejectionWarning: internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module '../lib/exposes'
Require stack:
- /app/lib/util/utils.js
- /app/lib/util/settings.js
- /app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /app/lib/util/externally-loaded.js:1:17
    at Script.runInContext (vm.js:143:18)
    at Script.runInNewContext (vm.js:148:17)
    at Object.runInNewContext (vm.js:303:38)
    at loadModuleFromText (/app/lib/util/utils.js:162:8)
    at loadModuleFromFile (/app/lib/util/utils.js:168:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:566) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:566) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ciotlosm** [comment]
This is something for core to help with. Please raise your issue here: https://github.com/Koenkk/zigbee2mqtt/issues
