### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/share/zigbee2mqtt/.yaml'

### ISSUE THREAD

**Issue by NCGNConsulting** [zigbee2mqtt/hassio-zigbee2mqtt#110]
Hello
I'm not able to perform any action due to cyclic error

Add-on version 1.18.3-1

--------------------------------------

CONFIGURATION:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.**.***:****'
  user: secret! mqtt_user
  password: secret! mqtt_password
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
  disable_led: false
advanced:
  log_level: warn
  log_directory: data/log/%TIMESTAMP%
  log_file: log.txt
  log_rotation: true
  log_output:
    - console
    - file
  pan_id: ****
  channel: **
  network_key:
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
    - ***
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: ****
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
zigbee_herdsman_debug: true
```
--------------------------------------------------------------------------------------------------------------------------------------------

PI3 with 
core-2021.5.3 
supervisor-2021.04.3
docker 20.10.6

PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster

**Your logs from Home Assistant Supervisor**
LOG:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[10:49:33] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[10:49:35] INFO: MQTT available, fetching server detail ...
[10:49:35] INFO: Previous config file found, checking backup
[10:49:35] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[10:49:35] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:49:37] INFO: Zigbee Herdsman debug logging enabled
[10:49:37] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.3 start /app
> node index.js
(node:331) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/share/zigbee2mqtt/.yaml'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at Object.read (/app/lib/util/yaml.js:7:33)
    at interpetValue (/app/lib/util/settings.js:284:25)
    at read (/app/lib/util/settings.js:291:23)
    at get (/app/lib/util/settings.js:365:21)
    at Object.reRead (/app/lib/util/settings.js:691:9)
    at start (/app/index.js:27:14)
    at Object.<anonymous> (/app/index.js:60:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:331) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:331) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[10:49:44] INFO: Zigbee Herdsman debug logging enabled
[10:49:45] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.3 start /app
> node index.js
```
-------------------------------------------------------------------------------------------------------------------------------------

**Comment by NCGNConsulting** [comment]
Also to add supervisor log.
Ingress error: Cannot connect to host ***.**.**.**:80** ssl:default [Connect call failed (***.**.**.**:80**)]

**Comment by ciotlosm** [comment]
The supervisor log shows error because the addon is not started so the UI can't be mapped. 
The error that you have in your logs is due to the configuration.yaml file missing. I'm not sure what type of installation you are using but looks like the Supervisor doesn't have permissions maybe in /share/zigbee2mqtt to save the configuration.yaml file 

` UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/share/zigbee2mqtt/.yaml'`

The file should have a name there, not just .yaml.

Try updating to 1.21.0 and see if you have any better results.
