### ISSUE TITLE
Newest version of hassio-zigbee2mqtt not automatically updated by supervisor...

### ISSUE THREAD

**Issue by sunsear** [zigbee2mqtt/hassio-zigbee2mqtt#114]
**Description of problem:**
Somehow I seem to be stuck on 1.18.1-1, while 1.18.3-1 has been out for a while. This new version has some updates that I need, so I have set the supervisor to auto-update zigbee2mqtt plugin, but it doesn't do it. I do find a strange error in my supervisor logs. Seems related.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.18.1-1 
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
No sure this is needed
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.4.6
Supervisor: supervisor-2021.04.3
Operating System: Home Assistant OS 5.13
```

**Your logs from Home Assistant Supervisor**
```
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 804, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 682, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.8/site-packages/git/cmd.py", line 409, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v --update-shallow --depth=1 origin
  stderr: 'b"fatal: unable to access 'https://github.com/danielwelch/hassio-zigbee2mqtt/': Could not resolve host: github.com"'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 110, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 107, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 195, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
```

**Comment by netweaver1970** [comment]
see : [https://github.com/Koenkk/zigbee2mqtt/discussions/7478](https://github.com/Koenkk/zigbee2mqtt/discussions/7478)

**Comment by sunsear** [comment]
Indeed, will try that!

**Comment by sunsear** [comment]
Ok, that was it, closing this issue.
