### ISSUE TITLE
Xiaomi Aqara sensors don't re-join the network

### ISSUE THREAD

**Issue by Nihvel** [zigbee2mqtt/hassio-zigbee2mqtt#117]
**Description of problem:**
All the sensors I own are in the range of the CC2531 (using the latest firmware). There is not much distance, less than 5 meters, between the coordinator and the sensors. Quite often these sensors, and randomly, lose connection to the coordinator.

The last time this happened was recently. With the exception that 2 sensors out of 9 won't re-join the network. All of them are Xiaomi Aqara sensors, ranging from door-contact, temperature, motion and light sensor.
I have always had issues to have these Xiaomi Aqara, all of them joining the network. I read that the reason could be the different implementation of Zigbee protocol that Xiaomi uses.

The 2 sensors are a temperature `WSDCGQ01LM` and a motion `RTCGQ11LM`. It is worth to note that I have 4 more RTCGQ11LM and one more WSDCGQ01LM, and they appear to work ok.

**Steps to reproduce** (which could only happen in my very own case):
1. Enable `Permit join` - I can see from the logs:
```
Zigbee2MQTT:info  2021-05-20 13:55:13: MQTT publish: topic 'zigbee2mqtt/bridge/response/permit_join', payload '{"data":{"value":true},"status":"ok","transaction":"uw0dh-2"}'
```
2. Press the button on the sensor(s) for 5 seconds, it blinks blue
3. No green balloon show up on Zigbee2mqtt GUI - No Log entry on Zigbee2mqtt addon show connection attempts

___

I have even tried the `single button press every few seconds` method, and still nothing.
___

I have also deleted the old entries in the `devices.yaml` and `database` file from `/share/zigbee2mqtt` so these will recreate (done frequently in the past when there was no GUI), but they won't.
___

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.18.1-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: *******
  password: ********
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - ******
    - ******
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false

```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.5.5
Supervisor: supervisor-2021.04.3
Operating System: Home Assistant OS 5.13
```

**Your logs from Home Assistant Supervisor**
```
21-05-20 12:13:07 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 123, in sentry_app_handle
    reraise(*_capture_exception(hub))
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/aiohttp.py", line 113, in sentry_app_handle
    response = await old_handle(self, request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/security.py", line 135, in system_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/security.py", line 197, in token_validation
    return await handler(request)
  File "/usr/src/supervisor/supervisor/api/utils.py", line 65, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/supervisor/supervisor/api/addons.py", line 398, in stats
    stats: DockerStats = await addon.stats()
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 673, in stats
    return await self.instance.stats()
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/interface.py", line 526, in _stats
    stats = docker_container.stats(stream=False)
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 422, in stats
    return self.client.api.stats(self.id, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 1141, in stats
    return self._result(self._get(url, params={'stream': False}),
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 277, in _result
    return response.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
21-05-20 12:13:07 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-20 12:13:07 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-20 12:13:07 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-20 12:13:07 WARNING (SyncWorker_3) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-20 12:13:07 WARNING (SyncWorker_3) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-20 12:13:07 WARNING (SyncWorker_3) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-20 12:13:07 INFO (SyncWorker_3) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.18.1-1
21-05-20 12:13:07 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-20 12:13:07 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-05-20 12:13:07 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
```

**Comment by ciotlosm** [comment]
I had similar issues and the only way to solve this was:
- buy an usb extender for your coordinator
- move the coordinator further away from any interference source

If you only have one problematic sensor, do some force removals, change batteries and pair again
