### ISSUE TITLE
Can't install and run z2m. Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by PandaGirll** [zigbee2mqtt/hassio-zigbee2mqtt#119]
Hello,
I have xiaomi gateway 3 and HA on mini-pc.
I'm trying to connect gateway to HA with AlexxIT/XiaomiGateway3/ integration.
I'm installing z2m integration in Supervisor tab, configuring it with mqtt settings from mosquitto brocker and  serial: settings from gateway integration.
But when i'm  starting z2m integration, i have some errors while starting zigbee-herdsman. 
The same in stable and edge.

**Zigbee2mqtt add-on version:**
```
zigbee2mqtt@1.18.3-dev
and
zigbee2mqtt@1.18.3
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
## System Health

version | core-2021.5.5
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 4.19.0-16-amd64
arch | x86_64
timezone | Europe/Moscow

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4843
Installed Version | 1.12.3
Stage | running
Available Repositories | 892
Installed Repositories | 24

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.04.3
docker_version | 20.10.6
disk_total | 144.8 GB
disk_used | 6.8 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | File editor (5.3.1), Samba share (9.4.0), MariaDB (2.3.0), Home Assistant Google Drive Backup (0.104.3), Mosquitto broker (6.0.1), Zigbee2mqtt (1.18.3-1)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 14
views | 7
mode | yaml

</details>
```

**Running platform (details from Supervisor > System)**
```
Core: core-2021.5.5
Supervisor: supervisor-2021.04.3
Operating System: Debian GNU/Linux 10 (buster)
Docker: 20.10.6

```

**Zigbee2mqtt configuration:**
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: hassiomqtt
  password: hassio4516627
serial:
  port: 'tcp://192.168.31.110:8888'
  adapter: ezsp
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
zigbee_herdsman_debug: true
```

**logs from Home Assistant Supervisor**
```
Zigbee2MQTT:error 2021-05-21 18:29:09: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-05-21 18:29:09: Failed to start zigbee
Zigbee2MQTT:error 2021-05-21 18:29:09: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-05-21 18:29:09: Exiting...
Zigbee2MQTT:error 2021-05-21 18:29:09: Error: {"frameId":83,"sequence":17} after 10000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:37:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.3-dev start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.3-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-21T15_29_09_213Z-debug.log
[18:29:09] INFO: Zigbee Herdsman debug logging enabled
[18:29:09] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.3-dev start /app
> node index.js
Zigbee2MQTT:info  2021-05-21 18:30:24: Logging to console and directory: '/config/zigbee2mqtt/log/2021-05-21.18-30-21' filename: log.txt
Zigbee2MQTT:info  2021-05-21 18:30:24: Starting Zigbee2MQTT version 1.18.3-dev (commit #888cc7e)
Zigbee2MQTT:info  2021-05-21 18:30:24: Starting zigbee-herdsman (0.13.105)
```
```
2021-05-21T15:31:55.618Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 83 (setConfigurationValue) received: 00
2021-05-21T15:31:55.619Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 83 (setConfigurationValue)   parsed: 0
2021-05-21T15:31:55.620Z zigbee-herdsman:adapter:ezsp:log Set EzspConfigId.CONFIG_APS_UNICAST_MESSAGE_COUNT = 255
2021-05-21T15:31:55.621Z zigbee-herdsman:adapter:ezsp:log ===> Send command setConfigurationValue: (3,255)
2021-05-21T15:31:55.622Z zigbee-herdsman:adapter:ezsp:log ===> Send data    setConfigurationValue: (0c0001530003ff00)
2021-05-21T15:31:55.623Z zigbee-herdsman:adapter:ezsp:uart Send DATA frame (4,4,0): 0c0001530003ff00
2021-05-21T15:31:55.624Z zigbee-herdsman:adapter:ezsp:uart waiting (5)
2021-05-21T15:31:55.624Z zigbee-herdsman:adapter:ezsp:uart --> [444e21a9072a164d59b5667e] [68,78,33,169,7,42,22,77,89,181,102,126]
2021-05-21T15:31:55.625Z zigbee-herdsman:adapter:ezsp:uart waiting (5) success
2021-05-21T15:31:55.678Z zigbee-herdsman:adapter:ezsp:uart <-- [454ea1a9072a206edd7e] [69,78,161,169,7,42,32,110,221,126]
2021-05-21T15:31:55.679Z zigbee-herdsman:adapter:ezsp:uart Recv DATA frame (4,5,0): 454ea1a9072a206edd7e
2021-05-21T15:31:55.680Z zigbee-herdsman:adapter:ezsp:uart Send ACK  frame (5)
2021-05-21T15:31:55.680Z zigbee-herdsman:adapter:ezsp:uart --> [8520dd7e] [133,32,221,126]
2021-05-21T15:31:55.681Z zigbee-herdsman:adapter:ezsp:log <=== Frame: 0c8001530035
2021-05-21T15:31:55.682Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 83 (setConfigurationValue) received: 35
2021-05-21T15:31:55.682Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 83 (setConfigurationValue)   parsed: 53
Assertion failed
2021-05-21T15:31:55.687Z zigbee-herdsman:adapter:ezsp:log Set EzspConfigId.CONFIG_BROADCAST_TABLE_SIZE = 15
2021-05-21T15:31:55.688Z zigbee-herdsman:adapter:ezsp:log ===> Send command setConfigurationValue: (43,15)
2021-05-21T15:31:55.689Z zigbee-herdsman:adapter:ezsp:log ===> Send data    setConfigurationValue: (0d000153002b0f00)
2021-05-21T15:31:55.690Z zigbee-herdsman:adapter:ezsp:uart Send DATA frame (5,5,0): 0d000153002b0f00
2021-05-21T15:31:55.691Z zigbee-herdsman:adapter:ezsp:uart waiting (6)
2021-05-21T15:31:55.691Z zigbee-herdsman:adapter:ezsp:uart --> [554f21a9072a3ebd5976ce7e] [85,79,33,169,7,42,62,189,89,118,206,126]
2021-05-21T15:31:55.692Z zigbee-herdsman:adapter:ezsp:uart waiting (6) success
2021-05-21T15:31:55.743Z zigbee-herdsman:adapter:ezsp:uart <-- [564fa1a9072a15a2727e] [86,79,161,169,7,42,21,162,114,126]
2021-05-21T15:31:55.743Z zigbee-herdsman:adapter:ezsp:uart Recv DATA frame (5,6,0): 564fa1a9072a15a2727e
2021-05-21T15:31:55.744Z zigbee-herdsman:adapter:ezsp:uart Send ACK  frame (6)
2021-05-21T15:31:55.745Z zigbee-herdsman:adapter:ezsp:uart --> [8610be7e] [134,16,190,126]
2021-05-21T15:31:55.746Z zigbee-herdsman:adapter:ezsp:log <=== Frame: 0d8001530000
2021-05-21T15:31:55.746Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 83 (setConfigurationValue) received: 00
2021-05-21T15:31:55.747Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 83 (setConfigurationValue)   parsed: 0
2021-05-21T15:31:55.749Z zigbee-herdsman:adapter:ezsp:log Set EzspConfigId.CONFIG_MAX_HOPS = 30
2021-05-21T15:31:55.749Z zigbee-herdsman:adapter:ezsp:log ===> Send command setConfigurationValue: (16,30)
2021-05-21T15:31:55.750Z zigbee-herdsman:adapter:ezsp:log ===> Send data    setConfigurationValue: (0e00015300101e00)
2021-05-21T15:31:55.751Z zigbee-herdsman:adapter:ezsp:uart Send DATA frame (6,6,0): 0e00015300101e00
2021-05-21T15:31:55.752Z zigbee-herdsman:adapter:ezsp:uart waiting (7)
2021-05-21T15:31:55.752Z zigbee-herdsman:adapter:ezsp:uart --> [664c21a9072a05ac5962eb7e] [102,76,33,169,7,42,5,172,89,98,235,126]
2021-05-21T15:31:55.753Z zigbee-herdsman:adapter:ezsp:uart waiting (7) success
2021-05-21T15:31:55.803Z zigbee-herdsman:adapter:ezsp:uart <-- [674ca1a9072a158d7d5e7e] [103,76,161,169,7,42,21,141,125,94,126]
2021-05-21T15:31:55.803Z zigbee-herdsman:adapter:ezsp:uart Recv DATA frame (6,7,0): 674ca1a9072a158d7e7e00
2021-05-21T15:31:55.804Z zigbee-herdsman:adapter:ezsp:uart Send ACK  frame (7)
2021-05-21T15:31:55.805Z zigbee-herdsman:adapter:ezsp:uart --> [87009f7e] [135,0,159,126]
2021-05-21T15:31:55.806Z zigbee-herdsman:adapter:ezsp:log <=== Frame: 0e80015300003f
2021-05-21T15:31:55.807Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 83 (setConfigurationValue) received: 003f
2021-05-21T15:31:55.807Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 83 (setConfigurationValue)   parsed: 0
2021-05-21T15:31:55.809Z zigbee-herdsman:adapter:ezsp:log Set EzspConfigId.CONFIG_INDIRECT_TRANSMISSION_TIMEOUT = 7680
2021-05-21T15:31:55.810Z zigbee-herdsman:adapter:ezsp:log ===> Send command setConfigurationValue: (18,7680)
2021-05-21T15:31:55.811Z zigbee-herdsman:adapter:ezsp:log ===> Send data    setConfigurationValue: (0f0001530012001e)
2021-05-21T15:31:55.812Z zigbee-herdsman:adapter:ezsp:uart Send DATA frame (7,7,0): 0f0001530012001e
2021-05-21T15:31:55.813Z zigbee-herdsman:adapter:ezsp:uart waiting (0)
2021-05-21T15:31:55.813Z zigbee-herdsman:adapter:ezsp:uart --> [774d21a9072a07b24720067e] [119,77,33,169,7,42,7,178,71,32,6,126]
2021-05-21T15:31:55.814Z zigbee-herdsman:adapter:ezsp:uart waiting (0) success
2021-05-21T15:31:55.877Z zigbee-herdsman:adapter:ezsp:uart <-- [704da1a9072a15e6e17e] [112,77,161,169,7,42,21,230,225,126]
2021-05-21T15:31:55.878Z zigbee-herdsman:adapter:ezsp:uart Recv DATA frame (7,0,0): 704da1a9072a15e6e17e
2021-05-21T15:31:55.879Z zigbee-herdsman:adapter:ezsp:uart Send ACK  frame (0)
2021-05-21T15:31:55.879Z zigbee-herdsman:adapter:ezsp:uart --> [8070787e] [128,112,120,126]
2021-05-21T15:31:55.881Z zigbee-herdsman:adapter:ezsp:log <=== Frame: 0f8001530000
2021-05-21T15:31:55.881Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 83 (setConfigurationValue) received: 00
2021-05-21T15:31:55.882Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 83 (setConfigurationValue)   parsed: 0
2021-05-21T15:31:55.883Z zigbee-herdsman:adapter:ezsp:log Set EzspConfigId.CONFIG_SOURCE_ROUTE_TABLE_SIZE = 16
2021-05-21T15:31:55.884Z zigbee-herdsman:adapter:ezsp:log ===> Send command setConfigurationValue: (26,16)
2021-05-21T15:31:55.885Z zigbee-herdsman:adapter:ezsp:log ===> Send data    setConfigurationValue: (10000153001a1000)
2021-05-21T15:31:55.886Z zigbee-herdsman:adapter:ezsp:uart Send DATA frame (0,0,0): 10000153001a1000
2021-05-21T15:31:55.887Z zigbee-herdsman:adapter:ezsp:uart waiting (1)
2021-05-21T15:31:55.887Z zigbee-herdsman:adapter:ezsp:uart --> [005221a9072a0fa259872d7e] [0,82,33,169,7,42,15,162,89,135,45,126]
2021-05-21T15:31:55.888Z zigbee-herdsman:adapter:ezsp:uart waiting (1) success
2021-05-21T15:31:57.015Z zigbee-herdsman:adapter:ezsp:uart <-- [c102029b7b7e] [193,2,2,155,123,126]
2021-05-21T15:31:57.015Z zigbee-herdsman:adapter:ezsp:uart RSTACK frame: c102029b7b7e
2021-05-21T15:31:57.016Z zigbee-herdsman:adapter:ezsp:uart RSTACK Version: 2 Reason: RESET_POWER_ON frame: c102029b7b7e
2021-05-21T15:32:00.590Z zigbee-herdsman:adapter:ezsp:uart <-- [c102029b7b7e] [193,2,2,155,123,126]
2021-05-21T15:32:00.591Z zigbee-herdsman:adapter:ezsp:uart RSTACK frame: c102029b7b7e
2021-05-21T15:32:00.591Z zigbee-herdsman:adapter:ezsp:uart RSTACK Version: 2 Reason: RESET_POWER_ON frame: c102029b7b7e
2021-05-21T15:32:04.170Z zigbee-herdsman:adapter:ezsp:uart <-- [c102029b7b7e] [193,2,2,155,123,126]
2021-05-21T15:32:04.171Z zigbee-herdsman:adapter:ezsp:uart RSTACK frame: c102029b7b7e
2021-05-21T15:32:04.172Z zigbee-herdsman:adapter:ezsp:uart RSTACK Version: 2 Reason: RESET_POWER_ON frame: c102029b7b7e
2021-05-21T15:32:04.845Z zigbee-herdsman:adapter:ezsp:log Time to watchdog ... 0
2021-05-21T15:32:04.846Z zigbee-herdsman:adapter:ezsp:log ===> Send command nop: ()
2021-05-21T15:32:05.888Z zigbee-herdsman:adapter:ezsp:log ===> Send data    nop: (1100010500)
2021-05-21T15:32:05.889Z zigbee-herdsman:adapter:ezsp:uart Send DATA frame (0,0,0): 1100010500
2021-05-21T15:32:05.890Z zigbee-herdsman:adapter:ezsp:uart waiting (1)
2021-05-21T15:32:05.891Z zigbee-herdsman:adapter:ezsp:uart --> [005321a9512a2fa17e] [0,83,33,169,81,42,47,161,126]
2021-05-21T15:32:05.892Z zigbee-herdsman:adapter:ezsp:uart waiting (1) success
```

**Comment by ciotlosm** [comment]
This add-on is not for gateways with AlexxIT/XiaomiGateway3/ integration. This only works directly with the supported sticks specified in the documentation.
