### ISSUE TITLE
 Unknown option 'username' for Zigbee2mqtt

### ISSUE THREAD

**Issue by sotavov** [zigbee2mqtt/hassio-zigbee2mqtt#124]
Good day!
see this error, what did I do wrong?

Supervisor
Версия
supervisor-2021.04.3

Zigbee2mqtt 
Current version: 1.18.3-1
```
21-05-25 12:48:44 WARNING (MainThread) [supervisor.addons.options] Unknown option 'username' for Zigbee2mqtt (45df7312_zigbee2mqtt)
21-05-25 12:51:23 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1139' coro=<Scheduler._run_task.<locals>._wrap_task() done, defined at /usr/src/supervisor/supervisor/misc/scheduler.py:58> exception=TypeError('an integer is required (got type str)')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/misc/scheduler.py", line 62, in _wrap_task
    await task.coro_callback()
  File "/usr/src/supervisor/supervisor/misc/tasks.py", line 416, in _watchdog_addon_application
    if addon.in_progress or await addon.watchdog_application():
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 479, in watchdog_application
    return await self.sys_run_in_executor(check_port, self.ip_address, port)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 43, in check_port
    result = sock.connect_ex((str(address), port))
TypeError: an integer is required (got type str)
```

![1](https://user-images.githubusercontent.com/14863356/119502063-30591d00-bd72-11eb-84c0-6d134899a4a9.jpg)

**Comment by smulle48** [comment]
https://www.zigbee2mqtt.io/information/configuration.html

You have to use **user** instead of **username** :-)
