### ISSUE TITLE
Unable to start zigbee2mqtt with CC2652R

### ISSUE THREAD

**Issue by pietjuhklaas** [zigbee2mqtt/hassio-zigbee2mqtt#129]
Today i received my CC2652R stick (as recommended on the zigbee2mqtt page).
I flashed it with the firmware:  https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_3.x.0/bin/CC2652R_coordinator_20210120.zip
It all was a success.

Then i went into Zigbee2Mqtt as it was working with my CC2531 stick.
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: mqtt
  password: ffdsfsd
serial:
  port: /dev/ttyUSB0
advanced:
  rtscts: false
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false

Above my configuration for the CC2652R.
When i'm starting the zigbee2mqtt add-on the error is shown:

Zigbee2MQTT:error 2021-06-03 19:15:56: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-06-03 19:15:56: Failed to start zigbee
Zigbee2MQTT:error 2021-06-03 19:15:56: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-06-03 19:15:56: Exiting...
Zigbee2MQTT:error 2021-06-03 19:15:56: Error: Error while opening serialport 'Error: Error: I/O error, cannot open /dev/ttyUSB0'
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.19.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.19.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-03T17_15_56_699Z-debug.log

On the console of Hassos the error is shown:
failed to send control message: -110

The ZHA configuration seems to accept the config.

I'm not sure what i'm doing wrong. Do i need to remove old configs as i've switched sticks??

Any help would be great. If you need more information, please let me know.

**Comment by pietjuhklaas** [comment]
Never mind... Had to put the stick into myb USB 3.0 port instead of the 2.0 port
