### ISSUE TITLE
Failed to set permit join to false

### ISSUE THREAD

**Issue by liuk4friends** [zigbee2mqtt/hassio-zigbee2mqtt#130]
**Description of problem:**
After installing the latest version of zigbee2mqtt 1.19.0 this error appeared in the log:
```
Zigbee2MQTT:error 2021-06-02 15:39:04: Failed to set permit join to false
```

All my zigbee devices are perfectly working but I’m wondering if joining procedure has been broken.
Unfortunately I don't have any other zigbee devices to test it.

I’ve upgraded HA to 2021.6.1 and zigbee2mqtt to 1.19.1 but those errors are still there….

When pairing is activated, this error also appears:
```
Zigbee2MQTT:error 2021-06-02 23:17:37: Failed to call 'BridgeLegacy' 'onMQTTMessage' (Error: SRSP - UTIL - ledControl after 6000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:37:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7))
```

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
> zigbee2mqtt@1.19.1 start /app
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://homeassistant
  user: ***********
  password: *************
serial:
  port: /dev/ttyUSB0
advanced:
  rtscts: false
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
zigbee_herdsman_debug: false
```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.6.1
Supervisor: supervisor-2021.05.4
Operating System: HassOS 5.13
```

**Your logs from Home Assistant Supervisor**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[15:38:44] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[15:38:45] INFO: MQTT available, fetching server detail ...
[15:38:46] INFO: Previous config file found, checking backup
[15:38:46] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[15:38:46] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:38:47] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.19.0 start /app
> node index.js
Zigbee2MQTT:error 2021-06-02 15:39:04: Failed to set permit join to false
Zigbee2MQTT:error 2021-06-02 23:17:37: Failed to call 'BridgeLegacy' 'onMQTTMessage' (Error: SRSP - UTIL - ledControl after 6000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:37:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7))
```

**Comment by liuk4friends** [comment]
Error has disappeared after installing zigbee2mqtt 1.20.0-1
