### ISSUE TITLE
Aqara Cover Motor stopped working after update

### ISSUE THREAD

**Issue by sweetpalma** [zigbee2mqtt/hassio-zigbee2mqtt#136]
**Description of problem:**
Aqara B1 Cover motor stopped working after update - it exposes it's battery and signal quality, but not the motor controls themselves. Also throws errors into the logs (attached).

**Zigbee2mqtt add-on version:**
```
Current version: 1.18.1-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: '!secret mqtt_username'
  password: '!secret mqtt_password'
serial:
  disable_led: true
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

**Running platform (details from Suypervisor > System)**
```
OS: Ubuntu 18.04.5 LTS
Supervisor Version: supervisor-2021.05.4
Core Version: core-2021.6.2
```

**Your logs from Home Assistant Supervisor**
```
Exception in message_received when handling msg on 'zigbee2mqtt/livingroom_cover': '' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 31, in wrapper _log_message(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 21, in _log_message messages = debug_info["entities"][entity_id]["subscriptions"][ KeyError: 'sensor.livingroom_cover_linkquality'
Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'command_topic': 'zigbee2mqtt/0x04cf8cdf3c73a855/set', 'device': {'identifiers': ['zigbee2mqtt_0x04cf8cdf3c73a855'], 'manufacturer': 'Xiaomi', 'model': 'Aqara B1 curtain motor (ZNCLDJ12LM)', 'name': '0x04cf8cdf3c73a855', 'sw_version': 'Zigbee2MQTT 1.18.1'}, 'json_attributes_topic': 'zigbee2mqtt/0x04cf8cdf3c73a855', 'name': '0x04cf8cdf3c73a855', 'position_topic': 'zigbee2mqtt/0x04cf8cdf3c73a855', 'set_position_template': '{ "position": {{ position }} }', 'set_position_topic': 'zigbee2mqtt/0x04cf8cdf3c73a855/set', 'unique_id': '0x04cf8cdf3c73a855_cover_zigbee2mqtt', 'value_template': '{{ value_json.position }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.
Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'command_topic': 'zigbee2mqtt/0x04cf8cdf3c73a10e/set', 'device': {'identifiers': ['zigbee2mqtt_0x04cf8cdf3c73a10e'], 'manufacturer': 'Xiaomi', 'model': 'Aqara B1 curtain motor (ZNCLDJ12LM)', 'name': '0x04cf8cdf3c73a10e', 'sw_version': 'Zigbee2MQTT 1.18.1'}, 'json_attributes_topic': 'zigbee2mqtt/0x04cf8cdf3c73a10e', 'name': '0x04cf8cdf3c73a10e', 'position_topic': 'zigbee2mqtt/0x04cf8cdf3c73a10e', 'set_position_template': '{ "position": {{ position }} }', 'set_position_topic': 'zigbee2mqtt/0x04cf8cdf3c73a10e/set', 'unique_id': '0x04cf8cdf3c73a10e_cover_zigbee2mqtt', 'value_template': '{{ value_json.position }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.
Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'command_topic': 'zigbee2mqtt/bedroom_cover/set', 'device': {'identifiers': ['zigbee2mqtt_0x04cf8cdf3c73a855'], 'manufacturer': 'Xiaomi', 'model': 'Aqara B1 curtain motor (ZNCLDJ12LM)', 'name': 'bedroom_cover', 'sw_version': 'Zigbee2MQTT 1.18.1'}, 'json_attributes_topic': 'zigbee2mqtt/bedroom_cover', 'name': 'bedroom_cover', 'position_topic': 'zigbee2mqtt/bedroom_cover', 'set_position_template': '{ "position": {{ position }} }', 'set_position_topic': 'zigbee2mqtt/bedroom_cover/set', 'unique_id': '0x04cf8cdf3c73a855_cover_zigbee2mqtt', 'value_template': '{{ value_json.position }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.
Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'command_topic': 'zigbee2mqtt/livingroom_cover/set', 'device': {'identifiers': ['zigbee2mqtt_0x04cf8cdf3c73a10e'], 'manufacturer': 'Xiaomi', 'model': 'Aqara B1 curtain motor (ZNCLDJ12LM)', 'name': 'livingroom_cover', 'sw_version': 'Zigbee2MQTT 1.18.1'}, 'json_attributes_topic': 'zigbee2mqtt/livingroom_cover', 'name': 'livingroom_cover', 'position_topic': 'zigbee2mqtt/livingroom_cover', 'set_position_template': '{ "position": {{ position }} }', 'set_position_topic': 'zigbee2mqtt/livingroom_cover/set', 'unique_id': '0x04cf8cdf3c73a10e_cover_zigbee2mqtt', 'value_template': '{{ value_json.position }}', 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options raise vol.Invalid( voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover config = schema(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__ raise er.MultipleInvalid([e]) voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.
```

**Comment by 7h0mas-R** [comment]
I have the same issue with my Merten Wiser Shutter Controls after I upgraded OS and Core 3 or 4 days ago.
Only the shutters are displayed as 'not available'. 
All other Zigbee2MQTT devices are working normally. 
From the Zigbee2MQTT Front-End, the shutters are working and not producing any errors in the Zigbee2MQTT logs. So I suppose it must be related to the integration in HA and obviously with Window Shutters/ Covers.

**Zigbee2mqtt add-on version:**
```
Current version: 1.18.1-1
```
**Your entire configuration from the frontend (with sensitive fields redacted):**
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto
  user: mqtt
  password: mqtt
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: debug
  pan_id: 6756
  channel: 11
  network_key:
 [...]
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
zigbee_shepherd_devices: false
```
**Running platform (details from Suypervisor > System)**
```
OS: Home Assistant OS 6.0
Supervisor Version: supervisor-2021.06.0
Core Version: core-2021.6.3
```
**Your logs from Home Assistant Supervisor**
```
2021-06-12 08:31:07 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'availability': [{'topic': 'zigbee2mqtt/bridge/state'}], 'command_topic': 'zigbee2mqtt/Rolladenschalter02/set', 'device': {'identifiers': ['zigbee2mqtt_0x588e81fffe127538'], 'manufacturer': 'Schneider Electric', 'model': 'Merten PlusLink Shutter insert with Merten Wiser System M Push Button (MEG5113-0300/MEG5165-0000)', 'name': 'Rolladenschalter02', 'sw_version': 'Zigbee2MQTT 1.18.1'}, 'json_attributes_topic': 'zigbee2mqtt/Rolladenschalter02', 'name': 'Rolladenschalter02', 'position_topic': 'zigbee2mqtt/Rolladenschalter02', 'set_position_template': '{ "position": {{ position }} }', 'set_position_topic': 'zigbee2mqtt/Rolladenschalter02/set', 'unique_id': '0x588e81fffe127538_cover_zigbee2mqtt', 'value_template': '{{ value_json.position }}', 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 118, in validate_options
    raise vol.Invalid(
voluptuous.error.Invalid: 'value_template' must be set together with 'state_topic'.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 160, in async_discover
    config = schema(discovery_payload)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 337, in _exec
    v = func(v)
  File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 276, in __call__
    raise er.MultipleInvalid([e])
voluptuous.error.MultipleInvalid: 'value_template' must be set together with 'state_topic'.
```

**Comment by 7h0mas-R** [comment]
...might have something to do with [this](https://github.com/home-assistant/core/pull/50579) change on the MQTT integration - too tired to check today and probably to busy the next days... maybe you can have a closer look...
They also updated [the docs](https://www.home-assistant.io/integrations/cover.mqtt/)

**Comment by 7h0mas-R** [comment]
ok, I had some time to look a little more into details. I deleted and disconnected one of my shutter controllers from the zigbee-adapter and re-paired it.

I looked at the log again, and what struck me is, that the auto-discover message of the cover controls does not contain a `state_topic` but only a `position topic`. That fits with the error message that starts the error chain.
The LinkQuality sensor however has a `state_topic`and still gets properly displayed.

Then I looked into the Home Assistant Core code and came across the following Error-message:
```
       _LOGGER.warning(
            "Using 'value_template' for 'position_topic' is deprecated "
            "and will be removed from Home Assistant in version 2021.6, "
            "please replace it with 'position_template'"
        )
```

This might be the solution - would fit with the fact, that the problem started to occur after upgrading (in my case from a < 2021.6 version to 2021.6.3.
I'll try to send a correct auto-detect tomorrow, see if it works (do not want to mess with the covers now - kids are sleeping 😴
It then would need a small fix to the way zigbee2mqtt sends the auto-discover message to HA

**Comment by 7h0mas-R** [comment]
Had a short look into the sources, but could not locate the code, where the message is put together.
But when I roll back to HA core 2016.5.5 it works again - which would support my theory. I will not have time to dig further for the next 10 days. Maybe somebody else has time to check further.

Below is the message that zigbee2mqtt publishes. It has `value_template`for the position in the last line, where it should now have a `position_template`:
```
Zigbee2MQTT:info  2021-06-20 13: 47: 58: MQTT publish: topic 'homeassistant/cover/0xnnnnnnn/cover/config', payload '

{
    "availability": [
        {
            "topic": "zigbee2mqtt/bridge/state"
        }
    ],
    "command_topic": "zigbee2mqtt/0xnnnnnnn/set",
    "device": {
        "identifiers": [
            "zigbee2mqtt_ 0xnnnnnnn"
        ],
        "manufacturer": "Schneider Electric",
        "model": "Merten PlusLink Shutter insert with Merten Wiser System M Push Button (MEG5113-0300/MEG5165-0000)",
        "name": "0xnnnnnnn",
        "sw_version": "Zigbee2MQTT 1.18.1"
    },
    "json_attributes_topic": "zigbee2mqtt/0xnnnnnnn",
    "name": "0xnnnnnnn",
    "position_topic": "zigbee2mqtt/0xnnnnnnn",
    "set_position_template": "{ \"position\": {{ position }} }",
    "set_position_topic": "zigbee2mqtt/0xnnnnnnn/set",
    "unique_id": "0xnnnnnnn_cover_zigbee2mqtt",
    "value_template": "{{ value_json.position }}"
}
```

**Comment by 7h0mas-R** [comment]
Found the issue in the zigbee2mqtt source. It is not matching anymore with HomeAssistant core in zigbee2mqtt 1.18.1, which is currently the latest version for the Add-On.
However, in the newer zigbee2mqtt versions, it is already fixed, so it should only be a matter of time, until it arrives in the add-on:

This is the code with `value_template` in
[version 1.18.1](https://github.com/Koenkk/zigbee2mqtt/blob/a43d1f3917fee5516429bf1bf80419f1d2e0e7f8/lib/extension/homeassistant.js#L278-L285)

This is the code with `position_template` in
[version 1.19.1](https://github.com/Koenkk/zigbee2mqtt/blob/89cb4f95368423f55047d2529ec96ab762b74ca0/lib/extension/homeassistant.js#L296-L303)

**Comment by 7h0mas-R** [comment]
I am on vaccation , and had some more time to check. This is how to fix it:
* If you are on zigbee2mqtt plugin version 1.18.1, you may still be on the old repo and may have missed, that it changed ([see here](https://github.com/Koenkk/zigbee2mqtt/releases/tag/1.19.0)).
You need to replace the path under `supervisor` → `Add-on store` → `⠇` → `Repositories`
* Stop the plugin 1.18.1 and switch off restart at boot
* Install Zigbee2MQTT again from the store
* Copy the config from the old add-in to the new one
* Start the new add-on

This fixed everything for me.

**Comment by sweetpalma** [comment]
@7h0mas-R thanks, it worked!
