### ISSUE TITLE
Getting error messages in log and devices fails to update

### ISSUE THREAD

**Issue by mannigill1** [zigbee2mqtt/hassio-zigbee2mqtt#146]
**Description of problem:**
// Please do a short description of the problem

I am seeing below error in addon log. I have number of Xiaomi motion sensor's and they are not updating the status info. Once sensor shows state occupied it get stuck there for hours. Not sure if this is related below error that I see in logs. I have uninstalled, removed the zigbee2mqtt files from /share/ folder and re-insatlled the addon but still same issue.
I am using cc2531 usb adaptor

Zigbee2MQTT:error 2021-06-24 12:21:38: Failed to call 'Receive' 'onZigbeeEvent' (TypeError: Cannot read property 'constructor' of undefined
    at Zigbee.resolveEntity (/app/lib/zigbee.js:182:17)
    at Receive.onZigbeeEvent (/app/lib/extension/receive.js:109:42)
    at Controller.callExtensionMethod (/app/lib/controller.js:380:44))

// Make sure your problem is related to the add-on, not to core Zigbee2mqtt functionality, like problems with specific devices - for such issues use https://github.com/Koenkk/zigbee2mqtt/issues

**Zigbee2mqtt add-on version (if edge, please report commit hash):**

Current version: 1.18.1-1```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://<IP:1883>
  user: <username>
  password: <password>
serial:
  port: /dev/ttyACM0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.2.2
Supervisor: supervisor-2021.02.6
Operating System: HassOS 5.4
```

**Your logs from Home Assistant Supervisor**


1-06-24 01:50:47 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.SERVICES' starting 2 add-ons
21-06-24 01:50:49 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on ghcr.io/hassio-addons/adguard/armv7 with version 3.0.0
21-06-24 01:50:52 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-ssh with version 9.1.3
21-06-24 01:50:57 INFO (MainThread) [supervisor.core] Start Home Assistant Core
21-06-24 01:51:16 INFO (SyncWorker_6) [supervisor.docker.interface] Starting homeassistant
21-06-24 01:51:17 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-06-24 01:51:40 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.STARTUP
21-06-24 01:51:40 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-06-24 01:51:49 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-06-24 01:51:58 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
21-06-24 01:52:02 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-06-24 01:52:02 INFO (MainThread) [supervisor.addons] Phase 'AddonStartup.APPLICATION' starting 2 add-ons
21-06-24 01:52:05 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on homeassistant/armv7-addon-configurator with version 5.3.1
21-06-24 01:52:05 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 01:52:05 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 01:52:05 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 01:52:05 WARNING (SyncWorker_1) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 01:52:05 WARNING (SyncWorker_1) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 01:52:05 WARNING (SyncWorker_1) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 01:52:08 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-armv7 with version 1.18.1-1
21-06-24 01:52:13 INFO (MainThread) [supervisor.misc.tasks] All core tasks are scheduled
21-06-24 01:52:13 INFO (MainThread) [supervisor.core] Supervisor is up and running
21-06-24 01:52:13 INFO (MainThread) [supervisor.host.info] Updating local host information
21-06-24 01:52:13 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
21-06-24 01:52:13 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-06-24 01:52:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-06-24 01:52:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-06-24 01:52:13 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-06-24 01:52:13 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
21-06-24 01:52:13 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 01:52:13 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 01:52:13 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 01:52:13 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-06-24 01:52:13 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-06-24 01:52:15 INFO (MainThread) [supervisor.host.services] Updating service information
21-06-24 01:52:15 INFO (MainThread) [supervisor.host.network] Updating local network information
21-06-24 01:52:19 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-06-24 01:52:19 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-06-24 01:52:19 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-06-24 01:52:20 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
21-06-24 01:52:20 INFO (MainThread) [supervisor.host] Host information reload completed
21-06-24 01:52:58 INFO (MainThread) [supervisor.snapshots] Creating new partial-snapshot with slug 28c73eaf
21-06-24 01:52:58 INFO (MainThread) [supervisor.snapshots] Snapshotting 28c73eaf store folders
21-06-24 01:52:58 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder homeassistant
21-06-24 01:53:30 INFO (SyncWorker_7) [supervisor.snapshots.snapshot] Snapshot folder homeassistant done
21-06-24 01:53:32 INFO (MainThread) [supervisor.snapshots] Creating partial-snapshot with slug 28c73eaf completed
21-06-24 01:53:32 INFO (MainThread) [supervisor.homeassistant.core] Updating Home Assistant to version 2021.6.6
21-06-24 01:53:32 INFO (SyncWorker_5) [supervisor.docker.interface] Updating image ghcr.io/home-assistant/raspberrypi3-homeassistant:2021.6.5 to homeassistant/raspberrypi3-homeassistant:2021.6.6
21-06-24 01:53:32 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image homeassistant/raspberrypi3-homeassistant with tag 2021.6.6.
21-06-24 01:58:17 INFO (SyncWorker_5) [supervisor.docker.interface] Stopping homeassistant application
21-06-24 01:58:28 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning homeassistant application
21-06-24 01:58:28 INFO (MainThread) [supervisor.homeassistant.module] Update pulse/client.config: /data/tmp/homeassistant_pulse
21-06-24 01:58:29 INFO (SyncWorker_3) [supervisor.docker.homeassistant] Starting Home Assistant homeassistant/raspberrypi3-homeassistant with version 2021.6.6
21-06-24 01:58:29 INFO (MainThread) [supervisor.homeassistant.core] Wait until Home Assistant is ready
21-06-24 01:58:48 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-06-24 01:58:49 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-06-24 01:59:13 WARNING (MainThread) [supervisor.addons.options] Option 'anonymous' does not exist in the schema for Mosquitto broker (core_mosquitto)
21-06-24 01:59:18 INFO (MainThread) [supervisor.homeassistant.core] Detect a running Home Assistant instance
21-06-24 01:59:18 INFO (MainThread) [supervisor.homeassistant.core] Successful started Home Assistant 2021.6.6
21-06-24 01:59:18 INFO (SyncWorker_2) [supervisor.docker.interface] Cleanup images: ['ghcr.io/home-assistant/raspberrypi3-homeassistant:2021.6.5']
21-06-24 02:22:14 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-06-24 02:45:34 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 02:45:34 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 02:45:34 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 02:46:44 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 02:46:44 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 02:46:44 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 02:48:03 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 02:48:03 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 02:48:03 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 02:50:54 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
21-06-24 02:50:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
21-06-24 02:50:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
21-06-24 02:50:54 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
21-06-24 02:50:54 INFO (MainThread) [supervisor.resolution.check] System checks complete
21-06-24 02:50:54 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
21-06-24 02:50:54 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
21-06-24 02:50:54 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
21-06-24 02:50:54 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
21-06-24 02:52:15 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
21-06-24 02:55:38 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 02:55:38 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 02:55:38 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 03:03:21 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 03:03:21 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
21-06-24 03:03:21 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt (7ad98f9c_zigbee2mqtt)
```

**Comment by mannigill1** [comment]
My issue was resolved after changing the wifi channel and moving my gateway away from wifi router
