### ISSUE TITLE
502 bad gateway after modem reset,

### ISSUE THREAD

**Issue by RoBro92** [zigbee2mqtt/hassio-zigbee2mqtt#152]
Having issues reaching my zigbee devices, IP has not changed for the hub 

log below 
```
s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[12:40:22] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[12:40:23] INFO: MQTT available, fetching server detail ...
[12:40:23] INFO: MQTT server settings not configured, trying to auto-discovering ...
[12:40:24] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[12:40:24] INFO: MQTT credentials not configured, trying to auto-discovering ...
[12:40:24] INFO: Configuring'addons' mqtt user
[12:40:24] INFO: Previous config file found, checking backup
[12:40:24] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[12:40:25] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:40:25] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
Zigbee2MQTT:error 2021-07-19 12:40:30: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-07-19 12:40:30: Failed to start zigbee
Zigbee2MQTT:error 2021-07-19 12:40:30: Exiting...
Zigbee2MQTT:error 2021-07-19 12:40:30: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-19T11_40_30_552Z-debug.log
[12:40:30] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
```

**Comment by ciotlosm** [comment]
Your serial port is not accessible, or it changed (Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'). 

Check your hardware in System tab for the supervisor and see which serial ports you have available.
