### ISSUE TITLE
Stop working on 2 similar servers after update to supervisor-2021.09.0

### ISSUE THREAD

**Issue by dekamilv** [zigbee2mqtt/hassio-zigbee2mqtt#185]
Worked properly few years. Yesterday installed updates supervisor-2021.09.0 and on both servers Zigbee2mqtt not working any more......Cant believe USB sticks died in one time in two servers locates in 2 sides of the city.....

Zigbee2MQTT:info  2021-09-07 13:31:45: Starting Zigbee2MQTT version 1.21.1-dev (commit #291383f)
Zigbee2MQTT:info  2021-09-07 13:31:45: Starting zigbee-herdsman (0.13.142)
Zigbee2MQTT:error 2021-09-07 13:32:04: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-09-07 13:32:04: Failed to start zigbee
Zigbee2MQTT:error 2021-09-07 13:32:04: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-09-07 13:32:04: Exiting...
Zigbee2MQTT:error 2021-09-07 13:32:05: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.js:113:27)
    at start (/app/index.js:95:5)
```

```

ata_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://homeassistant
  user: ****
  password: *****
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0   ((SAME issue with /dev/ttyUSB0)
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 13
    - 11
    - 15
    - 0
    - 2
    - 4
    - 6
    - 12
    - 10
    - 8
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: pty,raw,echo=0,link=/dev/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
```

Core: core-2021.9.4
Supervisor: supervisor-2021.09.0
Operating System: Home Assistant OS 6.3
```

**Your logs from Home Assistant Supervisor**
```
21-09-07 13:30:37 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_7ad98f9c_zigbee2mqtt_edge application
21-09-07 13:30:41 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_7ad98f9c_zigbee2mqtt_edge application
21-09-07 13:30:41 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 13:30:41 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 13:30:41 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 13:30:41 WARNING (SyncWorker_0) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 13:30:41 WARNING (SyncWorker_0) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 13:30:41 WARNING (SyncWorker_0) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 13:30:42 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-edge-aarch64 with version edge
21-09-07 13:30:42 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 13:30:42 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 13:30:42 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 13:33:14 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 13:33:14 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 13:33:14 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)


```

**Comment by dekamilv** [comment]
That's absolutely strange.... i solve this issue just by unplugging server from electricity for few minutes ...... 
But anyway, downgraded to core-2021.5.4 and core-2021.7.4 -   too much issues with core-2021.9.4.

but errors still here 


21-09-07 21:23:20 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:20 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:20 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:35 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:35 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:35 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:35 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:35 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:35 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:35 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:35 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:35 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:47 WARNING (MainThread) [supervisor.addons.options] Unknown option 'new_api' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:47 WARNING (MainThread) [supervisor.addons.options] Unknown option 'restartdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
21-09-07 21:23:47 WARNING (MainThread) [supervisor.addons.options] Unknown option 'initialdelay' for Zigbee2mqtt Edge (7ad98f9c_zigbee2mqtt_edge)
