### ISSUE TITLE
Cannot connect ConBee II to new installation of HA

### ISSUE THREAD

**Issue by Araxion** [zigbee2mqtt/hassio-zigbee2mqtt#247]
Hi, since yesterday i am trying to make clean installation of HA with Zigbee2MQTT, but still getting errors:

`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[13:08:37] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[13:08:38] INFO: MQTT available, fetching server detail ...
[13:08:38] INFO: MQTT server settings not configured, trying to auto-discovering ...
[13:08:39] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[13:08:39] INFO: Previous config file found, checking backup
[13:08:39] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[13:08:39] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:08:40] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
Zigbee2MQTT:error 2021-12-04 13:09:03: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-12-04 13:09:03: Failed to start zigbee
Zigbee2MQTT:error 2021-12-04 13:09:03: Exiting...
Zigbee2MQTT:error 2021-12-04 13:09:03: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-12-04T12_09_03_245Z-debug.log
[13:09:03] INFO: Handing over control to Zigbee2mqtt Core ...
`

Port is alive

`
pi@raspberrypi:~ $ test -w /dev/ttyACM0 && echo success || echo failure success

success
`

**Comment by avernan** [comment]
I had a similar issue (Failed to connect to the adapter) and it was solved by changing the config to include
`adapter: deconz` under `serial`

**Comment by Cic0r** [comment]
Same issue to me, even `adapter: deconz` won't work:

> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[20:00:32] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[20:00:33] INFO: MQTT available, fetching server detail ...
[20:00:33] INFO: MQTT server settings not configured, trying to auto-discovering ...
[20:00:34] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[20:00:34] INFO: MQTT credentials not configured, trying to auto-discovering ...
[20:00:34] INFO: Configuring'addons' mqtt user
[20:00:34] INFO: Previous config file found, checking backup
[20:00:34] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[20:00:34] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:00:36] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.1 start
> node index.js
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2021-12-17 20:00:52: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-12-17 20:00:52: Failed to start zigbee
Zigbee2MQTT:error 2021-12-17 20:00:52: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2021-12-17 20:00:52: Exiting...
Zigbee2MQTT:error 2021-12-17 20:00:52: undefined
[20:00:53] INFO: Handing over control to Zigbee2mqtt Core ...

>
