### ISSUE TITLE
Build core-2021.12.x breaks Zigbee2mqtt

### ISSUE THREAD

**Issue by Tokn59** [zigbee2mqtt/hassio-zigbee2mqtt#258]
The problem
Zigbee2mqtt does no longer start nor does it report status of devices and map function does not work anymore.

What version of Home Assistant Core has the issue?
2021.12.0

What was the last working version of Home Assistant Core?
2021.11.2

What type of installation are you running?
Home Assistant OS

Integration causing the issue
Zigbee2mqtt

Link to integration documentation on our website
No response

Example YAML snippet
Not applicable
Anything in the logs that might be useful for us?

Logfile :

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[13:35:17] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[13:35:17] INFO: MQTT available, fetching server detail ...
[13:35:18] INFO: MQTT server settings not configured, trying to auto-discovering ...
[13:35:18] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[13:35:18] INFO: Previous config file found, checking backup
[13:35:18] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[13:35:18] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:35:19] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.1 start
> node index.js
CREATED DECONZ ADAPTER
Zigbee2MQTT:warn  2021-12-18 13:35:25: Using experimental new availability feature

Additional information
Returning to previous build resolves the issue.

**Comment by thomaspalmdk** [comment]
I just want to add, that I have kind of the same problem.
After upgrading to 2021.12 Zigbee devices which sends signals in to hass does not work but signals going out works fine.
Ie. my remote does not work, but light-controlling from hass does.

**Comment by troicus** [comment]
I have also a problem with version >2021.12.X and Zigbee2mqtt. It's running but report status of devices does not work anymore. The entities could not be found after upgrade.

Returning to previous build 2021.11.5 resolves the issue.

**Comment by jbytheway** [comment]
I was trying to set up a new instance of Home Assistant today and found that the addon repository itself doesn't even work on 2021.12.5.  After adding the custom repository the two zigbee2mqtt addons still don't appear.  Downgrading to 2021.11.5 resolves that.

**Comment by 10n** [comment]
> I was trying to set up a new instance of Home Assistant today and found that the addon repository itself doesn't even work on 2021.12.5. After adding the custom repository the two zigbee2mqtt addons still don't appear. Downgrading to 2021.11.5 resolves that.

How to you install a previous version? I thought about forking the repository ... is there a simpler way ?

**Comment by jbytheway** [comment]
> How to you install a previous version? I thought about forking the repository ... is there a simpler way ?

https://community.home-assistant.io/t/how-to-downgrade-home-assistant/179735

**Comment by Peyoz** [comment]
There is something broken around, I suppose homeassistant changed something on their side.
The result is that my setup is completely broken, right now
I tested a fresh install of HASSOS 2021.12.7 and I can not even start my Conbee II adapter.
switching to ZHA works fine, looks something changed in the container stack.
```
[01:58:28] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.1 start
> node index.js
2021-12-30T00:58:34.704Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2021-12-30T00:58:34.712Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyACM0"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2021-12-30T00:58:34.713Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/ttyACM0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2021-12-30T00:58:34.729Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
2021-12-30T00:58:34.732Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-12-30T00:58:34.736Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2021-12-30T00:58:34.992Z zigbee-herdsman:adapter:zStack:znp:log Writing CC2530/CC2531 skip bootloader payload
2021-12-30T00:58:34.995Z zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]
2021-12-30T00:58:35.998Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-12-30T00:58:36.002Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2021-12-30T00:58:36.254Z zigbee-herdsman:adapter:zStack:znp:log Skip bootloader for CC2652/CC1352
2021-12-30T00:58:36.714Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-12-30T00:58:36.715Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2021-12-30T00:58:42.721Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-12-30T00:58:42.725Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2021-12-30T00:58:48.731Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-12-30T00:58:48.732Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
Zigbee2MQTT:error 2021-12-30 01:58:54: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-12-30 01:58:54: Failed to start zigbee
Zigbee2MQTT:error 2021-12-30 01:58:54: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2021-12-30 01:58:54: Exiting...
Zigbee2MQTT:error 2021-12-30 01:58:55: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:97:5)
[01:58:55] INFO: Zigbee Herdsman debug logging enabled
[01:58:55] INFO: Handing over control to Zigbee2mqtt Core ...
```

**Comment by cromelex** [comment]
Have the exact same issue as the first post at the moment with a new installation, it will hang after the creating the deconz adapter and it doesn't seem to move any further. The WebUI gets stuck on loading at the same time.

This is happening with 2021.12.7


INFO: Handing over control to Zigbee2mqtt Core ...
zigbee2mqtt@1.22.1 start
node index.js
CREATED DECONZ ADAPTER
Zigbee2MQTT:warn xxx  Using experimental new availability feature

**Comment by Peyoz** [comment]
I managed to somehow workaround by connecting the ConBee adapter to another system, and using the remote adapter feature.
I used this guide [https://www.zigbee2mqtt.io/advanced/remote-adapter/connect_to_a_remote_adapter.html#_2-b-configure-ser2net-4-0](url)

**Comment by cromelex** [comment]
Not sure if this helps, but the issue doesn't show if I use the zigbee2mqtt-edge version instead.
