### ISSUE TITLE
502: Bad Gateway - Fresh Install Issue

### ISSUE THREAD

**Issue by mike10101011** [zigbee2mqtt/hassio-zigbee2mqtt#275]
**Description of problem:**
Receiving error: 502: Bad Gateway
This is a fresh install completely, even for HA. I installed Z2M and MQTT Broker. Setup user/pass for MQTT and inputted in Z2M config. Based on the guides I've been looking at, the UI should be showing, but this is where I'm receiving the error. 

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
`Current version: 1.22.2-1 (New install)`

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: mqtt_user
  password: ****
serial:
  port: /dev/ttyACM0
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
zigbee_herdsman_debug: true
```

**Running platform (details from Suypervisor > System)**
```
Version core-2021.12.10
Version supervisor-2021.12.2
Windows 10, running VirtualBox, Operating System Home Assistant OS 7.1
```

**Your logs from Home Assistant Supervisor**
I have logs set to debug as well as zigbee_herdsman_debug: true, so there's a bit more than others I've seen. Hope that helps. 
```
[21:57:57] INFO: Zigbee Herdsman debug logging enabled
[21:57:57] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2 start
> node index.js
Zigbee2MQTT:debug 2022-01-20 21:57:58: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2022-01-20 21:57:58: Logging to console and directory: '/config/zigbee2mqtt/log/2022-01-20.21-57-58' filename: log.txt
Zigbee2MQTT:debug 2022-01-20 21:57:58: Removing old log directory '/config/zigbee2mqtt/log/2022-01-20.21-48-32'
Zigbee2MQTT:info  2022-01-20 21:57:58: Starting Zigbee2MQTT version 1.22.2 (commit #unknown)
Zigbee2MQTT:info  2022-01-20 21:57:58: Starting zigbee-herdsman (0.13.188)
Zigbee2MQTT:debug 2022-01-20 21:57:58: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyACM0"}}'
2022-01-21T03:57:58.848Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2022-01-21T03:57:58.849Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyACM0"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2022-01-21T03:57:58.850Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/ttyACM0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2022-01-21T03:57:58.854Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
2022-01-21T03:57:58.855Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2022-01-21T03:57:58.856Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2022-01-21T03:57:59.108Z zigbee-herdsman:adapter:zStack:znp:log Writing CC2530/CC2531 skip bootloader payload
2022-01-21T03:57:59.109Z zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]
2022-01-21T03:58:00.111Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2022-01-21T03:58:00.113Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2022-01-21T03:58:00.365Z zigbee-herdsman:adapter:zStack:znp:log Skip bootloader for CC2652/CC1352
2022-01-21T03:58:00.831Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2022-01-21T03:58:00.833Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2022-01-21T03:58:06.834Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2022-01-21T03:58:06.835Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2022-01-21T03:58:12.837Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2022-01-21T03:58:12.838Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
Zigbee2MQTT:error 2022-01-20 21:58:18: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-01-20 21:58:18: Failed to start zigbee
Zigbee2MQTT:error 2022-01-20 21:58:18: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-01-20 21:58:18: Exiting...
Zigbee2MQTT:error 2022-01-20 21:58:18: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:102:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:123:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:100:27)
    at start (/app/index.js:97:5)
```

I also know this is a common question, so here's the Conbee II device info:
```
Subsystem: tty
Device path:
/dev/ttyACM0
ID:
/dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2477219-if00
```

**Comment by LucasHokerberg** [comment]
Same issue here. Fresh install of both MQTT Broker and Zigbee2Mqtt. I have the exact same error about not being able to connect to the adapter. I recently used the ConBee II device in ZHA for testing, and now wants to test Zigbee2Mqtt as well.

I know my ConBee device is working as HA is autodiscovering it and asking med to configure ZHA.

**Comment by LucasHokerberg** [comment]
I managed to get it working with some help from this issue: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/247

In the config under serial, add "adapter: deconz".

**Comment by mike10101011** [comment]
> I managed to get it working with some help from this issue: #247
> 
> In the config under serial, add "adapter: deconz".

Still no luck. Added it between serial and port. It rearranged itself to be right after port. But I restarted all of HA, and it didn't work. However, error changed a bit. It now shows it's undefined at the end. 

```
Zigbee2MQTT:error 2022-01-21 08:57:10: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-01-21 08:57:10: Failed to start zigbee
Zigbee2MQTT:error 2022-01-21 08:57:11: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-01-21 08:57:11: Exiting...
Zigbee2MQTT:error 2022-01-21 08:57:11: undefined
```

**Comment by mike10101011** [comment]
https://www.zigbee2mqtt.io/guide/adapters/#recommended

I followed the instructions on the Conbee II option. Deconz did not install automatically on my PC, so I did the manual install. After a restart, it started working.

**Comment by Pierrocito** [comment]
You must go to "integration" delete "Mosquito broker" restart Home assistant. If you dongle is connected home assistant will discover from us "Mosquito broker" you just have to press contiguous then submit and finish.
The message in Zigbee2Mqtt "502: Bad Gateway" will disappear.
