### ISSUE TITLE
YALE YMF40 door lock failed to interview

### ISSUE THREAD

**Issue by EvertonAdroit** [zigbee2mqtt/hassio-zigbee2mqtt#282]
**Description of problem:**
I have a Yale YMF40 and a YRL226L door locks and the pairing process was flawless with the YRL, but with the YMF I keep getting this errors (I enabled the zigbee_herdsman_debug):

Error Failed to configure 'Fechadura Sala', attempt 1 (Error: Bind 0x000d6f0016fdc36f/1 closuresDoorLock from '0x00124b00256c5557/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (internal/timers.js:557:17) at processTimers (internal/timers.js:500:7))
Error Failed to interview 'Fechadura Sala', device has not successfully been paired
Error Failed to configure 'Fechadura Sala', attempt 2 (Error: Bind 0x000d6f0016fdc36f/1 genPowerCfg from '0x00124b00256c5557/1' failed (AREQ - ZDO - bindRsp after 10000ms) at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35) at listOnTimeout (internal/timers.js:557:17) at processTimers (internal/timers.js:500:7))

I've already tried removing the batteries and starting again. Got it very close to the coordinator and the router (tried without the router connected as well). Basically tried every tips from here https://www.zigbee2mqtt.io/guide/faq/ with no success.

I can control the lock, but it won't show battery status neither send its current status back to home assistant.

I'm using 2 of the new sonoff zigbee 3.0 dongle flashed for coordinator and router.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.22.2-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  user: *****
  password: ****
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: warn
  pan_id: 6759
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
zigbee_herdsman_debug: true
```

**Running platform (details from Suypervisor > System)**
```
// Example
Core: core-2021.12.10
Supervisor: supervisor-2021.12.2
Operating System: Home Assistant OS 7.2
```

**Your logs from Home Assistant Supervisor**
```
22-01-28 17:32:32 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-01-28 17:32:33 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-01-28 17:32:33 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-01-28 17:32:33 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-01-28 17:32:33 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-01-28 17:32:33 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-01-28 17:32:33 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-01-28 17:33:17 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-01-28 17:41:45 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-01-28 17:48:44 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-01-28 17:48:44 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
22-01-28 18:11:49 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-01-28 18:32:33 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-01-28 18:32:33 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-01-28 18:32:33 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-01-28 18:32:33 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-01-28 18:32:33 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-01-28 18:32:33 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-01-28 18:32:33 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-01-28 18:32:33 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-01-28 18:32:33 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-01-28 18:32:33 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-01-28 18:32:33 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-01-28 18:32:33 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-01-28 18:35:42 INFO (MainThread) [supervisor.store.git] Update add-on http://github.com/danmed/TasmoBackupV1 repository
22-01-28 18:35:42 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-01-28 18:35:42 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-01-28 18:35:42 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/sabeechen/hassio-google-drive-backup repository
22-01-28 18:35:42 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/zigbee2mqtt/hassio-zigbee2mqtt repository
22-01-28 18:35:48 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove
22-01-28 18:35:48 INFO (MainThread) [supervisor.store] Loading add-ons from store: 66 all - 0 new - 0 remove
22-01-28 18:41:50 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-01-28 18:48:48 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-01-28 18:48:48 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
22-01-28 19:11:50 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-01-28 19:26:06 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/ttyUSB0 - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_a8729e00d91aec119dd97fe5f01c6278-if00-port0
22-01-28 19:26:06 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/gpiochip0 - None
22-01-28 19:26:06 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/bus/usb/002/003 - None
22-01-28 19:27:03 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/bus/usb/002/004 - None
22-01-28 19:27:03 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/gpiochip0 - None
22-01-28 19:27:03 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/ttyUSB0 - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_a8729e00d91aec119dd97fe5f01c6278-if00-port0
22-01-28 19:32:33 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-01-28 19:32:33 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.CORE
22-01-28 19:32:33 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-01-28 19:32:33 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-01-28 19:32:33 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-01-28 19:32:33 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.PLUGIN
22-01-28 19:32:34 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-01-28 19:32:34 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-01-28 19:32:34 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-01-28 19:32:34 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-01-28 19:32:34 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-01-28 19:32:34 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-01-28 19:33:17 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-01-28 19:34:31 INFO (MainThread) [supervisor.host.info] Updating local host information
22-01-28 19:34:33 INFO (MainThread) [supervisor.host.services] Updating service information
22-01-28 19:34:33 INFO (MainThread) [supervisor.host.network] Updating local network information
22-01-28 19:34:33 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
22-01-28 19:34:33 INFO (MainThread) [supervisor.host.manager] Host information reload completed
22-01-28 19:35:53 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/ttyUSB0 - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_a8729e00d91aec119dd97fe5f01c6278-if00-port0
22-01-28 19:35:53 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/gpiochip0 - None
22-01-28 19:35:53 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.REMOVE hardware /dev/bus/usb/002/004 - None
22-01-28 19:36:02 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.8:8099 ssl:default [Connect call failed ('172.30.33.8', 8099)]
22-01-28 19:36:28 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/bus/usb/002/005 - None
22-01-28 19:36:28 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/gpiochip0 - None
22-01-28 19:36:28 INFO (MainThread) [supervisor.hardware.monitor] Detecting HardwareAction.ADD hardware /dev/ttyUSB0 - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_a8729e00d91aec119dd97fe5f01c6278-if00-port0
22-01-28 19:38:53 INFO (SyncWorker_2) [supervisor.docker.interface] Stopping addon_45df7312_zigbee2mqtt application
22-01-28 19:38:56 INFO (SyncWorker_2) [supervisor.docker.interface] Cleaning addon_45df7312_zigbee2mqtt application
22-01-28 19:38:57 INFO (SyncWorker_4) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.22.2-1
22-01-28 19:41:51 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-01-28 19:48:50 INFO (MainThread) [supervisor.api.middleware.security] /supervisor/info access from cebe7a76_hassio_google_drive_backup
22-01-28 19:48:50 INFO (MainThread) [supervisor.api.middleware.security] /backups access from cebe7a76_hassio_google_drive_backup
```

**Comment by EvertonAdroit** [comment]
I'm still having this problem. And now that I'm doing some automations with Node-RED, I realized that the lock won't sent any message when it is unlocked via fingerprint, but it will send messages normally when using password or commands via Home Assistant
