### ISSUE TITLE
Zigbee2mqtt add-on not starting "Cannot lock port" with Conbee II

### ISSUE THREAD

**Issue by dustinosity** [zigbee2mqtt/hassio-zigbee2mqtt#304]
**Description of problem:**
Zigbee2mqtt add-on no longer starts after updating and rebooting system (was working perfectly fine previously and reboots were never a problem). Logs showing `Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port` 

I'm running Home Assistant OS on an ODROID with a Conbee II stick.

I think it's a permission issue since no other processes appear to be connected to the device. `test -w /dev/ttyACM0 && echo success || echo failure` returns success when run as root. I'm unclear as to how to change the permissions / what user the add-on is running as. 

One other oddity that I'm noticing is that the group for the device is `audio` and not `tty` or `dialout` etc. 
`crw-rw---- 1 root audio 166, 0 Mar 19 18:53 /dev/ttyACM0`

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@1.24.0-1 
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyACM0
  adapter: deconz
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
zigbee_herdsman_debug: true
```

**Running platform (details from Suypervisor > System)**
```
Core: core-2022.3.5
Supervisor: supervisor-2022.03.5
Operating System: Home Assistant OS 7.5
```

**Your logs from Home Assistant Supervisor**
```
Zigbee2MQTT:debug 2022-03-19 19:03:56: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2022-03-19 19:03:56: Logging to console and directory: '/config/zigbee2mqtt/log/2022-03-19.19-03-54' filename: log.txt
Zigbee2MQTT:debug 2022-03-19 19:03:56: Removing old log directory '/config/zigbee2mqtt/log/2022-03-19.19-03-13'
Zigbee2MQTT:info  2022-03-19 19:03:56: Starting Zigbee2MQTT version 1.24.0 (commit #unknown)
Zigbee2MQTT:info  2022-03-19 19:03:56: Starting zigbee-herdsman (0.14.20)
Zigbee2MQTT:debug 2022-03-19 19:03:56: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6755},"serialPort":{"adapter":"deconz","path":"/dev/ttyACM0"}}'
2022-03-20T02:03:56.709Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2022-03-20T02:03:56.711Z zigbee-herdsman:deconz:driver Set delay to 0
CREATED DECONZ ADAPTER
2022-03-20T02:03:56.713Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6755,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyACM0","adapter":"deconz"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2022-03-20T02:03:56.714Z zigbee-herdsman:deconz:driver Opening with /dev/ttyACM0
Zigbee2MQTT:error 2022-03-19 19:03:56: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-03-19 19:03:56: Failed to start zigbee
Zigbee2MQTT:error 2022-03-19 19:03:56: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-03-19 19:03:56: Exiting...
Zigbee2MQTT:error 2022-03-19 19:03:56: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/deconz/driver/driver.ts:182:28)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
[19:03:56] INFO: Zigbee Herdsman debug logging enabled
[19:03:57] INFO: Handing over control to Zigbee2mqtt Core ...
```

**Comment by kokrp** [comment]
I have exactly the same errors and logging/output. Main difference is I'm running an RPI4.
