### ISSUE TITLE
Error: spawn udevadm ENOENT (resulting in 502: bad gateway)

### ISSUE THREAD

**Issue by ralhei** [zigbee2mqtt/hassio-zigbee2mqtt#319]
**Description of problem:**
I installed everything from scratch today on a raspberry4:
- HomeAssistant OS
- hassio-zigbee2mqtt (via add-on repository from https://github.com/zigbee2mqtt/hassio-zigbee2mqtt)

No special configuration setups, everything pretty much using default config values. Only added `zigbee_herdsman_debug flag` after I got the problems described here.

Zigbee2mqtt in the UI reports a `"502: Bad gateway"` error.
The logs (see below) report:  `Error: spawn udevadm ENOENT`

Restarting HA or the entire raspberry did not solve this issue.

I use a zigstar USB stick V4, obtained today.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.25.0-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
I hope this is what is meant to be provided:
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt: {}
serial: {}
zigbee_herdsman_debug: true
```

**Running platform (details from Suypervisor > System)**
```
Version 	core-2022.3.8
Installation Type 	Home Assistant OS
Development 	false
Supervisor 	true
Docker 	true
User 	root
Virtual Environment 	false
Python Version 	3.9.9
Operating System Family 	Linux
Operating System Version 	5.10.103-v8
CPU Architecture 	aarch64
Host Operating System 	Home Assistant OS 7.6
Update Channel 	stable
Supervisor Version 	supervisor-2022.03.5
Docker Version 	20.10.9
Disk Total 	14.1 GB
Disk Used 	2.7 GB
Healthy 	true
Supported 	true
Board 	rpi4-64
Supervisor API 	ok
Version API 	ok
Installed Add-ons 	Mosquitto broker (6.0.1), Zigbee2mqtt (1.25.0-1), Terminal & SSH (9.3.0)```
```

**Your logs from Home Assistant Supervisor**
```
Zigbee2MQTT:debug 2022-04-04 22:31:12: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2022-04-04 22:31:12: Logging to console and directory: '/config/zigbee2mqtt/log/2022-04-04.22-31-09' filename: log.txt
Zigbee2MQTT:debug 2022-04-04 22:31:12: Removing old log directory '/config/zigbee2mqtt/log/2022-04-04.22-29-47'
Zigbee2MQTT:info  2022-04-04 22:31:12: Starting Zigbee2MQTT version 1.25.0 (commit #unknown)
Zigbee2MQTT:info  2022-04-04 22:31:12: Starting zigbee-herdsman (0.14.20)
Zigbee2MQTT:debug 2022-04-04 22:31:12: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{}}'
2022-04-04T20:31:12.587Z zigbee-herdsman:adapter No path provided, auto detecting path
Zigbee2MQTT:error 2022-04-04 22:31:12: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-04-04 22:31:12: Failed to start zigbee
Zigbee2MQTT:error 2022-04-04 22:31:12: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-04-04 22:31:12: Exiting...
Zigbee2MQTT:error 2022-04-04 22:31:12: Error: spawn udevadm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
[22:31:12] INFO: Zigbee Herdsman debug logging enabled
[22:31:14] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.25.0 start
> node index.js
```

**Comment by kumboleijo** [comment]
👍 Facing the same issue! I wanted to switch from ZHA to Z2M. My steps so far:
- uninstall ZHA
- restart HA
- install Addon Zigbee2mqtt (1.25.0-1)
- add `frontend` and `debug` configuration

**Config**
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt: {}
serial: {}
zigbee_herdsman_debug: true
frontend:
  port: 8099
```

**Logs**
```
> zigbee2mqtt@1.25.0 start
> node index.js
Zigbee2MQTT:debug 2022-04-05 14:21:38: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2022-04-05 14:21:38: Logging to console and directory: '/config/zigbee2mqtt/log/2022-04-05.14-21-36' filename: log.txt
Zigbee2MQTT:debug 2022-04-05 14:21:39: Removing old log directory '/config/zigbee2mqtt/log/2022-04-05.14-20-00'
Zigbee2MQTT:info  2022-04-05 14:21:39: Starting Zigbee2MQTT version 1.25.0 (commit #unknown)
Zigbee2MQTT:info  2022-04-05 14:21:39: Starting zigbee-herdsman (0.14.20)
Zigbee2MQTT:debug 2022-04-05 14:21:39: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{}}'
2022-04-05T12:21:39.397Z zigbee-herdsman:adapter No path provided, auto detecting path
Zigbee2MQTT:error 2022-04-05 14:21:39: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-04-05 14:21:39: Failed to start zigbee
Zigbee2MQTT:error 2022-04-05 14:21:39: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-04-05 14:21:39: Exiting...
Zigbee2MQTT:error 2022-04-05 14:21:39: Error: spawn udevadm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**System**
```
arch: aarch64
channel: stable
docker: 20.10.9
features:
- reboot
- shutdown
- services
- network
- hostname
- timedate
- os_agent
- haos
hassos: "7.6"
homeassistant: 2022.3.8
hostname: homeassistant
logging: info
machine: raspberrypi4-64
operating_system: Home Assistant OS 7.6
state: running
supervisor: 2022.03.5
supported: true
supported_arch:
- aarch64
- armv7
- armhf
timezone: Europe/Berlin
```

I tried multiple restarts of `HA` after the installation of the plugin but it just won't start.

**Comment by kumboleijo** [comment]
**update**: I was able to solve the issue by properly setting the serial port to my zigbee coordinator.

**Solution**

Add serial port configuration:

```
serial:
  port: /dev/ttyACM0
```

I find it a bit misleading that the service cannot boot properly with default configurations.
