### ISSUE TITLE
Home Assistant 1.25.1 not working 

### ISSUE THREAD

**Issue by cisco351** [zigbee2mqtt/hassio-zigbee2mqtt#334]
After upgrading to the latest version 1.25.1 add-on in home assistant it quit working. I am using two external converters. One for a zemismart zs811 switch and one for the Aqara P1 motion sensor. 

I get error messages in the log. see below
 (  node index.js
(node:18332) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'options' of undefined
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:91:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:83:58)
    at start (/app/index.js:109:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18332) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18332) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.)

Configuration: 
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: xxxxxx
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_d23f758ec9c9eb11aa218d4f1d69213e-if00-port0
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
advanced:
  log_level: debug
  pan_id: 6754
  channel: 15
  network_key: xxxx
    
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
transmit_power: 9
zigbee_herdsman_debug: true

Home Assistant version: 
Core
Version
core-2022.4.7
Supervisor
Version
supervisor-2022.04.0
HA Blue

**Your logs from Home Assistant Supervisor**
```
// 22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:27:05 WARNING (MainThread) [supervisor.addons.options] Option 'transmit_power' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:31:41 WARNING (MainThread) [supervisor.addons.options] Option 'transmit_power' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'dark_mode' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'require_ssl' does not exist in the schema for Node-RED (a0d7b954_nodered)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'interface' does not exist in the schema for Samba share (core_samba)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Unknown option 'base_topic' for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'external_converters' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'devices' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'groups' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'homeassistant' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'permit_join' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'advanced' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'device_options' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'blocklist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'passlist' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'queue' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'frontend' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'experimental' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'availability' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)
22-05-01 14:36:45 WARNING (MainThread) [supervisor.addons.options] Option 'transmit_power' does not exist in the schema for Zigbee2mqtt (45df7312_zigbee2mqtt)

**Comment by Koterak** [comment]
You have to remove config despite of:
- data path
- socat
- mqtt
- serial

Every other options are stored in config file now. It should be already there, so after removing unnecesary parts of config it should start working

**Comment by cisco351** [comment]
Thank you for the reply. Would I do this in the zigbee2mqtt config file in the File editor? Sorry I am not familiar with what to do.

**Comment by Koterak** [comment]
No, you should go to the addons page in home assistant then click on zigbee2mqtt and here you have page called configuration. Of course before editing it copy everything from this page. It can happen that zigbee didn’t copy everything to new config page

**Comment by Scoff123** [comment]
I've had the same problem after updating to 1.25.1. It appears that most of my Z2M config file is now empty, when viewing it in the front end of Home Assistant, and missing the majority of my settings. Checking the configuration yaml file in the data path, it does still have all the previously configured settings in there, but they just aren't pulling through to the front end, which is why all the error messages are showing in the supervisor logs. I've tried uninstalling Z2M and reinstalling but there is no difference.

**Comment by thejeffreystone** [comment]
Yeah, I am having the same issue. 1.15.0-1 works fine. Update to 1.15.1-1, reset add-on config defaults, verify all config options are in config file, restart add-on, it won't start. Just complains about options. Or it does start zigbee2mqtt works but it never connect to mqtt thus making it useless inside of home assistant. I have tried multiple times, and doing the steps in different orders same result.

**Comment by cisco351** [comment]
HI All,
Follow up to the issue I was having. today I updated Home Assistant to the latest version. I then saved my zigbee2mqtt config settings. I then updated and was unable to connect. I then had to go in the config in the file editor and remove the external converter text and leave blank. I then restarted and everything worked. Thanks, Koterak for the help.
