### ISSUE TITLE
stuck at "starting zigbee-herdsman" fail to connect

### ISSUE THREAD

**Issue by lonelysushi** [zigbee2mqtt/hassio-zigbee2mqtt#393]
### Description of the issue

What happened?

The add on in HomeAssistant fails to start with the error message: seems to hang at "starting zigbee-herdsman" for a long time while refreshing the logs

info  2022-10-06 17:01:46: Starting zigbee-herdsman (0.14.62)
error 2022-10-06 17:02:51: Error while starting zigbee-herdsman
error 2022-10-06 17:02:51: Failed to start zigbee
error 2022-10-06 17:02:51: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2022-10-06 17:02:51: Exiting...
error 2022-10-06 17:02:52: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:109:5)

Steps taken to solve the issue:
very very new at this, read that i could try to delete the data/coordinator_backup.json file to try it but not sure how to find it with a Raspberrypi HA set up.  instead went into file editor and deleted the files in config/zigbee2mqtt/

Tried to reflash the SONOFF zigbee 3.0 USB dongle (CC1352P2_CC2652P_launchpad_coordinator_20220219)
not 100% sure how to set panID but i did attempt to change channel in the configuration page

Zigbee2MQTT version
1.28.0-1

Adapter firmware version
20220219

Adapter
Sonoff Zigbee 3.0 USB Dongle Plus (ZBDongle-P)

### Addon version

v1.28.0-1

### Platform

RaspberryPi 4

Home Assistant 2022.10.0
Supervisor 2022.09.1
Operating System 9.0
Frontend 20221005.0 - latest

### Logs of the issue (if applicable)

info  2022-10-06 17:17:46: Logging to console and directory: '/config/zigbee2mqtt/log/2022-10-06.17-17-46' filename: log.txt
info  2022-10-06 17:17:46: Starting Zigbee2MQTT version 1.28.0 (commit #unknown)
info  2022-10-06 17:17:46: Starting zigbee-herdsman (0.14.62)
error 2022-10-06 17:18:52: Error while starting zigbee-herdsman
error 2022-10-06 17:18:52: Failed to start zigbee
error 2022-10-06 17:18:52: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
error 2022-10-06 17:18:52: Exiting...
error 2022-10-06 17:18:52: Error: network commissioning timed out - most likely network with the same panId or extendedPanId already exists nearby
    at ZnpAdapterManager.beginCommissioning (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:347:23)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:92:17)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:109:5)

**Comment by 982020201** [comment]
My situation has been going on for 2 days, how can I fix it

[16:45:16] INFO: Preparing to start...
[16:45:16] INFO: Socat not enabled
[16:45:16] INFO: Zigbee Herdsman debug logging enabled
[16:45:17] INFO: Starting Zigbee2MQTT...
/app/dist/util/externally-loaded.js:2474
                .withPreset(['manual', 'program']).withSensor(['internal', 'external', 'both'], ea.STATE_SET),
                                                   ^
TypeError: exposes.climate(...).withSetpoint(...).withLocalTemperature(...).withLocalTemperatureCalibration(...).withSystemMode(...).withRunningState(...).withPreset(...).withSensor is not a function
    at /app/dist/util/externally-loaded.js:2474:52
    at Script.runInContext (node:vm:141:12)
    at Script.runInNewContext (node:vm:146:17)
    at Object.runInNewContext (node:vm:306:38)
    at loadModuleFromText (/app/lib/util/utils.ts:148:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:155:12)
    at Object.getExternalConvertersDefinitions (/app/lib/util/utils.ts:165:25)
    at getExternalConvertersDefinitions.next (<anonymous>)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:12:20)
    at new Controller (/app/lib/controller.ts:84:58)
