### ISSUE TITLE
Errors in communication after a few minutes after start

### ISSUE THREAD

**Issue by navyhod** [zigbee2mqtt/hassio-zigbee2mqtt#410]
### Description of the issue

After starting the addon all devices are available for a few minutes. But then there are a lot of identical errors in the logs:
I'm using the latest HA and addon versions.

What could be the issue?

Thanks!

### Addon version

1.28.2-1

### Platform

Home Assistant 2022.11.1
Supervisor 2022.10.2
Operating System 9.3

### Logs of the issue (if applicable)

2022-11-07T15:05:51.889Z zigbee-herdsman:adapter:ezsp:erro Request error Error: Failure send setExtendedTimeout:{"type":"Buffer","data":[167,0,1,126,0,144,39,84,254,255,234,53,144,1]}: Error: Failure send setExtendedTimeout:{"type":"Buffer","data":[167,0,1,126,0,144,39,84,254,255,234,53,144,1]}
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:512:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
2022-11-07T15:05:51.890Z zigbee-herdsman:controller:endpoint Read 0x9035eafffe542790/1 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)
2022-11-07T15:13:13.944Z zigbee-herdsman:controller:endpoint Read 0x00158d0006bcf140/1 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2022-11-07T15:13:13.945Z zigbee-herdsman:adapter:ezsp:debg sendZclFrameToEndpointInternal 0x00158d0006bcf140:14728/1 (0,0,1)
2022-11-07T15:13:13.946Z zigbee-herdsman:adapter:ezsp:ezsp ==> setExtendedTimeout: {"remoteEui64":{"_value":{"type":"Buffer","data":[0,21,141,0,6,188,241,64]}},"extendedTimeout":true}
2022-11-07T15:13:13.946Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"setExtendedTimeout","_id_":126,"_isRequest_":true,"remoteEui64":{"_value":{"type":"Buffer","data":[0,21,141,0,6,188,241,64]}},"extendedTimeout":true}
2022-11-07T15:13:13.947Z zigbee-herdsman:adapter:ezsp:uart --> DATA (0,3,0): a800017e0040f1bc06008d150001
2022-11-07T15:13:13.947Z zigbee-herdsman:adapter:ezsp:uart --> [03ea21a92a2a5543e5924aa8bf559329de7e]
2022-11-07T15:13:13.948Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (1)
2022-11-07T15:13:14.948Z zigbee-herdsman:adapter:ezsp:uart -!- break waiting (1)
2022-11-07T15:13:14.949Z zigbee-herdsman:adapter:ezsp:uart Can't send DATA frame (0,3,0): a800017e0040f1bc06008d150001
2022-11-07T15:13:14.949Z zigbee-herdsman:adapter:ezsp:uart ->> DATA (0,3,1): a800017e0040f1bc06008d150001
2022-11-07T15:13:14.949Z zigbee-herdsman:adapter:ezsp:uart --> [0bea21a92a2a5543e5924aa8bf55930e9b7e]
2022-11-07T15:13:14.950Z zigbee-herdsman:adapter:ezsp:uart -?- rewaiting (1)
2022-11-07T15:13:15.950Z zigbee-herdsman:adapter:ezsp:uart -!- break rewaiting (1)
2022-11-07T15:13:15.951Z zigbee-herdsman:adapter:ezsp:uart Can't resend DATA frame (0,3,1): a800017e0040f1bc06008d150001
2022-11-07T15:13:15.953Z zigbee-herdsman:adapter:ezsp:erro Request error Error: Failure send setExtendedTimeout:{"type":"Buffer","data":[168,0,1,126,0,64,241,188,6,0,141,21,0,1]}: Error: Failure send setExtendedTimeout:{"type":"Buffer","data":[168,0,1,126,0,64,241,188,6,0,141,21,0,1]}
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:512:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
2022-11-07T15:13:15.953Z zigbee-herdsman:controller:endpoint Read 0x00158d0006bcf140/1 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (sendZclFrameToEndpointInternal error)
2022-11-07T15:14:10.859Z zigbee-herdsman:controller:endpoint Read 0x04cf8cdf3c802e93/1 genBasic(["zclVersion"], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":true,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2022-11-07T15:14:10.859Z zigbee-herdsman:adapter:ezsp:debg sendZclFrameToEndpointInternal 0x04cf8cdf3c802e93:13979/1 (0,0,1)
2022-11-07T15:14:10.860Z zigbee-herdsman:adapter:ezsp:ezsp ==> setExtendedTimeout: {"remoteEui64":{"_value":{"type":"Buffer","data":[4,207,140,223,60,128,46,147]}},"extendedTimeout":true}

**Comment by navyhod** [comment]
I'm using Xiaomi Gateway 3 as a ZigBee router.

**Comment by 6773939989** [comment]
Hello
same problem here... Identical logs

**Comment by seb81** [comment]
Hi
some problems
