### ISSUE TITLE
[Bug]: Error: spawn udevadm ENOENT 

### ISSUE THREAD

**Issue by platini76** [zigbee2mqtt/hassio-zigbee2mqtt#420]
### Description of the issue

I dont know if is my bad config or something else...

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://192.168.15.10:1883
  user: USER
  password: PASSWORD
serial:
  serial:
    port: /dev/ttyACM0
    adapter: deconz
```

### Addon version

1.28.2-1 

### Platform

Home Assistant 2022.11.4
Supervisor 2022.11.2
Operating System 9.3
Frontend 20221108.0 - latest

### Logs of the issue (if applicable)

```shell
[03:00:29] INFO: Preparing to start...
[03:00:29] INFO: Socat not enabled
[03:00:31] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2022-11-26 03:00:35: Logging to console and directory: '/config/zigbee2mqtt/log/2022-11-26.03-00-35' filename: log.txt
Zigbee2MQTT:info  2022-11-26 03:00:35: Starting Zigbee2MQTT version 1.28.2 (commit #unknown)
Zigbee2MQTT:info  2022-11-26 03:00:35: Starting zigbee-herdsman (0.14.68)
Zigbee2MQTT:error 2022-11-26 03:00:36: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-11-26 03:00:36: Failed to start zigbee
Zigbee2MQTT:error 2022-11-26 03:00:36: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-11-26 03:00:36: Exiting...
Zigbee2MQTT:error 2022-11-26 03:00:36: Error: spawn udevadm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by Nagrom33** [comment]
I've gotting the same error.

**Setup:**
- Raspberry Pi 3
- Sonoff Zigbee 3.0 USB Dongle Plus

**Home Assistant:**
 Home Assistant 2022.11.4
 Supervisor 2022.11.2
 Operating System 9.3
 Frontend 20221108.0 - latest 

**dmesg:**
`[10674.070197] usb 1-1.5: Product: Sonoff Zigbee 3.0 USB Dongle Plus
[10674.070216] usb 1-1.5: Manufacturer: Silicon Labs
[10674.070234] usb 1-1.5: SerialNumber: 0001
[10674.074400] cp210x 1-1.5:1.0: cp210x converter detected
[10674.079507] usb 1-1.5: cp210x converter now attached to ttyUSB0
`

Config:
`data_path: /config/zigbee2mqtt
socat:Error while starting zigbee-herdsmanError while starting zigbee-herdsman
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: {}
serial:
  port: /dev/ttyUSB0
zigbee_herdsman_debug: true
`

Complete error with debug:
```
[23:42:12] INFO: Preparing to start...
[23:42:15] INFO: Socat not enabled
[23:42:16] INFO: Zigbee Herdsman debug logging enabled
[23:42:23] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2022-11-28 23:42:41: Can't load state from file /config/zigbee2mqtt/state.json (doesn't exist)
Zigbee2MQTT:info  2022-11-28 23:42:41: Logging to console and directory: '/config/zigbee2mqtt/log/2022-11-28.23-42-41' filename: log.txt
Zigbee2MQTT:info  2022-11-28 23:42:41: Starting Zigbee2MQTT version 1.28.2 (commit #unknown)
Zigbee2MQTT:info  2022-11-28 23:42:41: Starting zigbee-herdsman (0.14.68)
Zigbee2MQTT:debug 2022-11-28 23:42:41: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyUSB0"}}'
2022-11-28T22:42:43.239Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2022-11-28T22:42:43.249Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyUSB0"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2022-11-28T22:42:43.254Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/ttyUSB0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2022-11-28T22:42:43.284Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
2022-11-28T22:42:43.293Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2022-11-28T22:42:43.302Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2022-11-28T22:42:43.566Z zigbee-herdsman:adapter:zStack:znp:log Writing CC2530/CC2531 skip bootloader payload
2022-11-28T22:42:43.569Z zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]
2022-11-28T22:42:44.574Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2022-11-28T22:42:44.576Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2022-11-28T22:42:44.829Z zigbee-herdsman:adapter:zStack:znp:log Skip bootloader for CC2652/CC1352
2022-11-28T22:42:45.298Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2022-11-28T22:42:45.304Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2022-11-28T22:42:51.309Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2022-11-28T22:42:51.314Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2022-11-28T22:42:57.326Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2022-11-28T22:42:57.328Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
Zigbee2MQTT:error 2022-11-28 23:43:03: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-11-28 23:43:03: Failed to start zigbee
Zigbee2MQTT:error 2022-11-28 23:43:03: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-11-28 23:43:03: Exiting...
Zigbee2MQTT:error 2022-11-28 23:43:04: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:109:5)
```

**Comment by ndeunk** [comment]
I’ve got the same problem.

Also with the Sonoff Zigbee 3.0 USB Dongle Plus. 
I’ll post more info and logs tomorrow.

**Comment by Launi83** [comment]
Hello everybody,
i've got the same problem.
I'm running HomeAssistant in a VirtualBox VM and zigbee2MQTT doesn't start.
Error: spawn udevadm ENOENT

The Sonoff USB Stick ist installed correctly under the devices Adress port: /dev/ttyUSB0
ZHA is not running.

Home Assistant 2022.12.9
Supervisor 2022-12.1
OS 9.4
Frontend 20221213.1-latest

Zigbee2MQTT version 1.29.0-1

**Comment by ymisonice** [comment]
> i've got the same problem. I'm running HomeAssistant in a VirtualBox VM and zigbee2MQTT doesn't start. Error: spawn udevadm ENOENT
> 
> The Sonoff USB Stick ist installed correctly under the devices Adress port: /dev/ttyUSB0 ZHA is not running.

I have the same issue. The log shows following:

`[18:03:10] INFO: Preparing to start...
[18:03:11] INFO: Socat not enabled
[18:03:11] INFO: Zigbee Herdsman debug logging enabled
[18:03:13] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2023-01-04 18:03:18: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2023-01-04 18:03:18: Logging to console and directory: '/config/zigbee2mqtt/log/2023-01-04.18-03-18' filename: log.txt
Zigbee2MQTT:debug 2023-01-04 18:03:18: Removing old log directory '/config/zigbee2mqtt/log/2023-01-04.17-26-18'
Zigbee2MQTT:info  2023-01-04 18:03:18: Starting Zigbee2MQTT version 1.29.0 (commit #unknown)
Zigbee2MQTT:info  2023-01-04 18:03:18: Starting zigbee-herdsman (0.14.83)
Zigbee2MQTT:debug 2023-01-04 18:03:18: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyUSB0"}}'
2023-01-04T17:03:19.360Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2023-01-04T17:03:19.364Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyUSB0"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2023-01-04T17:03:19.366Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with {"path":"/dev/ttyUSB0","baudRate":115200,"rtscts":false,"autoOpen":false}
2023-01-04T17:03:19.393Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
2023-01-04T17:03:19.399Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2023-01-04T17:03:19.402Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2023-01-04T17:03:19.658Z zigbee-herdsman:adapter:zStack:znp:log Writing CC2530/CC2531 skip bootloader payload
2023-01-04T17:03:19.659Z zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]
2023-01-04T17:03:20.662Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2023-01-04T17:03:20.663Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2023-01-04T17:03:20.914Z zigbee-herdsman:adapter:zStack:znp:log Skip bootloader for CC2652/CC1352
2023-01-04T17:03:21.380Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2023-01-04T17:03:21.380Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2023-01-04T17:03:27.386Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2023-01-04T17:03:27.389Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2023-01-04T17:03:33.395Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2023-01-04T17:03:33.397Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
Zigbee2MQTT:error 2023-01-04 18:03:39: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-01-04 18:03:39: Failed to start zigbee
Zigbee2MQTT:error 2023-01-04 18:03:39: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-01-04 18:03:39: Exiting...
Zigbee2MQTT:error 2023-01-04 18:03:39: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)`

**Comment by Malathan** [comment]
Having the same issue as well.  HomeAssistant in a VirtualBox VM.  Zigbee2MQTT fails with same error as @ymisonice 

Any update on solution?

**Comment by HARJMI** [comment]
Same issue:Zigbee2MQTT:info  2023-01-22 17:32:51: Starting Zigbee2MQTT version 1.29.2 (commit #unknown)
Zigbee2MQTT:info  2023-01-22 17:32:51: Starting zigbee-herdsman (0.14.83-hotfix.0)
Zigbee2MQTT:error 2023-01-22 17:32:52: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-01-22 17:32:52: Failed to start zigbee
Zigbee2MQTT:error 2023-01-22 17:32:52: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-01-22 17:32:52: Exiting...
Zigbee2MQTT:error 2023-01-22 17:32:52: Error: spawn udevadm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by tubit** [comment]
I had the same issue and was able to solve it by adding the config values directly in the `config/zigbee2mqtt/configuration.yaml` file. I don't know why, but the values from the config panel were not set..

HTH,
Dennis

**Comment by HARJMI** [comment]
@tubit Thank You Dennis I have checked and the values in the configuration.Yaml are the same as the UI.

Copy of my config

data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://core-mosquitto:1883
  user: USER
  password: PASSWORD
serial:
  serial: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20221031133346-if00
  adapter: ezsp

**Comment by HARJMI** [comment]
Managed to get it working by adding the port from the hardware list. port: /dev/ttyACM0

**Comment by Piknikilla** [comment]
Hello, 
I've got the same issue on a Raspberry Pi 4b with a ConBee II, running on HAOS.
I removed the DeConz Add-on and the ZHA integration, reinstalled Z2M and Mosquitto. I made sure the ConBee II is plugged on a USB 2.0 port, with an extension cable. 
I modified multiple times the config, directly in the FileEditor but the error keeps happening and apparently blocks the connection to the MQTT server.
I don't know what to do...

Here is the config : 

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://192.68.2.83:1883
  user: USER
  password: PASSWORD
serial:
  adapter: deconz
  port: /dev/ttyACM0
zigbee_herdsman_debug: true

```

**Comment by Launi83** [comment]
> Hello everybody, i've got the same problem. I'm running HomeAssistant in a VirtualBox VM and zigbee2MQTT doesn't start. Error: spawn udevadm ENOENT
> 
> The Sonoff USB Stick ist installed correctly under the devices Adress port: /dev/ttyUSB0 ZHA is not running.
> 
> Home Assistant 2022.12.9 Supervisor 2022-12.1 OS 9.4 Frontend 20221213.1-latest
> 
> Zigbee2MQTT version 1.29.0-1

Interesting discovery: after starting ZHA to test the function of the sonoff stick and then deactivating the ZHA integration, Z2M is working correctly. Don't know why but that's it.

**Comment by Piknikilla** [comment]
Hello I did try this but it didn't change anything. 
ZHA works well with the ConBee II and detects zigbee devices though, so it has nothing to do with the hardware...

**Comment by pdenessen** [comment]
Same problem here. When I finally swapped the Sonoff stick here with a Deconz Conbee it 2 it worked immediately.
I used the latest CC1352P2_CC2652P_launchpad_coordinator_20221226 firmware.

**Comment by parktho** [comment]
As HARJMI suggested, I managed to get it working by adding the port from the hardware list by adding the following to the serial field in the Zigbee2MQTT addon options page: port: /dev/ttyACM0

**Comment by riccardoq76** [comment]
Same problem I  cannot start Zigbee. Any idea?
here my report:

[19:45:22] INFO: Preparing to start...
[19:45:24] INFO: Socat not enabled
[19:45:25] INFO: Zigbee Herdsman debug logging enabled
[19:45:30] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2023-04-29 19:45:46: Can't load state from file /config/zigbee2mqtt/state.json (doesn't exist)
Zigbee2MQTT:info  2023-04-29 19:45:47: Logging to console and directory: '/config/zigbee2mqtt/log/2023-04-29.19-45-46' filename: log.txt
Zigbee2MQTT:debug 2023-04-29 19:45:47: Removing old log directory '/config/zigbee2mqtt/log/2023-04-26.18-25-51'
Zigbee2MQTT:info  2023-04-29 19:45:47: Starting Zigbee2MQTT version 1.30.3 (commit #unknown)
Zigbee2MQTT:info  2023-04-29 19:45:47: Starting zigbee-herdsman (0.14.103)
Zigbee2MQTT:debug 2023-04-29 19:45:47: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"deconz","path":"/dev/ttyAMA0"}}'
2023-04-29T17:45:49.260Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2023-04-29T17:45:49.272Z zigbee-herdsman:deconz:driver Set delay to 0
2023-04-29T17:45:49.278Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyAMA0","adapter":"deconz"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2023-04-29T17:45:49.281Z zigbee-herdsman:deconz:driver Opening with /dev/ttyAMA0
2023-04-29T17:45:49.322Z zigbee-herdsman:deconz:driver Serialport opened
2023-04-29T17:45:49.323Z zigbee-herdsman:controller:log Started with result 'resumed'
2023-04-29T17:45:49.324Z zigbee-herdsman:controller:log Injected database: true, adapter: true
2023-04-29T17:45:49.331Z zigbee-herdsman:controller:database:log Writing database to '/config/zigbee2mqtt/database.db'
2023-04-29T17:45:49.377Z zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 1 paramId: 1
2023-04-29T17:45:52.278Z zigbee-herdsman:deconz:adapter checking coordinator simple descriptor
2023-04-29T17:45:52.288Z zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x0 EP:0 SeqNr. 2 request id: 1
2023-04-29T17:45:59.382Z zigbee-herdsman:deconz:driver Timeout for request - CMD: 0xa seqNr: 1
Zigbee2MQTT:error 2023-04-29 19:45:59: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-04-29 19:45:59: Failed to start zigbee
Zigbee2MQTT:error 2023-04-29 19:45:59: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-04-29 19:45:59: Exiting...
Zigbee2MQTT:error 2023-04-29 19:45:59: undefined
2023-04-29T17:45:59.429Z zigbee-herdsman:deconz:driver send read device state from queue. seqNr: 3

**Comment by Piknikilla** [comment]
> Same problem here. When I finally swapped the Sonoff stick here with a Deconz Conbee it 2 it worked immediately. I used the latest CC1352P2_CC2652P_launchpad_coordinator_20221226 firmware.

I made the opposite (switching the Conbee with a Sonoff stick) and I still get the very same error... It's so frustrating...

**Comment by davix10** [comment]
Were you able to solve the problem?

**Comment by marcjjohn** [comment]
FWIW I copied these settings from a old config when I was having this issue. Added them all so know idea what worked:
serial:
  port: /dev/ttyACM0
  adapter: ezsp
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false

**Comment by baa73** [comment]
Thanks for the input. after 2 weeks of searching the issue, finally. 
I had the same problem config file was only one line => something with Homeassistant true. After erasing this line and copy the config from the UI into the config file, the add-on run :-D

**Comment by nielssiebert** [comment]
> > Hello everybody, i've got the same problem. I'm running HomeAssistant in a VirtualBox VM and zigbee2MQTT doesn't start. Error: spawn udevadm ENOENT
> > The Sonoff USB Stick ist installed correctly under the devices Adress port: /dev/ttyUSB0 ZHA is not running.
> > Home Assistant 2022.12.9 Supervisor 2022-12.1 OS 9.4 Frontend 20221213.1-latest
> > Zigbee2MQTT version 1.29.0-1
> 
> Interesting discovery: after starting ZHA to test the function of the sonoff stick and then deactivating the ZHA integration, Z2M is working correctly. Don't know why but that's it.

This did the trick for me two, thanks for pointing it out!

**Comment by Mincka** [comment]
> I had the same issue and was able to solve it by adding the config values directly in the `config/zigbee2mqtt/configuration.yaml` file. I don't know why, but the values from the config panel were not set..
> 
> HTH, Dennis

Thank your for that! 🙏 My `configuration.yaml` had still the reference to my previous dongle.
I deleted the file and starter the addon again.

**Comment by baa73** [comment]
In the meanwile I move from Z2M to ZHA. 
HA is so faster and stable. Since the move no more hangoffs.

**Comment by Bluemeus** [comment]
I got stucked on the same issue, tried out every solution above and on the docs (https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html). 

In my case ZHA worked well out-of-the-box, but Z2M does not. So i checked the ZHA config (port, adapter, type, baud rate, ...) and could resolve it by adding the following lines in the Z2M config in the **serial part**:

```
port: /dev/ttyACM0
adapter: ezsp
baudrate: 115200
```

Hope this helps...

**Comment by ebbandflow4614** [comment]
So when you first get the Sonoff Zigbee 3.0 USB Dongle Plus and it shows up as Discovered in HA, do you click **IGNORE** or just leave it as "Discovered" and move on to setting up in Z2M?

**Comment by xelemorf** [comment]
I've bumped into the same issue and I already had the device path in Z2M config (/homeassistant/zigbee2mqtt/configuration.yaml) but apparently had to change it slightly.

This was the orig format:
  port: >-
    /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_REDACTED-if00-port0

Changed to this and it works now:
  port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_REDACTED-if00-port0
