### ISSUE TITLE
Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/DeviceID

### ISSUE THREAD

**Issue by Sashik259** [zigbee2mqtt/hassio-zigbee2mqtt#429]
### Description of the issue

```
Logger: homeassistant.util.logging
Source: util/logging.py:168 
First occurred: 2 December 2022, 22:21:32 (1418 occurrences) 
Last logged: 20:30:16

Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Kitchen LED': '{"brightness":190,"color_mode":"color_temp","color_temp":346,"color_temp_startup":17476,"last_seen":"2022-12-03T17:22:49.976Z","linkquality":72,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":"10276802","state":"idle"},"update_available":false}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received if "installed_version" in json_payload: TypeError: argument of type 'int' is not iterable
Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Kitchen LED': '{"brightness":190,"color_mode":"color_temp","color_temp":346,"color_temp_startup":17476,"last_seen":"2022-12-03T17:23:47.271Z","linkquality":76,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":"10276802","state":"idle"},"update_available":false}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received if "installed_version" in json_payload: TypeError: argument of type 'int' is not iterable
Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Kitchen LED': '{"brightness":190,"color_mode":"color_temp","color_temp":346,"color_temp_startup":17476,"last_seen":"2022-12-03T17:23:47.271Z","linkquality":76,"power_on_behavior":"previous","state":"ON","update":{"installed_version":"10276802","state":"idle"},"update_available":false}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received if "installed_version" in json_payload: TypeError: argument of type 'int' is not iterable
Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Kitchen LED': '{"brightness":190,"color_mode":"color_temp","color_temp":346,"color_temp_startup":17476,"last_seen":"2022-12-03T17:30:16.364Z","linkquality":76,"power_on_behavior":"previous","state":"ON","update":{"installed_version":"10276802","state":"idle"},"update_available":false}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received if "installed_version" in json_payload: TypeError: argument of type 'int' is not iterable
Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Kitchen LED': '{"brightness":190,"color_mode":"color_temp","color_temp":346,"color_temp_startup":17476,"last_seen":"2022-12-03T17:30:16.364Z","linkquality":76,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":"10276802","state":"idle"},"update_available":false}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received if "installed_version" in json_payload: TypeError: argument of type 'int' is not iterable

```
```

2022-12-02 22:21:32.527 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Kitchen LED': '{"brightness":190,"color_mode":"color_temp","color_temp":346,"color_temp_startup":17476,"last_seen":"2022-12-02T19:19:19.014Z","linkquality":76,"power_on_behavior":"previous","state":"ON","update":{"installed_version":"10276802","state":"idle"},"update_available":false}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
msg_callback(msg)
File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
if "installed_version" in json_payload:
TypeError: argument of type 'int' is not iterable
2022-12-02 22:21:32.567 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Bedroom LED': '{"brightness":14,"color_mode":"color_temp","color_temp":495,"color_temp_startup":17476,"last_seen":"2022-12-02T19:20:19.460Z","linkquality":32,"power_on_behavior":"previous","state":"ON","update":{"installed_version":"10276802","state":"idle"},"update_available":false}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
msg_callback(msg)
File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
if "installed_version" in json_payload:
TypeError: argument of type 'int' is not iterable
2022-12-02 22:21:32.902 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Kitchen LED': '{"brightness":190,"color_mode":"color_temp","color_temp":346,"color_temp_startup":17476,"last_seen":"2022-12-02T19:21:32.893Z","linkquality":76,"power_on_behavior":"previous","state":"ON","update":{"installed_version":"10276802","state":"idle"},"update_available":false}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
msg_callback(msg)
File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
if "installed_version" in json_payload:
TypeError: argument of type 'int' is not iterable
2022-12-02 22:21:32.917 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Kitchen LED': '{"brightness":190,"color_mode":"color_temp","color_temp":346,"color_temp_startup":17476,"last_seen":"2022-12-02T19:21:32.893Z","linkquality":76,"power_on_behavior":"previous","state":"ON","update":{"installed_version":"10276802","state":"idle"},"update_available":false}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
msg_callback(msg)
File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
if "installed_version" in json_payload:
TypeError: argument of type 'int' is not iterable
2022-12-02 22:22:57.053 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Kitchen LED': '{"brightness":190,"color_mode":"color_temp","color_temp":346,"color_temp_startup":17476,"last_seen":"2022-12-02T19:22:57.034Z","linkquality":76,"power_on_behavior":"previous","state":"ON","update":{"installed_version":"10276802","state":"idle"},"update_available":false}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
msg_callback(msg)
File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
if "installed_version" in json_payload:
TypeError: argument of type 'int' is not iterable
2022-12-02 22:22:57.083 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Kitchen LED': '{"brightness":190,"color_mode":"color_temp","color_temp":346,"color_temp_startup":17476,"last_seen":"2022-12-02T19:22:57.034Z","linkquality":76,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":"10276802","state":"idle"},"update_available":false}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
msg_callback(msg)
File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
if "installed_version" in json_payload:
TypeError: argument of type 'int' is not iterable
2022-12-02 22:22:57.130 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Bedroom LED': '{"brightness":14,"color_mode":"color_temp","color_temp":495,"color_temp_startup":17476,"last_seen":"2022-12-02T19:22:57.115Z","linkquality":58,"power_on_behavior":"previous","state":"ON","update":{"installed_version":"10276802","state":"idle"},"update_available":false}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
msg_callback(msg)
File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
if "installed_version" in json_payload:
TypeError: argument of type 'int' is not iterable
2022-12-02 22:22:57.152 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Bedroom LED': '{"brightness":14,"color_mode":"color_temp","color_temp":495,"color_temp_startup":17476,"last_seen":"2022-12-02T19:22:57.115Z","linkquality":58,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":"10276802","state":"idle"},"update_available":false}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
msg_callback(msg)
File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
if "installed_version" in json_payload:
TypeError: argument of type 'int' is not iterable
2022-12-02 22:23:29.678 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Kitchen LED': '{"brightness":190,"color_mode":"color_temp","color_temp":346,"color_temp_startup":17476,"last_seen":"2022-12-02T19:23:29.664Z","linkquality":80,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":"10276802","state":"idle"},"update_available":false}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
msg_callback(msg)
File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
if "installed_version" in json_payload:
TypeError: argument of type 'int' is not iterable
2022-12-02 22:23:29.708 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Kitchen LED': '{"brightness":190,"color_mode":"color_temp","color_temp":346,"color_temp_startup":17476,"last_seen":"2022-12-02T19:23:29.664Z","linkquality":80,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":"10276802","state":"idle"},"update_available":false}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
msg_callback(msg)
File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
if "installed_version" in json_payload:
TypeError: argument of type 'int' is not iterable
2022-12-02 22:27:32.600 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Kitchen LED': '{"brightness":190,"color_mode":"color_temp","color_temp":346,"color_temp_startup":17476,"last_seen":"2022-12-02T19:27:32.589Z","linkquality":80,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":"10276802","state":"idle"},"update_available":false}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
msg_callback(msg)
File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
if "installed_version" in json_payload:
TypeError: argument of type 'int' is not iterable
```

### Addon version

1.28.4-1

### Platform

Home Assistant 2022.11.5
Supervisor 2022.11.2
Frontend 20221108.0 - latest

**Comment by PiotrSulowski** [comment]
It is a problem with Gledopto GL-C-008P

After changing the name of device it showed more info in logs:
```
2022-12-04 18:32:17.730 WARNING (MainThread) [homeassistant.components.mqtt.mixins] Erroneous JSON:
2022-12-04 18:32:17.734 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.power_on_behavior }}'
2022-12-04 18:32:17.739 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: , template: {{ value_json.power_on_behavior }})
2022-12-04 18:32:17.743 ERROR (MainThread) [homeassistant.components.mqtt.select] Invalid option for select.led_wanna_power_on_behavior: '' (valid options: ['off', 'on', 'toggle', 'previous'])
2022-12-04 18:32:17.748 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: , template: {{ value_json['update']['installed_version'] }})
2022-12-04 18:32:17.754 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: , template: {% if value_json['update']['state'] == "available" %}{{ 'newer' }}{% else %}{{ value_json['update']['installed_version'] }}{% endif %})
2022-12-04 18:32:17.778 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.state }}'
2022-12-04 18:32:17.782 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: , template: {{ value_json.state }})
2022-12-04 18:32:17.790 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.state }}'
2022-12-04 18:32:17.793 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: , template: {{ value_json.state }})
2022-12-04 18:32:17.797 ERROR (MainThread) [homeassistant.helpers.template] Template variable error: 'value_json' is undefined when rendering '{{ value_json.state }}'
2022-12-04 18:32:17.800 ERROR (MainThread) [homeassistant.helpers.template] Error parsing value: 'value_json' is undefined (value: , template: {{ value_json.state }})
2022-12-04 18:36:20.525 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/LEDWanna': '{"brightness":254,"color":{"h":40,"hue":40,"s":51,"saturation":51,"x":0.3836,"y":0.3787},"color_mode":"color_temp","color_temp":254,"color_temp_startup":254,"last_seen":"2022-12-04T18:36:20+01:00","linkquality":255,"power_on_behavior":"off","state":"ON","update":{"installed_version":"10976802","state":"idle"},"update_available":false}'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
msg_callback(msg)
File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
if "installed_version" in json_payload:
TypeError: argument of type 'int' is not iterable
```




some state dump:
```
{
    "brightness": 254,
    "color": {
        "h": 40,
        "hue": 40,
        "s": 51,
        "saturation": 51,
        "x": 0.3836,
        "y": 0.3787
    },
    "color_mode": "color_temp",
    "color_temp": 254,
    "color_temp_startup": 254,
    "last_seen": "2022-12-04T18:31:21+01:00",
    "linkquality": 255,
    "power_on_behavior": "off",
    "state": "ON",
    "update": {
        "installed_version": "10976802",
        "state": "idle"
    },
    "update_available": false
}
```

**Comment by Gorouk** [comment]
Same for me also with Gledopto GL-C-008P

**Comment by Sashik259** [comment]
> with Gledopto GL-C-008P

I have Gledopto GL-C-006P
I guess the problem is not with Gledopto, but with Zeegbee2MQTT.
I noticed they added definitely important and necessary option called "power_on_behavior".
And a new bug (error) has appeared too.

**Comment by AbeltjeNL** [comment]
'''

Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Toilet': '{"brightness":102,"last_seen":"2022-12-05T18:55:50+01:00","linkquality":131,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":"10476802","state":"idle"},"update_available":false}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received if "installed_version" in json_payload: TypeError: argument of type 'int' is not iterable
'''

**Comment by AbeltjeNL** [comment]
```
Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Toilet': '{"brightness":102,"last_seen":"2022-12-05T18:55:50+01:00","linkquality":131,"power_on_behavior":"previous","state":"OFF","update":{"installed_version":"10476802","state":"idle"},"update_available":false}' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received if "installed_version" in json_payload: TypeError: argument of type 'int' is not iterable
```

**Comment by IronButterfly** [comment]
The same issue with Eurotronic SPZB0001 TRV

Zigbee2MQTT version: 1.28.4
Coordinator type: zStack3x0
Coordinator revision: 20220103

**Comment by drjjr2** [comment]
I am having the same issue with two **INNR SP24s**. I posted this on the zigbee2mqtt but they said it was an HA problem.
```
2022-12-05 02:49:44.502 ERROR (MainThread) [homeassistant.util.logging] Exception in handle_state_message_received when handling msg on 'zigbee2mqtt/Upstairs Christmas Lights': '{"last_seen":"2022-12-05T02:49:44-06:00","linkquality":120,"state":"OFF","update":{"installed_version":"2.1","state":"available"},"update_available":null}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 44, in wrapper
    msg_callback(msg)
  File "/usr/src/homeassistant/homeassistant/components/mqtt/update.py", line 191, in handle_state_message_received
    if "installed_version" in json_payload:
TypeError: argument of type 'float' is not iterable
```

**Comment by drjjr2** [comment]
My money's on the version being presented as a string when it should not be. For this device it is sw_version: '2.1' For my Philips light bulbs that value is not in quotes.
Update also shows as "unknown" in the MQTT integration.

```
availability:
  - topic: zigbee2mqtt/bridge/state
    value_template: '{{ value_json.state }}'
command_topic: zigbee2mqtt/bridge/request/device/ota_update/update
device:
  identifiers:
![Clipboard01](https://user-images.githubusercontent.com/69729977/205943433-80471a4a-c0fe-4f06-86ff-b86c745f0227.jpg)

    - zigbee2mqtt_0x04cd15fffe682d6f
  manufacturer: Innr
  model: Smart plug (SP 224)
  name: Salt Lamp
  sw_version: '2.1'
device_class: firmware
entity_picture: https://github.com/Koenkk/zigbee2mqtt/raw/master/images/logo.png
latest_version_template: >-
  {% if value_json['update']['state'] == "available" %}{{ 'newer' }}{% else %}{{
  value_json['update']['installed_version'] }}{% endif %}
latest_version_topic: zigbee2mqtt/Salt Lamp
name: Salt Lamp
payload_install: '{"id": "0x04cd15fffe682d6f"}'
state_topic: zigbee2mqtt/Salt Lamp
unique_id: 0x04cd15fffe682d6f_update_zigbee2mqtt
value_template: '{{ value_json[''update''][''installed_version''] }}'
platform: mqtt
```

**Comment by drjjr2** [comment]
Looks like they have already been working on a fix:
[](https://github.com/Koenkk/zigbee2mqtt/issues/15290)

**Comment by Koenkk** [comment]
This is a HA issue and will be fixed in 2022.12 (https://github.com/home-assistant/core/pull/83218)
