### ISSUE TITLE
Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)

### ISSUE THREAD

**Issue by bezrukovp** [zigbee2mqtt/hassio-zigbee2mqtt#430]
### Description of the issue

Installing zigbee2mqtt as home helper addon gives error Error: SRSP - SYS - ping after 6000ms
It looks like the reason is that /run/udev is not mounted in the container.

It works if you separately install koenkk/zigbee2mqtt + addon zigbee2mqtt proxy.

I want to understand how the default addon zigbee2mqtt works for others. Perhaps it needs to be installed in some other way.

### Addon version

1.28.4-1

### Platform

Core: 2022.11.5
Supervisor: 2022.11.2
Operating system: Linux raspberrypi 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux

**Comment by makanimike** [comment]
I seem to be experiencing this after a fresh install of Home Assistant and recovery of my old setup. However, I cannot work around it by installing the proxy.

**Comment by tnesser** [comment]
Just got the SkyConnect device. Get same error message when I try to start zigbee2mqtt:

Zigbee2MQTT:error 2022-12-11 11:52:17: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2022-12-11 11:52:17: Failed to start zigbee
Zigbee2MQTT:error 2022-12-11 11:52:17: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2022-12-11 11:52:17: Exiting...
Zigbee2MQTT:error 2022-12-11 11:52:17: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by lillson** [comment]
> Just got the SkyConnect device. Get same error message when I try to start zigbee2mqtt:
> 
> Zigbee2MQTT:error 2022-12-11 11:52:17: Error while starting zigbee-herdsman Zigbee2MQTT:error 2022-12-11 11:52:17: Failed to start zigbee Zigbee2MQTT:error 2022-12-11 11:52:17: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions Zigbee2MQTT:error 2022-12-11 11:52:17: Exiting... Zigbee2MQTT:error 2022-12-11 11:52:17: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms) at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27) at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29) at Zigbee.start (/app/lib/zigbee.ts:58:27) at Controller.start (/app/lib/controller.ts:101:27) at start (/app/index.js:107:5)

SkyConnect worked with ZHA, but after removing ZHA and trying to use the SkyConnect with Zigbee2MQTT I get the same error.

**Comment by mvgent** [comment]
Havind the same problem ,clean install on a raspberry pi with HA. zigbee stick that worked before. whole hardware setup belongs to a friend...weird...

**Comment by MeisterGig** [comment]
I have the same problem. I am using a Sonoff Zigbee Stick. I disabled and deleted ZHA. I have tried through the terminal addon if the Serial connection works (test -w /dev/ttyUSB0 && echo success || echo failure) and it does. I don't really know what else i can try

**Comment by DieterKoblenz** [comment]
Same here with the ZBDongle-E. I installed z2m edge add-on, but it won't work.

Nor can I add ezsp adapter to the config file...

**Comment by Koenkk** [comment]
If you get the `(Error: SRSP - SYS - ping after 6000ms)` error it means the zstack adapter code is used. For ezsp (=ZBDongle-E, SkyConnect) you can force the adapter type by adding the following to your `configuration.yaml`

```yaml
serial:
  port: /dev/THEPORT # <- change this accordingly
  adapter: ezsp
```

**Comment by zigajamnik** [comment]
Hi,
my father also got this error (Error: SRSP - SYS - ping after 6000ms). Several months it was working very well with SONOFF Dongle 3.0 and zigbee2mqtt Edge.  Today, suddenly no entities avaliable in HA. Checked logs and got this error. Tried rebooting, rebooting HA. Reinstalling z2mEdge. Tried also with normal version of Z2m... Nothing works :/ 
Nothing really changed with integrations or any other settings... it suddenly stopped working. 
Also, no ZHA integration is installed ( some ppl say that this might be causing it ). 

please help?

**Comment by lillson** [comment]
> If you get the `(Error: SRSP - SYS - ping after 6000ms)` error it means the zstack adapter code is used. For ezsp (=ZBDongle-E, SkyConnect) you can force the adapter type by adding the following to your `configuration.yaml`
> 
> ```yaml
> serial:
>   port: /dev/THEPORT # <- change this accordingly
>   adapter: ezsp
> ```

That did the trick :)

**Comment by makanimike** [comment]
it got rid of the SRSP SYS ping error. Now I only have the 502: Bad Gateway left.... 

Is the Configuration section of the add-on meant to coexist with a configuration.yaml, or override it?

**Comment by MeisterGig** [comment]
> it got rid of the SRSP SYS ping error. Now I only have the 502: Bad Gateway left....
> 
> Is the Configuration section of the add-on meant to coexist with a configuration.yaml, or override it? I've been searching the web for days now trying different suggested solutions.

I can confirm that. The logs unfortionatly dind't give more insight into the error 502
```
[00:56:49] INFO: Preparing to start...
[00:56:49] INFO: Socat not enabled
[00:56:50] INFO: Zigbee Herdsman debug logging enabled
[00:56:51] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2022-12-20 00:56:56: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2022-12-20 00:56:56: Logging to console and directory: '/config/zigbee2mqtt/log/2022-12-20.00-56-56' filename: log.txt
Zigbee2MQTT:debug 2022-12-20 00:56:56: Removing old log directory '/config/zigbee2mqtt/log/2022-12-14.20-08-33'
Zigbee2MQTT:info  2022-12-20 00:56:56: Starting Zigbee2MQTT version 1.28.4 (commit #unknown)
Zigbee2MQTT:info  2022-12-20 00:56:56: Starting zigbee-herdsman (0.14.76)
Zigbee2MQTT:debug 2022-12-20 00:56:56: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"/dev/ttyUSB0"}}'
2022-12-19T23:56:56.802Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2022-12-19T23:56:56.806Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[secret],"panID":6754,"extendedPanID":[secret],"channelList":[11]},"serialPort":{"path":"/dev/ttyUSB0","adapter":"ezsp"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2022-12-19T23:56:56.810Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with /dev/ttyUSB0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2022-12-19T23:56:56.830Z zigbee-herdsman:adapter:ezsp:uart Serialport opened
2022-12-19T23:56:56.830Z zigbee-herdsman:adapter:ezsp:uart Uart reseting
2022-12-19T23:56:56.831Z zigbee-herdsman:adapter:ezsp:uart --> Write reset
2022-12-19T23:56:56.833Z zigbee-herdsman:adapter:ezsp:uart --> [1ac038bc7e]
```
I am using a Sonoff ZB  Stick and the following config in HA:
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: {}
serial:
  port: /dev/ttyUSB0
  adapter: ezsp
zigbee_herdsman_debug: true
```

**Comment by evan-annix** [comment]
> If you get the `(Error: SRSP - SYS - ping after 6000ms)` error it means the zstack adapter code is used. For ezsp (=ZBDongle-E, SkyConnect) you can force the adapter type by adding the following to your `configuration.yaml`
> 
> ```yaml
> serial:
>   port: /dev/THEPORT # <- change this accordingly
>   adapter: ezsp
> ```

9 Hours. I have been trying to fix this for *9 Straight Hours* and this is what fixed it for me. 

For reference, I am running HAS OS on an Xpenology DS920+ HackiNAS, and spent at least 4 of those hours attempting to get the CH-341 drivers from archive.org running via rhythmic face smashing into SSH, hoping I could pass through my EZSP stick to Docker/Portainer, which was a complete crapshoot. 

This is my first foray in to zigbee2mqtt after reading so many threads about it's superiority to ZHA - which, for the record, worked automatically with my Zigbee USB. It's nearly 6:30am and I haven't slept - I refused to be defeated by a £9 Aliexpress dongle, and you sir have saved me from the worst of it. I own one Zigbee device. Why on earth am I doing this to myself. 

To be clear to anyone else as inexperienced / sleep deprived as I am, @Koenkk means that this should go in the 'configuration.yaml' located in the '/zigbee2mqtt' subfolder, not your main Home Assistant config. Computers were a mistake.

**Comment by kkoenen** [comment]
Adding `adapter: ezsp` to the config (under `serial:` ) fixed it for me.

**Comment by zeng5200** [comment]
when i add "adapter: ezsp" then save it will print error as follow

**Comment by ollibert** [comment]
> Failed to save add-on configuration, does not match regular expression ^zstack|deconz|zigate$. Got {'data_path': '/config/zigbee2mqtt', 'external_converters': [], 'devices': 'devices.yaml', 'groups': 'groups.yaml', 'homeassistant': True, 'permit_join': False, 'mqtt': {'base_topic': 'zigbee2mqtt'}, 'serial': {'port': '/dev/ttyUSB1', 'adapter': 'ezsp'}, 'advanced': {'log_level': 'warn', 'pan_id': 6754, 'channel': 11, 'network_key': [1, 3, 5, 7, 9, 11, 13, 15, 0, 2, 4, 6, 8, 10, 12, 13], 'availability_blocklist': [], 'availability_passlist': []}, 'device_options': {}, 'blocklist': [], 'passli...

I have the same problem. I can't add, that z2m should use ezsp.

**Comment by mwood77** [comment]
> ```yaml
> serial:
>   port: /dev/THEPORT # <- change this accordingly
>   adapter: ezsp
> ```

I had a different issue where my Sonoff ZigBee 3.0 dongle wasn't available, but I could see it in HA. The above fixed it.

**Comment by codyc1515** [comment]
Why isn't this automatic?

**Comment by dcarpio01** [comment]
My god. I just found this and it's the answer to my SLZB-06 mqtt startup issues. Why is this not in the zigbee2mqtt quick start guide?

**Comment by LindsayReid** [comment]
This solved my problem using Skyconnect on a Proxmox installation after setting the USB interface in Proxmod hardware USBdevice itself:

Use USB Port
SkyConnect v1.0 (1-4)



In HA Zigbee2MQTT config:

mqtt
base_topic: zigbee2mqtt

serial
port: /dev/ttyUSB0
adapter: ezsp

**Comment by maxant** [comment]
for me, this worked:

serial:
  port: /dev/ttyUSB0
  adapter: deconz
  baudrate: 115200

for a conbee 3

**Comment by Bagunda** [comment]
Everything worked for a long time and reliably.
But today I woke up... And it doesn't work...

I tried to add:
```
serial:
  port: tcp://10.2.90.5:6638
  adapter: ezsp
```
Didn't help.
Tried:
```
serial:
  port: tcp://10.2.90.5:6638
  adapter: ember
```
Didn't help.

```
[07:38:43] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-10-04 07:38:48] info: 	z2m: Logging to console, file (filename: log.log)
[2024-10-04 07:38:48] info: 	z2m: Starting Zigbee2MQTT version 1.39.0 (commit #unknown)
[2024-10-04 07:38:48] info: 	z2m: Starting zigbee-herdsman (0.50.1)
[2024-10-04 07:38:48] info: 	zh:zstack:znp: Opening TCP socket with 10.2.90.5:6638
[2024-10-04 07:38:48] info: 	zh:zstack:znp: Socket connected
[2024-10-04 07:38:48] info: 	zh:zstack:znp: Socket ready
[2024-10-04 07:38:48] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-10-04 07:38:49] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-10-04 07:39:07] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-04 07:39:07] error: 	z2m: Failed to start zigbee
[2024-10-04 07:39:07] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-04 07:39:07] error: 	z2m: Exiting...
[2024-10-04 07:39:07] error: 	z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:101:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:129:29)
    at Zigbee.start (/app/lib/zigbee.ts:63:27)
    at Controller.start (/app/lib/controller.ts:139:27)
    at start (/app/index.js:154:5)
[07:41:28] INFO: Preparing to start...
[07:41:28] INFO: Socat not enabled
[07:41:29] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-10-04 07:41:33] info: 	z2m: Logging to console, file (filename: log.log)
[2024-10-04 07:41:33] info: 	z2m: Starting Zigbee2MQTT version 1.39.0 (commit #unknown)
[2024-10-04 07:41:33] info: 	z2m: Starting zigbee-herdsman (0.50.1)
[2024-10-04 07:41:33] warning: 	zh:ezsp: Deprecated driver 'ezsp' currently in use, 'ember' will become the officially supported EmberZNet driver in next release. If using Zigbee2MQTT see https://github.com/Koenkk/zigbee2mqtt/discussions/21462
[2024-10-04 07:41:44] error: 	zh:ezsp:uart: --> Error: Error: {"sequence":-1} after 10000ms
Error: Failure to connect
    at SerialDriver.resetForReconnect (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:347:19)
    at SerialDriver.emit (node:events:517:28)
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:348:22
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Socket.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:154:17)
[07:44:53] INFO: Preparing to start...
[07:44:54] INFO: Socat not enabled
[07:44:55] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-10-04 07:44:59] info: 	z2m: Logging to console, file (filename: log.log)
[2024-10-04 07:44:59] info: 	z2m: Starting Zigbee2MQTT version 1.39.0 (commit #unknown)
[2024-10-04 07:44:59] info: 	z2m: Starting zigbee-herdsman (0.50.1)
[2024-10-04 07:44:59] info: 	zh:ember: Using default stack config.
[2024-10-04 07:44:59] info: 	zh:ember: ======== Ember Adapter Starting ========
[2024-10-04 07:44:59] info: 	zh:ember:ezsp: ======== EZSP starting ========
[2024-10-04 07:44:59] info: 	zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-10-04 07:44:59] info: 	zh:ember:uart:ash: Socket ready
[2024-10-04 07:44:59] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-10-04 07:45:01] info: 	zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-10-04 07:45:01] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-10-04 07:45:04] info: 	zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-10-04 07:45:04] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-10-04 07:45:07] info: 	zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-10-04 07:45:07] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-10-04 07:45:09] info: 	zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-10-04 07:45:09] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-10-04 07:45:12] error: 	z2m: Error while starting zigbee-herdsman
[2024-10-04 07:45:12] error: 	z2m: Failed to start zigbee
[2024-10-04 07:45:12] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-10-04 07:45:12] error: 	z2m: Exiting...
[2024-10-04 07:45:12] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:889:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:2722:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:129:29)
    at Zigbee.start (/app/lib/zigbee.ts:63:27)
    at Controller.start (/app/lib/controller.ts:139:27)
    at start (/app/index.js:154:5)
```

**Comment by MR-Ostrich13** [comment]
i have exactly the same issue.

**Comment by grunes** [comment]
I have exact the same issue here, switched from ezsp to ember to face exactly the same issue:
```
serial:
  port: tcp://host.lan:12345
  adapter: ember
```
```
Using '/app/data' as data directory
Starting Zigbee2MQTT without watchdog.
[2025-08-14 13:03:03] info: 	z2m: Logging to console, file (filename: log.log)
[2025-08-14 13:03:04] info: 	z2m: Starting Zigbee2MQTT version 2.6.0 (commit #0bdc3fd1f76aaad71f6231e5b38529e2d2b345e9
)
[2025-08-14 13:03:04] info: 	z2m: Starting zigbee-herdsman (5.0.4)
[2025-08-14 13:03:04] info: 	zh:ember: Using default stack config.
[2025-08-14 13:03:04] info: 	zh:ember: ======== Ember Adapter Starting ========
[2025-08-14 13:03:04] info: 	zh:ember:ezsp: ======== EZSP starting ========
[2025-08-14 13:03:04] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2025-08-14 13:03:04] info: 	zh:ember:uart:ash: Socket ready
[2025-08-14 13:03:04] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2025-08-14 13:03:08] info: 	zh:ember:uart:ash: Port closed.
[2025-08-14 13:03:09] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2025-08-14 13:03:09] info: 	zh:ember:uart:ash: Socket ready
[2025-08-14 13:03:09] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2025-08-14 13:03:14] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2025-08-14 13:03:14] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2025-08-14 13:03:19] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2025-08-14 13:03:19] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2025-08-14 13:03:24] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2025-08-14 13:03:24] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2025-08-14 13:03:29] error: 	z2m: Error while starting zigbee-herdsman
[2025-08-14 13:03:29] error: 	z2m: Failed to start zigbee-herdsman
[2025-08-14 13:03:29] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start_crashes-runtime.html for possible solutions
[2025-08-14 13:03:29] error: 	z2m: Exiting...
[2025-08-14 13:03:29] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/.pnpm/zigbee-herdsman@5.0.4/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:665:19)
    at EmberAdapter.start (/app/node_modules/.pnpm/zigbee-herdsman@5.0.4/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1547:24)
    at Controller.start (/app/node_modules/.pnpm/zigbee-herdsman@5.0.4/node_modules/zigbee-herdsman/src/controller/controller.ts:134:29)
    at Zigbee.start (/app/lib/zigbee.ts:67:27)
    at Controller.start (/app/lib/controller.ts:101:13)
    at start (/app/index.js:149:5)
```
Was anybody able to solve this in the meantime?

**Comment by beardyname** [comment]
> Everything worked for a long time and reliably. But today I woke up... And it doesn't work...


> Rebooting stick by the power help me. Rebooting from web - does not help


Just wanted to bump this since i had the exact same problem!
rebooting via web-ui did nothing, pulling the power and restarting my slzb-06 and everything went straight back online!

**Comment by VRohou** [comment]
"Glad" to see I'm not alone. 

Everything was working fine for months with my setup (HA / Zigbee2MQTT / SLZB-06) but now I'm facing regular issue with my SLZB-06 becoming unreachable.

```
[2025-09-10 09:28:52] error: 	z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:114:27)
    at Controller.start (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/controller/controller.ts:133:29)
    at Zigbee.start (/app/lib/zigbee.ts:67:27)
    at Controller.start (/app/lib/controller.ts:101:13)
    at start (/app/index.js:149:5)
```

I Tried to restart from web UI : KO
I tried to update to latest FW : KO
The only thing that worked is to unplug/plug the SLZB-06, which is not very convenient especially when I'm not at home...

**Comment by rhadamantys** [comment]
+1

**Comment by Rhylthus** [comment]
> "Glad" to see I'm not alone.
> 
> Everything was working fine for months with my setup (HA / Zigbee2MQTT / SLZB-06) but now I'm facing regular issue with my SLZB-06 becoming unreachable.
> 
> ```
> [2025-09-10 09:28:52] error: 	z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
>     at ZStackAdapter.start (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:114:27)
>     at Controller.start (/app/node_modules/.pnpm/zigbee-herdsman@6.0.4/node_modules/zigbee-herdsman/src/controller/controller.ts:133:29)
>     at Zigbee.start (/app/lib/zigbee.ts:67:27)
>     at Controller.start (/app/lib/controller.ts:101:13)
>     at start (/app/index.js:149:5)
> ```
> 
> I Tried to restart from web UI : KO I tried to update to latest FW : KO The only thing that worked is to unplug/plug the SLZB-06, which is not very convenient especially when I'm not at home...

Same here !

**Comment by sven-s** [comment]
Same here
