### ISSUE TITLE
Failed to connect to Adapter after Update

### ISSUE THREAD

**Issue by filewalker1** [zigbee2mqtt/hassio-zigbee2mqtt#44]
**Description of problem:**
I updated to the new version 1.18.0-1 and the addon was not able to start: "missing OTA in root". so i added 

```
ota:
  update_check_interval: 10
  disable_automatic_update_check: false
```

to the config. now i get another error log:

```[20:10:04] INFO: MQTT available, fetching server detail ...
[20:10:04] INFO: Previous config file found, checking backup
[20:10:04] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[20:10:04] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:10:05] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.0 start /app
> node index.js
Zigbee2MQTT:info  2021-03-01 20:10:08: Logging to console and directory: '/share/zigbee2mqtt/log/2021-03-01.20-10-07' filename: log.txt
Zigbee2MQTT:info  2021-03-01 20:10:08: Starting Zigbee2MQTT version 1.18.0 (commit #1.18.0)
Zigbee2MQTT:info  2021-03-01 20:10:08: Starting zigbee-herdsman (0.13.72)
Zigbee2MQTT:error 2021-03-01 20:10:28: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-01 20:10:28: Failed to start zigbee
Zigbee2MQTT:error 2021-03-01 20:10:28: Exiting...
Zigbee2MQTT:error 2021-03-01 20:10:28: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: **********
  password: *********
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CB_FD_8A-if00-port0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  ikea_ota_use_test_url: true
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
ota:
  update_check_interval: 10
  disable_automatic_update_check: false

```

**Running platform (details from Suypervisor > System)**
```
Core: core-2021.2.3
Supervisor: supervisor-2021.02.11
Operating System: Debian
```

**Comment by filewalker1** [comment]
Is there a way to downgrade? I need zigbee up and running...

**Comment by PedroQ** [comment]
The same thing happened to me. I am using a CC2652RB stick from slaesh. I would say that this is not an adapter issue because downgrading to version 1.17.1 works fine.
@filewalker1 I downgraded by adding the old danielwelch's repo and installing the addon from there, copying the config.

**Comment by filewalker1** [comment]
@PedroQ  good idea! Thank you

**Comment by McGiverGim** [comment]
For the next time, the easy way to rollback, if you have a snapshot, is to restore the snapshot but select only the addon too restore, nothing more.

**Comment by filewalker1** [comment]
@McGiverGim found this, too. But for the first time i did not snapshot...

**Comment by filewalker1** [comment]
after downgrade it started once but no devices were found. i rebooted HA, now it says: PANID already in use....

**Comment by ciotlosm** [comment]
Can you please try using 1.18.1-1 version and see if that fixes your problem?

**Comment by filewalker1** [comment]
yes, now it is working
