### ISSUE TITLE
CC2652P dont start on 1.18.0-1 release

### ISSUE THREAD

**Issue by maximus3331** [zigbee2mqtt/hassio-zigbee2mqtt#46]
**Description of problem:**

Stick  CC2652P (CC1352P2_CC2652P_coordinator_20210120.zip firmware inside stick) dont start.
This error was detected at first time on zegbee2mqtt edge in release upper than 2021.02.21 (zigbee-herdsman relise upper 0.13.60)

// Make sure your problem is related to the add-on, not to core Zigbee2mqtt functionality, like problems with specific devices - for such issues use https://github.com/Koenkk/zigbee2mqtt/issues

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
zigbee2mqtt@ 1.18.0-1 master

```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: mqtt
  password: mqtt
  version: 5
serial:
  port: /dev/ttyUSB0
advanced:
  log_level: debug
  pan_id: 6754
  channel: 25
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
  last_seen: ISO_8601_local
  homeassistant_legacy_triggers: true
  availability_timeout: 1800
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
zigbee_shepherd_devices: true
zigbee_herdsman_debug: true
ota: {}
```

**Running platform (details from Suypervisor > System)**
```
Pi4b
core-2021.2.3
supervisor-2021.02.11
Home Assistant OS 5.12
```

**Your logs from Home Assistant Supervisor**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[00:03:58] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[00:03:59] INFO: MQTT available, fetching server detail ...
[00:03:59] INFO: Previous config file found, checking backup
[00:03:59] INFO: Creating backup config in '/share/zigbee2mqtt/.configuration.yaml.bk'
[00:03:59] WARNING: No devices.js file found in data path, starting with default devices.js
[00:03:59] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[00:04:00] INFO: Zigbee Herdsman debug logging enabled
[00:04:00] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.0 start /app
> node index.js
Zigbee2MQTT:debug 2021-03-02 00:04:04: Loaded state from file /share/zigbee2mqtt/state.json
Zigbee2MQTT:info  2021-03-02 00:04:04: Logging to console and directory: '/share/zigbee2mqtt/log/2021-03-02.00-04-03' filename: log.txt
Zigbee2MQTT:debug 2021-03-02 00:04:04: Removing old log directory '/share/zigbee2mqtt/log/2021-03-01.23-58-43'
Zigbee2MQTT:info  2021-03-02 00:04:05: Starting Zigbee2MQTT version 1.18.0 (commit #1.18.0)
Zigbee2MQTT:info  2021-03-02 00:04:05: Starting zigbee-herdsman (0.13.72)
Zigbee2MQTT:debug 2021-03-02 00:04:05: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/share/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","databasePath":"/share/zigbee2mqtt/database.db","network":{"channelList":[25],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"/dev/ttyUSB0"}}'
2021-03-01T21:04:05.276Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2021-03-01T21:04:05.280Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[25]},"serialPort":{"path":"/dev/ttyUSB0"},"databasePath":"/share/zigbee2mqtt/database.db","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","backupPath":"/share/zigbee2mqtt/coordinator_backup.json","adapter":{"concurrent":null,"delay":null}}'
2021-03-01T21:04:05.282Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/ttyUSB0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2021-03-01T21:04:05.302Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
2021-03-01T21:04:05.762Z zigbee-herdsman:adapter:zStack:znp:log Writing skip bootloader payload
2021-03-01T21:04:05.763Z zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]
2021-03-01T21:04:06.771Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-03-01T21:04:06.775Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2021-03-01T21:04:12.784Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-03-01T21:04:12.785Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2021-03-01T21:04:18.793Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-03-01T21:04:18.794Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
Zigbee2MQTT:error 2021-03-02 00:04:24: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-02 00:04:24: Failed to start zigbee
Zigbee2MQTT:error 2021-03-02 00:04:24: Exiting...
Zigbee2MQTT:error 2021-03-02 00:04:24: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-01T21_04_24_880Z-debug.log
```

**Comment by mozolin** [comment]
It might be strange, but I've got the same error using 1.17.1 release...

```
Zigbee2MQTT:error 2021-03-01 11:38:27: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-01 11:38:27: Failed to start zigbee
Zigbee2MQTT:error 2021-03-01 11:38:27: Exiting...
Zigbee2MQTT:error 2021-03-01 11:38:27: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.17.1 start: node index.js
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-01T08_38_27_959Z-debug.log
```

**Comment by nanobra1n** [comment]
Same happens to me with CC2652RB (slaesh) FW from 20210120 as well

**Comment by maximus3331** [comment]
> It might be strange, but I've got the same error using 1.17.1 release...
> 
> ```
> Zigbee2MQTT:error 2021-03-01 11:38:27: Error while starting zigbee-herdsman
> Zigbee2MQTT:error 2021-03-01 11:38:27: Failed to start zigbee
> Zigbee2MQTT:error 2021-03-01 11:38:27: Exiting...
> Zigbee2MQTT:error 2021-03-01 11:38:27: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
>     at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
>     at Generator.throw (<anonymous>)
>     at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! zigbee2mqtt@1.17.1 start: node index.js
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the zigbee2mqtt@1.17.1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-03-01T08_38_27_959Z-debug.log
> ```

This error I detected at first time on zegbee2mqtt edge on relise upper than 2021.02.21 (zigbee-herdsman relise upper 0.13-60)

**Comment by bruvv** [comment]
Try unplugging and replugging the stick that would fix it

**Comment by maximus3331** [comment]
> Try unplugging and replugging the stick that would fix it
> 
> Btw duplicated issue:
> #44

It was the first wat i tried. Dont working. pushing Rst buttom on stik - dont work

**Comment by m0wlheld** [comment]
Also exists upstream, see https://github.com/Koenkk/zigbee2mqtt/issues/6517 for more.

**Comment by ciotlosm** [comment]
Can you please test with 1.18.1-1 version?

**Comment by mozolin** [comment]
Mine is working! Thanks!
