### ISSUE TITLE
hersman failure - addon not working

### ISSUE THREAD

**Issue by costasfait** [zigbee2mqtt/hassio-zigbee2mqtt#480]
### Description of the issue

I properly run HA with a rasbee and zigbee2mqtt on a pi with a 16GB sd card. 
Though, as you can tell, I need to upgrade the storage! So i got a new sd card (128GB samsung endurance), installed Hass.io in the card using Balena Etcher and the image https://github.com/home-assistant/operating-system/releases/download/9.5/haos_rpi4-64-9.5.img.xz , and then installed all necessary add-ons (mosquitto broker and zigbee2mqtt) though when I try run the z2m it fails. 

I get this in the log:

`Zigbee2MQTT:info  2023-04-08 21:10:35: Starting Zigbee2MQTT version 1.30.3 (commit #unknown)`
`Zigbee2MQTT:info  2023-04-08 21:10:35: Starting zigbee-herdsman (0.14.103)`
`Zigbee2MQTT:error 2023-04-08 21:10:46: Error while starting zigbee-herdsman`
`Zigbee2MQTT:error 2023-04-08 21:10:46: Failed to start zigbee`

I have in settings:

port: /dev/ttyAMA0
adapter: deconz

and in the ttyAMA0 port i get this:

DEVLINKS: /dev/serial1
DEVNAME: /dev/ttyAMA0
DEVPATH: /devices/platform/soc/fe201000.serial/tty/ttyAMA0
MAJOR: '204'
MINOR: '64'
SUBSYSTEM: tty
TAGS: ':systemd:'
USEC_INITIALIZED: '3067329'

I have tried to use a different sd card (32GB) and the problem is still the same ..... 

i activated herdsman debug and the log is below

this seems to be a known issue for a long time, but no solution yet... see the thread below [https://github.com/Koenkk/zigbee2mqtt/issues/5854](url)
and here
[https://community.home-assistant.io/t/cant-start-zigbee2mqtt-conbee2/428987](url)

I have no idea how to sort out this issue!
I would really appreciate any help.

### Addon version

1.30-3.1

### Platform

Home Assistant 2023.4.1
Supervisor 2023.04.0
Operating System HASSIO 9.5
Frontend 20230406.1 - latest

### Logs of the issue (if applicable)

2023-04-08T19:21:00.805Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2023-04-08T19:21:00.809Z zigbee-herdsman:deconz:driver Set delay to 0
2023-04-08T19:21:00.811Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/ttyAMA0","adapter":"deconz"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2023-04-08T19:21:00.812Z zigbee-herdsman:deconz:driver Opening with /dev/ttyAMA0
2023-04-08T19:21:00.829Z zigbee-herdsman:deconz:driver Serialport opened
2023-04-08T19:21:00.829Z zigbee-herdsman:controller:log Started with result 'resumed'
2023-04-08T19:21:00.830Z zigbee-herdsman:controller:log Injected database: true, adapter: true
2023-04-08T19:21:00.832Z zigbee-herdsman:controller:database:log Writing database to '/config/zigbee2mqtt/database.db'
2023-04-08T19:21:00.852Z zigbee-herdsman:deconz:driver send read parameter request from queue. seqNr: 1 paramId: 1
2023-04-08T19:21:03.812Z zigbee-herdsman:deconz:adapter checking coordinator simple descriptor
2023-04-08T19:21:03.817Z zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0x0 EP:0 SeqNr. 2 request id: 1
2023-04-08T19:21:10.857Z zigbee-herdsman:deconz:driver Timeout for request - CMD: 0xa seqNr: 1

**Comment by costasfait** [comment]
I think I fixed it by disabling bluetooth in the config.txt

dtoverlay=disable-bt

**Comment by patrinif** [comment]
hi I've been getting the failed to start zigbee-herdran issue too. I've been able to change the port to /dev/ttyUSB0, I have mosquito installed well been following the official instruction of zigbee2mqtt here on GitHub for the home assistant add-on
https://github.com/zigbee2mqtt/hassio-zigbee2mqtt#installation
 
here is the log [16:25:58] INFO: Preparing to start...


[16:26:00] INFO: Socat not enabled
[16:26:07] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-04-09 16:26:24: Logging to console and directory: '/config/zigbee2mqtt/log/2023-04-09.16-26-24' filename: log.txt
Zigbee2MQTT:info  2023-04-09 16:26:24: Starting Zigbee2MQTT version 1.30.3 (commit #unknown)
Zigbee2MQTT:info  2023-04-09 16:26:24: Starting zigbee-herdsman (0.14.103)
Zigbee2MQTT:error 2023-04-09 16:26:26: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-04-09 16:26:26: Failed to start zigbee
Zigbee2MQTT:error 2023-04-09 16:26:26: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-04-09 16:26:26: Exiting...
Zigbee2MQTT:error 2023-04-09 16:26:26: Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:146:28)
    at SerialPort._error (/app/node_modules/@serialport/stream/dist/index.js:76:22)
    at /app/node_modules/@serialport/stream/dist/index.js:112:18


here is a screenshot of the config section
<img width="1013" alt="Screenshot 2023-04-09 at 16 37 05" src="https://user-images.githubusercontent.com/31830173/230795289-42fad8ec-dba7-4d98-88e8-49792a1ed47d.png">

**Comment by obot101** [comment]
Hello, ive got this issue as well, and i am using the homeassistant sky connect and the mosquito broker:

**The Log:**

![ha mqtt log](https://user-images.githubusercontent.com/112019174/230889274-d301a20b-e6ae-4735-a735-e62d8d2f5f5d.png)


**And my config:**

![ha mqtt config](https://user-images.githubusercontent.com/112019174/230889372-0c66d19f-72b8-4234-8807-4c3f8cbad698.png)

**Comment by obot101** [comment]
Where is the config.txt file?

**Comment by patrinif** [comment]
goodmorning im looking for it through the terminal because im not home. Im running Hassio so directly not home assistant on top of raspbian. (also been using home assistant for a total of a week ahah) here is the inside of the configuration.yaml. if you need a different file. let me know. thank you so much for the help.

# Loads default set of integrations. Do not remove.
default_config:



# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

**Comment by obot101** [comment]
Sorry when I put the sd card in my mac it sais "_The disk you attached was not readable by this computer_"Is there any other way?

**Comment by costasfait** [comment]
I get that too sometimes. use a USB sd card reader instead of the one in your pc.

**Comment by obot101** [comment]
(USB card reader)

**Comment by patrinif** [comment]
here is my config.txt from the main sd card.

config.txt
[config.txt](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/files/11204683/config.txt)

**Comment by peterj1977** [comment]
I have the same problem, is there a solution?

**Comment by patrinif** [comment]
I just stopped using it unfortunately

**Comment by jmpaiva** [comment]
> I just stopped using it unfortunately

I'm having this issue, sometimes it workls sometinmes is doesn't

What alternative are you using?

**Comment by jmpaiva** [comment]
[14:53:06] INFO: Preparing to start...
[14:53:07] INFO: Socat not enabled
[14:53:10] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-05-26 14:53:17: Logging to console and directory: '/config/zigbee2mqtt/log/2023-05-26.14-53-17' filename: log.txt
Zigbee2MQTT:info  2023-05-26 14:53:17: Starting Zigbee2MQTT version 1.30.4-dev (commit #2d731ba)
Zigbee2MQTT:info  2023-05-26 14:53:17: Starting zigbee-herdsman (0.14.117)
Zigbee2MQTT:error 2023-05-26 14:54:18: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-05-26 14:54:18: Failed to start zigbee
Zigbee2MQTT:error 2023-05-26 14:54:18: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-05-26 14:54:18: Exiting...
Zigbee2MQTT:error 2023-05-26 14:54:18: Error: Connection not initialized
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:551:19)
    at Ezsp.version (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:349:35)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:141:25)
    at EZSPAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:165:16)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by danielrudolf** [comment]
I have the same problem. No solution?

**Comment by jmpaiva** [comment]
> I have the same problem. No solution?

The only solution I found was to migrate to ZHA, no issues so far

**Comment by Martti10** [comment]
Same problem here:

[18:01:26] INFO: Preparing to start...
[18:01:26] INFO: Socat not enabled
[18:01:27] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-07-02 18:01:29: Logging to console and directory: '/config/zigbee2mqtt/log/2023-07-02.18-01-29' filename: log.txt
Zigbee2MQTT:info  2023-07-02 18:01:29: Starting Zigbee2MQTT version 1.32.0 (commit #unknown)
Zigbee2MQTT:info  2023-07-02 18:01:29: Starting zigbee-herdsman (0.16.0)
Zigbee2MQTT:error 2023-07-02 18:01:29: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-07-02 18:01:29: Failed to start zigbee
Zigbee2MQTT:error 2023-07-02 18:01:29: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-07-02 18:01:29: Exiting...
Zigbee2MQTT:error 2023-07-02 18:01:29: Error: spawn udevadm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Br,
Martti

**Comment by Edzakabluk** [comment]
Same problem:

[13:29:29] INFO: Preparing to start...
[13:29:29] INFO: Socat not enabled
[13:29:30] INFO: Zigbee Herdsman debug logging enabled
[13:29:31] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2023-07-06 11:29:35: Can't load state from file /config/zigbee2mqtt/state.json (doesn't exist)
Zigbee2MQTT:info  2023-07-06 11:29:35: Logging to console and directory: '/config/zigbee2mqtt/log/2023-07-06.11-29-35' filename: log.txt
Zigbee2MQTT:debug 2023-07-06 11:29:35: Removing old log directory '/config/zigbee2mqtt/log/2023-07-06.09-26-03'
Zigbee2MQTT:info  2023-07-06 11:29:35: Starting Zigbee2MQTT version 1.32.0 (commit #unknown)
Zigbee2MQTT:info  2023-07-06 11:29:35: Starting zigbee-herdsman (0.16.0)
Zigbee2MQTT:debug 2023-07-06 11:29:35: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"path":"tcp://192.168.1.187:6638"}}'
2023-07-06T10:29:35.446Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2023-07-06T10:29:35.449Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"tcp://192.168.1.187:6638"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2023-07-06T10:29:35.450Z zigbee-herdsman:adapter:zStack:znp:log Opening TCP socket with 192.168.1.187:6638
2023-07-06T10:29:35.462Z zigbee-herdsman:adapter:zStack:znp:log Socket connected
2023-07-06T10:29:35.463Z zigbee-herdsman:adapter:zStack:znp:log Socket ready
2023-07-06T10:29:35.464Z zigbee-herdsman:adapter:zStack:znp:log Writing CC2530/CC2531 skip bootloader payload
2023-07-06T10:29:35.464Z zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]
2023-07-06T10:29:36.467Z zigbee-herdsman:adapter:zStack:znp:log Skip bootloader for CC2652/CC1352
2023-07-06T10:29:36.469Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2023-07-06T10:29:36.471Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2023-07-06T10:29:42.476Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2023-07-06T10:29:42.477Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2023-07-06T10:29:48.478Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2023-07-06T10:29:48.479Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
Zigbee2MQTT:error 2023-07-06 11:29:54: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-07-06 11:29:54: Failed to start zigbee
Zigbee2MQTT:error 2023-07-06 11:29:54: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-07-06 11:29:54: Exiting...
Zigbee2MQTT:error 2023-07-06 11:29:54: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)
