### ISSUE TITLE
Addon fails to start - error while starting zigbee-herdsman, timeout

### ISSUE THREAD

**Issue by gordonthree** [zigbee2mqtt/hassio-zigbee2mqtt#490]
### Description of the issue

Feeling like I'm missing something simple here. I moved over to zigbee2mqtt because the native ZHA integration in home assistant died on me.

In my add-on config, under serial I have
```
port: >-
  /dev/serial/by-id/usb-Texas_Instruments_TI_CC2531_USB_CDC___0X00124B000FEA9C71-if00
```

The tail of the log file is this, herdsman is clearly running and talking with my zigbee network, however, the addon doesn't seem to recognize this fact, and fails with a timeout
```
2023-05-24T02:31:18.738Z zigbee-herdsman:adapter:zStack:znp:SREQ --> UTIL - getDeviceInfo - {}
2023-05-24T02:31:18.738Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,39,0,39]
2023-05-24T02:31:18.742Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,103,0,0,113,156,234,15,0,75,18,0,0,0,7,9,0,54]
2023-05-24T02:31:18.742Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,103,0,0,113,156,234,15,0,75,18,0,0,0,7,9,0,54]
2023-05-24T02:31:18.743Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 3 - 7 - 0 - [0,113,156,234,15,0,75,18,0,0,0,7,9,0] - 54
2023-05-24T02:31:18.743Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- UTIL - getDeviceInfo - {"status":0,"ieeeaddr":"0x00124b000fea9c71","shortaddr":0,"devicetype":7,"devicestate":9,"numassocdevices":0,"assocdeviceslist":[]}
2023-05-24T02:31:18.743Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-05-24T02:31:18.743Z zigbee-herdsman:adapter:zStack:startup adapter is already running in coordinator mode
2023-05-24T02:31:18.744Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - activeEpReq - {"dstaddr":0,"nwkaddrofinterest":0}
2023-05-24T02:31:18.744Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,5,0,0,0,0,36]
2023-05-24T02:31:18.749Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,5,0,97]
2023-05-24T02:31:18.749Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,5,0,97]
2023-05-24T02:31:18.749Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 5 - [0] - 97
2023-05-24T02:31:18.749Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - activeEpReq - {"status":0}
2023-05-24T02:31:18.749Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
Zigbee2MQTT:error 2023-05-23 22:31:28: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-05-23 22:31:28: Failed to start zigbee
Zigbee2MQTT:error 2023-05-23 22:31:28: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-05-23 22:31:28: Exiting...
Zigbee2MQTT:error 2023-05-23 22:31:28: Error: AREQ - ZDO - activeEpRsp after 10000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

### Addon version

1.30.4-1

### Platform

Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

Installed on a quad core HP Prodesk SFF (x86)

### Logs of the issue (if applicable)

2023-05-24T02:31:18.663Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,110,0,30]
2023-05-24T02:31:18.663Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [110,0] - 30
2023-05-24T02:31:18.663Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":110}
2023-05-24T02:31:18.663Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-05-24T02:31:18.664Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":33,"offset":0}
2023-05-24T02:31:18.664Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,33,0,0,0,24]
2023-05-24T02:31:18.682Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,112,97,28,0,110,29,5,2,21,20,21,0,20,0,0,0,1,5,1,143,7,0,2,5,30,0,0,11,0,0,0,0,0,0,0,0,0,0,98,26,8,0,8,0,0,15,15,5,0,1,0,0,0,1,0,0,0,0,113,156,234,15,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,3,0,1,60,10,1,0,0,0,0,0,241]
2023-05-24T02:31:18.682Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,112,97,28,0,110,29,5,2,21,20,21,0,20,0,0,0,1,5,1,143,7,0,2,5,30,0,0,11,0,0,0,0,0,0,0,0,0,0,98,26,8,0,8,0,0,15,15,5,0,1,0,0,0,1,0,0,0,0,113,156,234,15,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,3,0,1,60,10,1,0,0,0,0,0,241]
2023-05-24T02:31:18.682Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 112 - 3 - 1 - 28 - [0,110,29,5,2,21,20,21,0,20,0,0,0,1,5,1,143,7,0,2,5,30,0,0,11,0,0,0,0,0,0,0,0,0,0,98,26,8,0,8,0,0,15,15,5,0,1,0,0,0,1,0,0,0,0,113,156,234,15,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,3,0,1,60,10,1,0,0,0,0,0] - 241
2023-05-24T02:31:18.683Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":0,"len":110,"value":{"type":"Buffer","data":[29,5,2,21,20,21,0,20,0,0,0,1,5,1,143,7,0,2,5,30,0,0,11,0,0,0,0,0,0,0,0,0,0,98,26,8,0,8,0,0,15,15,5,0,1,0,0,0,1,0,0,0,0,113,156,234,15,0,75,18,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,15,3,0,1,60,10,1,0,0,0,0,0]}}
2023-05-24T02:31:18.683Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-05-24T02:31:18.684Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SAPI - readConfiguration - {"configid":98}
2023-05-24T02:31:18.684Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,1,38,4,98,65]
2023-05-24T02:31:18.703Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,19,102,4,0,98,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,0]
2023-05-24T02:31:18.703Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,19,102,4,0,98,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13,0]
2023-05-24T02:31:18.703Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 19 - 3 - 6 - 4 - [0,98,16,1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13] - 0
2023-05-24T02:31:18.703Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SAPI - readConfiguration - {"status":0,"configid":98,"len":16,"value":{"type":"Buffer","data":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13]}}
2023-05-24T02:31:18.703Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-05-24T02:31:18.704Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":58}
2023-05-24T02:31:18.704Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,58,0,10]
2023-05-24T02:31:18.707Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,17,0,97]
2023-05-24T02:31:18.707Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,17,0,97]
2023-05-24T02:31:18.707Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [17,0] - 97
2023-05-24T02:31:18.707Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":17}
2023-05-24T02:31:18.707Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-05-24T02:31:18.708Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":58,"offset":0}
2023-05-24T02:31:18.708Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,58,0,0,0,3]
2023-05-24T02:31:18.711Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,28,2,0,125]
2023-05-24T02:31:18.711Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,28,2,0,125]
2023-05-24T02:31:18.711Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 28 - [2,0] - 125
2023-05-24T02:31:18.711Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}}
2023-05-24T02:31:18.711Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-05-24T02:31:18.712Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":58,"offset":0}
2023-05-24T02:31:18.712Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,58,0,0,0,3]
2023-05-24T02:31:18.715Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,28,2,0,125]
2023-05-24T02:31:18.715Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,28,2,0,125]
2023-05-24T02:31:18.715Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 28 - [2,0] - 125
2023-05-24T02:31:18.715Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}}
2023-05-24T02:31:18.716Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-05-24T02:31:18.716Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":58,"offset":0}
2023-05-24T02:31:18.716Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,58,0,0,0,3]
2023-05-24T02:31:18.719Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,28,2,0,125]
2023-05-24T02:31:18.719Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,28,2,0,125]
2023-05-24T02:31:18.719Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 28 - [2,0] - 125
2023-05-24T02:31:18.719Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}}
2023-05-24T02:31:18.719Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-05-24T02:31:18.720Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvLength - {"id":59}
2023-05-24T02:31:18.720Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,2,33,19,59,0,11]
2023-05-24T02:31:18.723Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,19,17,0,97]
2023-05-24T02:31:18.723Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,19,17,0,97]
2023-05-24T02:31:18.723Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 19 - [17,0] - 97
2023-05-24T02:31:18.723Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvLength - {"length":17}
2023-05-24T02:31:18.723Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-05-24T02:31:18.723Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":59,"offset":0}
2023-05-24T02:31:18.724Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,59,0,0,0,2]
2023-05-24T02:31:18.727Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,28,2,0,125]
2023-05-24T02:31:18.727Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,28,2,0,125]
2023-05-24T02:31:18.727Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 28 - [2,0] - 125
2023-05-24T02:31:18.727Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}}
2023-05-24T02:31:18.727Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-05-24T02:31:18.727Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":59,"offset":0}
2023-05-24T02:31:18.727Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,59,0,0,0,2]
2023-05-24T02:31:18.731Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,28,2,0,125]
2023-05-24T02:31:18.731Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,28,2,0,125]
2023-05-24T02:31:18.731Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 28 - [2,0] - 125
2023-05-24T02:31:18.731Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}}
2023-05-24T02:31:18.731Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-05-24T02:31:18.731Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvReadExt - {"id":59,"offset":0}
2023-05-24T02:31:18.731Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,33,28,59,0,0,0,2]
2023-05-24T02:31:18.735Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,28,2,0,125]
2023-05-24T02:31:18.735Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,28,2,0,125]
2023-05-24T02:31:18.735Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 28 - [2,0] - 125
2023-05-24T02:31:18.735Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvReadExt - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}}
2023-05-24T02:31:18.735Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-05-24T02:31:18.738Z zigbee-herdsman:adapter:zStack:startup:strategy (stage-1) adapter is configured
2023-05-24T02:31:18.738Z zigbee-herdsman:adapter:zStack:startup:strategy (stage-2) adapter state matches configuration
2023-05-24T02:31:18.738Z zigbee-herdsman:adapter:zStack:startup determined startup strategy: startup
2023-05-24T02:31:18.738Z zigbee-herdsman:adapter:zStack:znp:SREQ --> UTIL - getDeviceInfo - {}
2023-05-24T02:31:18.738Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,39,0,39]
2023-05-24T02:31:18.742Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,14,103,0,0,113,156,234,15,0,75,18,0,0,0,7,9,0,54]
2023-05-24T02:31:18.742Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,14,103,0,0,113,156,234,15,0,75,18,0,0,0,7,9,0,54]
2023-05-24T02:31:18.743Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 14 - 3 - 7 - 0 - [0,113,156,234,15,0,75,18,0,0,0,7,9,0] - 54
2023-05-24T02:31:18.743Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- UTIL - getDeviceInfo - {"status":0,"ieeeaddr":"0x00124b000fea9c71","shortaddr":0,"devicetype":7,"devicestate":9,"numassocdevices":0,"assocdeviceslist":[]}
2023-05-24T02:31:18.743Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2023-05-24T02:31:18.743Z zigbee-herdsman:adapter:zStack:startup adapter is already running in coordinator mode
2023-05-24T02:31:18.744Z zigbee-herdsman:adapter:zStack:znp:SREQ --> ZDO - activeEpReq - {"dstaddr":0,"nwkaddrofinterest":0}
2023-05-24T02:31:18.744Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,4,37,5,0,0,0,0,36]
2023-05-24T02:31:18.749Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,1,101,5,0,97]
2023-05-24T02:31:18.749Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,1,101,5,0,97]
2023-05-24T02:31:18.749Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 1 - 3 - 5 - 5 - [0] - 97
2023-05-24T02:31:18.749Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- ZDO - activeEpReq - {"status":0}
2023-05-24T02:31:18.749Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
Zigbee2MQTT:error 2023-05-23 22:31:28: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-05-23 22:31:28: Failed to start zigbee
Zigbee2MQTT:error 2023-05-23 22:31:28: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-05-23 22:31:28: Exiting...
Zigbee2MQTT:error 2023-05-23 22:31:28: Error: AREQ - ZDO - activeEpRsp after 10000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)

**Comment by jmpaiva** [comment]
I have the same problem, everything was working fine yestarday, today Z2m won't work and I keep having the "bad gateway" message

in the addon's logs I have the following:
14:37:38] INFO: Preparing to start...
[14:37:39] INFO: Socat not enabled
[14:37:41] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-05-24 14:37:48: Logging to console and directory: '/config/zigbee2mqtt/log/2023-05-24.14-37-48' filename: log.txt
Zigbee2MQTT:info  2023-05-24 14:37:48: Starting Zigbee2MQTT version 1.30.4-dev (commit #2d731ba)
Zigbee2MQTT:info  2023-05-24 14:37:48: Starting zigbee-herdsman (0.14.117)
Zigbee2MQTT:error 2023-05-24 14:38:49: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-05-24 14:38:49: Failed to start zigbee
Zigbee2MQTT:error 2023-05-24 14:38:49: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-05-24 14:38:49: Exiting...
Zigbee2MQTT:error 2023-05-24 14:38:49: Error: Connection not initialized
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:551:19)
    at Ezsp.version (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:349:35)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:141:25)
    at EZSPAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:165:16)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:58:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)


I'm using a xiaomi hub that is reponding correctly on mi Home and has not been updated.  I can even telnet to it on port 8888 and it opens a connection

**Comment by gordonthree** [comment]
> Likely your adapter crashed (common for CC2531), try to re-flash the firmware.

I'll give that a shot, need to find my Texas Instruments programmer and weird adapter cable.

**Comment by gordonthree** [comment]
@Koenkk nailed it ... erased and reflashed coordinator firmware to my cc2531 and it is cooperating now. 

Now I just need to figure out how to "import" the existing devices that are paired with it into z2m.
