### ISSUE TITLE
1.18.1 does not start

### ISSUE THREAD

**Issue by GD-Dal** [zigbee2mqtt/hassio-zigbee2mqtt#51]
After migrating to this new repository and installing v1.18.1, I cannot get Zigbee2MQTT to start.
Since the old v1.17.1-4 comes from another repository apparently, I now have 2 Zigbee2MQTT installations in my system...

So I stopped v1.17.1.-4, and copied the configuration settings (mosquitto user/pass, serial port) over to v.1.18.1, and try to start it.

Then I get these errors:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[13:19:15] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[13:19:15] INFO: MQTT available, fetching server detail ...
[13:19:15] INFO: Previous config file found, checking backup
[13:19:15] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[13:19:15] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:19:15] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
Zigbee2MQTT:error 2021-03-05 13:19:36: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-05 13:19:36: Failed to start zigbee
Zigbee2MQTT:error 2021-03-05 13:19:36: Exiting...
Zigbee2MQTT:error 2021-03-05 13:19:36: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-05T12_19_36_026Z-debug.log
[13:19:36] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
```

This is the configuration as it stands now:

```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: nope
  password: jerite
serial:
  port: >-
    /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2231282-if00
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
ota: {}
```

This is running on core version core-2021.3.1
Supervisor version is supervisor-2021.03.4

Rebooting or reseating the USB stick does not help.

**Comment by ciotlosm** [comment]
Can you try to update to latest 1.18.1-1? Other users found that they had deconz in their home assistant config or something happened with the usb stick that required to re-flash it.

**Comment by GD-Dal** [comment]
Hi.
I got it working.
I was missing this line in the config:
serial:
  **adapter: deconz**
After I put that in, it worked without problems.
But with an empty database.
So I copied all the files from the old directory (\share\zigbee2mqtt) to the new directory (\config\zigbee2mqtt)

Problem solved, and all is well :)
