### ISSUE TITLE
MQTT no longer working after upgrade mosquito today 24.11.2023

### ISSUE THREAD

**Issue by videobuff** [zigbee2mqtt/hassio-zigbee2mqtt#536]
### Description of the issue

Can no longer make an connection with MQTT broker core-mosquitto:1883 today.
Also not possible to connect MQTT explorer to the core-mosquitto.
Deleted the integration and re installed - no succes.

### Addon version

v1.22.1

### Platform

Core.                        2023.11.3
Supervisor               2023.11.3
Operating System.  11.1
Frontend                   20231030.2

### Logs of the issue (if applicable)

2023-11-24 23:44:33.744 ERROR (Thread-2 (_thread_main)) [homeassistant.components.mqtt.client] Unable to connect to the MQTT broker: Connection Refused: not authorised.
2023-11-24 23:44:33.746 WARNING (Thread-2 (_thread_main)) [homeassistant.components.mqtt.client] Disconnected from MQTT server core-mosquitto:1883 (5)

**Comment by Lonestar10** [comment]
I'm also having an issue with the latest update 1.34.0-1.  Zigbee2mqtt will not start. (logs below).
I've tried:
-uninstalling/reinstalling zigbee2mqtt
-uninstalling/reinstalling Mosquito Broker
-changing USB ports
-changing USB cable
-installing new Sonoff USB Dongle 3.0 (P)

**Platform**
Core:  2023.12.3
Supervisor:  2023.12.0
Operating System:  11.2
Frontend:  2023128.2

**Logs from Zigbee2mqtt add-on**

[17:19:08] INFO: Preparing to start...
[17:19:09] INFO: Socat not enabled
[17:19:11] INFO: Starting Zigbee2MQTT...

/app/node_modules/js-yaml/lib/loader.js:183
  return new YAMLException(message, mark);
         ^
YAMLException: duplicated mapping key (58:1)

 55 |   port: 8099
 56 | experimental: {}
 57 | 
 58 | external_converters:
------^
 59 |   - lywsd03mmc.js
    at generateError (/app/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/app/node_modules/js-yaml/lib/loader.js:187:9)
    at storeMappingPair (/app/node_modules/js-yaml/lib/loader.js:358:7)
    at readBlockMapping (/app/node_modules/js-yaml/lib/loader.js:1173:9)
    at composeNode (/app/node_modules/js-yaml/lib/loader.js:1441:12)
    at readDocument (/app/node_modules/js-yaml/lib/loader.js:1625:3)
    at loadDocuments (/app/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/app/node_modules/js-yaml/lib/loader.js:1714:19)
    at Object.read (/app/lib/util/yaml.ts:7:21)
    at read (/app/lib/util/settings.ts:333:20)
