### ISSUE TITLE
New Version 1.34 and Home Assistant

### ISSUE THREAD

**Issue by thphilipp** [zigbee2mqtt/hassio-zigbee2mqtt#538]
### Description of the issue

Thanks, but Even with the new version, it is not possible to operate a Conbee III stick with home assistant.There are always mistakes.
Can you help us?

### Addon version

newest

### Platform

all the newest

### Logs of the issue (if applicable)

log.txt
Zigbee2MQTT:info  2023-12-01 12:48:30: Starting Zigbee2MQTT version 1.34.0 (commit #unknown)
Zigbee2MQTT:info  2023-12-01 12:48:30: Starting zigbee-herdsman (0.25.0)
Zigbee2MQTT:error 2023-12-01 12:48:50: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-12-01 12:48:50: Failed to start zigbee
Zigbee2MQTT:error 2023-12-01 12:48:50: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-12-01 12:48:50: Exiting...
Zigbee2MQTT:error 2023-12-01 12:48:51: Error: Connection not initialized
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:551:19)
    at Ezsp.version (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:349:35)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:140:25)
    at EZSPAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:172:16)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

**Comment by direx1** [comment]
Same issue

**Comment by Lonestar10** [comment]
I'm having a similar issue with Zigbee2mqtt after the 1.34.0-1 update in November '23.  I'm using a Sonoff USB Dongle 3.0 (P).  HA seems to still recognize the the hardware but, since the update, Zigbee2mqtt will not start.

I have tried:
-uninstalling and reinstalling Zigbee2mqtt
-uninstalling and reinstalling Mosquito Broker
-reinstalling the Sonoff dongle
-replacing the Sonoff dongle (with the same model)
-changing USB ports
-rolling HA back to an earlier point (Oct '23)

I have only about 15 Zigbee devices.  At this point, I don't know how to start over with Zigbee2mqtt without entirely rebuilding Home Assistant from scratch.

**LOGS**
Here are the logs from the Zigbee2mqtt add-on in HA:
10:01:20] INFO: Preparing to start...
[10:01:20] INFO: Socat not enabled
[10:01:23] INFO: Starting Zigbee2MQTT...

/app/node_modules/js-yaml/lib/loader.js:183
  return new YAMLException(message, mark);
         ^
YAMLException: duplicated mapping key (58:1)

 55 |   port: 8099
 56 | experimental: {}
 57 | 
 58 | external_converters:
------^
 59 |   - lywsd03mmc.js
    at generateError (/app/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/app/node_modules/js-yaml/lib/loader.js:187:9)
    at storeMappingPair (/app/node_modules/js-yaml/lib/loader.js:358:7)
    at readBlockMapping (/app/node_modules/js-yaml/lib/loader.js:1173:9)
    at composeNode (/app/node_modules/js-yaml/lib/loader.js:1441:12)
    at readDocument (/app/node_modules/js-yaml/lib/loader.js:1625:3)
    at loadDocuments (/app/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/app/node_modules/js-yaml/lib/loader.js:1714:19)
    at Object.read (/app/lib/util/yaml.ts:7:21)
    at read (/app/lib/util/settings.ts:333:20) 
    
    Can anyone tell me what this means and how to fix it?

**Comment by BenSki2023** [comment]
I have the same problem and I can't start the add-on.

Addon version
1.35.1-1

I'm using the Sonoff dongle v2 E.

> data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://localhost:1883
  base_topic: zigbee2mqtt
  user: mqttuser
  password: mqttpass
serial:
  port: >-
    /dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20231216145407-if00
  adapter: ezsp

> [17:21:42] INFO: Preparing to start...
[17:21:43] INFO: Socat not enabled
[17:21:43] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2024-01-22 17:21:47: Logging to console and directory: '/config/zigbee2mqtt/log/2024-01-22.17-21-47' filename: log.txt
Zigbee2MQTT:info  2024-01-22 17:21:47: Starting Zigbee2MQTT version 1.35.1 (commit #unknown)
Zigbee2MQTT:info  2024-01-22 17:21:47: Starting zigbee-herdsman (0.30.0)
Zigbee2MQTT:error 2024-01-22 17:22:07: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-01-22 17:22:07: Failed to start zigbee
Zigbee2MQTT:error 2024-01-22 17:22:07: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-01-22 17:22:07: Exiting...
Zigbee2MQTT:error 2024-01-22 17:22:07: Error: Failure to connect
    at Ezsp.connect (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:277:19)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:139:9)
    at EZSPAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:172:16)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:98:27)
    at start (/app/index.js:107:5)

@thphilipp  is your problem solved?

**Comment by Tramuset** [comment]
A mi tambien me paso lo mismo , desde la ultima actualizacion de Zigbee2MQTT que todo va como el culo, no actualiza en OTA los dispositivos no responden, es una locura con lo que cuesto ponerlo todo apunto y lo facil que es joder todo el trabajo.
