### ISSUE TITLE
The zigbee2MQTT cannot start after 1.34 updated. 

### ISSUE THREAD

**Issue by arsancube** [zigbee2mqtt/hassio-zigbee2mqtt#539]
### Description of the issue

It could not start with following error. 

[01:47:51] INFO: Preparing to start...
[01:47:52] INFO: Socat not enabled
[01:47:53] INFO: Starting Zigbee2MQTT...

/app/node_modules/zigbee-herdsman-converters/index.js:172
        if (converter.options) {
                      ^
TypeError: Cannot read properties of undefined (reading 'options')
    at Object.addDefinition [as addDeviceDefinition] (/app/node_modules/zigbee-herdsman-converters/index.js:172:23)
    at new ExternalConverters (/app/lib/extension/externalConverters.ts:15:17)
    at new Controller (/app/lib/controller.ts:84:58)
    at start (/app/index.js:106:18)

### Addon version

1.34

### Platform

Core 2023.11.3
Frontend 20231030.2
Operating System 11.1
Frontend 20231030.2
On synology linux VM

**Comment by ornago** [comment]
Same here, I had to disable the external converter "Herdsman for Aqara T1" in my configuration to get Z2M running again. Unfortunately now I don't get sensor informations for Energy consumption from the Aquara Relais. Hope it'll be fixed soon?

**Comment by Lonestar10** [comment]
Same here.  Zigbee2mqtt will not start after the 1.34.0-1 update.  I have tried removing and reinstalling Z2M from Github (Z2M appears in the Add-On store with a blue line -- doesn't that mean an update is available?).
After adding credentials to Z2M and pointing it to the Zonoff USB Dongle P 3.0, I press Start.  On the Info page, a green dot appears, but clicking on the Zigbee2mqtt Web UI fails to start it.  
I'm running latest Home Assistant on a Generic x86-64.
Here is log from Zigbee2mqtt:
[10:13:22] INFO: Preparing to start...
[10:13:22] INFO: Socat not enabled
[10:13:24] INFO: Starting Zigbee2MQTT...

/app/node_modules/js-yaml/lib/loader.js:183
  return new YAMLException(message, mark);
         ^
YAMLException: duplicated mapping key (58:1)

 55 |   port: 8099
 56 | experimental: {}
 57 | 
 58 | external_converters:
------^
 59 |   - lywsd03mmc.js
    at generateError (/app/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/app/node_modules/js-yaml/lib/loader.js:187:9)
    at storeMappingPair (/app/node_modules/js-yaml/lib/loader.js:358:7)
    at readBlockMapping (/app/node_modules/js-yaml/lib/loader.js:1173:9)
    at composeNode (/app/node_modules/js-yaml/lib/loader.js:1441:12)
    at readDocument (/app/node_modules/js-yaml/lib/loader.js:1625:3)
    at loadDocuments (/app/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/app/node_modules/js-yaml/lib/loader.js:1714:19)
    at Object.read (/app/lib/util/yaml.ts:7:21)
    at read (/app/lib/util/settings.ts:333:20)

![z2m start button](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/94314066/a5d252ad-868c-489f-95fb-6764d23f77cf)

**Comment by moshin34** [comment]
Looks like i picked a hell of a time to move MQTT and Z2MQTT from my RasPi to the VM instance with HAOS.   Fml

This is on a fresh install 

```

[14:48:02] INFO: Preparing to start...
[14:48:03] INFO: Socat not enabled
[14:48:03] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-12-04 14:48:05: Logging to console and directory: '/config/zigbee2mqtt/log/2023-12-04.14-48-05' filename: log.txt
Zigbee2MQTT:info  2023-12-04 14:48:05: Starting Zigbee2MQTT version 1.34.0 (commit #unknown)
Zigbee2MQTT:info  2023-12-04 14:48:05: Starting zigbee-herdsman (0.25.0)
Zigbee2MQTT:error 2023-12-04 14:48:05: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-12-04 14:48:05: Failed to start zigbee
Zigbee2MQTT:error 2023-12-04 14:48:05: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-12-04 14:48:05: Exiting...
Zigbee2MQTT:error 2023-12-04 14:48:05: Error: spawn udevadm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:485:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by almanzarj** [comment]
having similar issue after upgrading to 1.34.0-1

`[19:54:13] INFO: Preparing to start...
[19:54:14] INFO: Socat not enabled
[19:54:15] INFO: Starting Zigbee2MQTT...

/app/node_modules/js-yaml/lib/loader.js:183
  return new YAMLException(message, mark);
         ^
YAMLException: duplicated mapping key (46:1)

 43 |   port: 8099
 44 | experimental: {}
 45 | availability: false
 46 | external_converters:
------^
 47 |   - lywsd03mmc.js
 48 |   
    at generateError (/app/node_modules/js-yaml/lib/loader.js:183:10)
    at throwError (/app/node_modules/js-yaml/lib/loader.js:187:9)
    at storeMappingPair (/app/node_modules/js-yaml/lib/loader.js:358:7)
    at readBlockMapping (/app/node_modules/js-yaml/lib/loader.js:1173:9)
    at composeNode (/app/node_modules/js-yaml/lib/loader.js:1441:12)
    at readDocument (/app/node_modules/js-yaml/lib/loader.js:1625:3)
    at loadDocuments (/app/node_modules/js-yaml/lib/loader.js:1688:5)
    at Object.load (/app/node_modules/js-yaml/lib/loader.js:1714:19)
    at Object.read (/app/lib/util/yaml.ts:7:21)
    at read (/app/lib/util/settings.ts:333:20)`

**Comment by Koenkk** [comment]
One of your external converters is incompatible, remove it to make z2m start

**Comment by moshin34** [comment]
Thank you Koen.  Forgive my ignorance, but what is meant by "external
converters". Can't be my conbee2 can it?
