### ISSUE TITLE
After a few days everything working i get: "Error: Reset error: Error: {"sequence":-1} after 10000ms "

### ISSUE THREAD

**Issue by r77s** [zigbee2mqtt/hassio-zigbee2mqtt#550]
### Description of the issue

Hi,
I used the zigbee2Mqtt addon a long time, but I thing after the last update there are some problem. I use the Skyconnect and after some reboot for some other updates etc. the zigbee2mqtt wont start any more. In the log I get this:

[18:46:22] INFO: Preparing to start...
[18:46:22] INFO: Socat not enabled
[18:46:23] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2023-12-26 18:46:24: Logging to console and directory: '/config/zigbee2mqtt/log/2023-12-26.18-46-24' filename: log.txt
Zigbee2MQTT:info  2023-12-26 18:46:24: Starting Zigbee2MQTT version 1.34.0 (commit #unknown)
Zigbee2MQTT:info  2023-12-26 18:46:24: Starting zigbee-herdsman (0.25.0)
Error: Reset error: Error: {"sequence":-1} after 10000ms
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:299:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

### Addon version

1.34.0-1

### Platform

Core 2023.12.3
Supervisor 2023.12.0
Operating System 11.2
Frontend 20231208.2

**Comment by njbuch** [comment]
Same here: More detailed log:
```
[22:39:42] INFO: Preparing to start...
[22:39:43] INFO: Socat not enabled
[22:39:43] INFO: Zigbee Herdsman debug logging enabled
[22:39:45] INFO: Starting Zigbee2MQTT...
2023-12-26T21:39:53.097Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2023-12-26T21:39:53.102Z zigbee-herdsman:adapter:ezsp:debg Adapter concurrent: 8
2023-12-26T21:39:53.104Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"baudRate":115200,"path":"/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220811172127-if00","adapter":"ezsp"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2023-12-26T21:39:53.109Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with {"path":"/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20220811172127-if00","baudRate":115200,"rtscts":false,"autoOpen":false}
2023-12-26T21:39:53.129Z zigbee-herdsman:adapter:ezsp:uart Serialport opened
2023-12-26T21:39:53.130Z zigbee-herdsman:adapter:ezsp:uart Uart reseting
2023-12-26T21:39:53.132Z zigbee-herdsman:adapter:ezsp:uart --> Write reset
2023-12-26T21:39:53.136Z zigbee-herdsman:adapter:ezsp:uart --> [1ac038bc7e]
2023-12-26T21:39:53.139Z zigbee-herdsman:adapter:ezsp:uart -?- waiting reset
2023-12-26T21:39:53.149Z zigbee-herdsman:adapter:ezsp:uart Serialport error: Error: EIO: i/o error, write
2023-12-26T21:39:53.150Z zigbee-herdsman:adapter:ezsp:uart Port closed
2023-12-26T21:39:53.150Z zigbee-herdsman:adapter:ezsp:ezsp Close ezsp
2023-12-26T21:39:53.152Z zigbee-herdsman:adapter:ezsp:driv Close driver
2023-12-26T21:40:03.138Z zigbee-herdsman:adapter:ezsp:uart --> Error: Error: {"sequence":-1} after 10000ms
2023-12-26T21:40:03.140Z zigbee-herdsman:adapter:ezsp:driv Reset connection. Try 0
2023-12-26T21:40:03.142Z zigbee-herdsman:adapter:ezsp:driv Stop driver
2023-12-26T21:40:03.143Z zigbee-herdsman:adapter:ezsp:ezsp Stop ezsp
2023-12-26T21:40:03.145Z zigbee-herdsman:adapter:ezsp:ezsp Close ezsp
2023-12-26T21:40:03.145Z zigbee-herdsman:adapter:ezsp:driv Close driver
Error: Reset error: Error: {"sequence":-1} after 10000ms
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:299:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
```

**Comment by Tiremo** [comment]
Yep, can confirm this exact same issue and error, using a sky connect stick.

**Comment by mlorgan** [comment]
Same issue with SONOFF Zigbee 3.0 USB Dongle Plus E

**Comment by njbuch** [comment]
Gets up and running after plugging it into a different port, but fails again after a while. A USB reset might work, seems to be an issue with the underlying driver seen from here.

**Comment by wwwdesign** [comment]
Same issue here, but with CC2531 on HA 12.4

**Comment by njbuch** [comment]
I have some HA installs in the neighborhood, all failing now. I guess this is getting critical?

**Comment by njbuch** [comment]
I experienced a crash in the log:

```
2024-01-01T16:31:46.623Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x3f: {"_cls_":"messageSentHandler","_id_":63,"_isRequest_":false,"type":0,"indexOrDestination":31151,"apsFrame":{"profileId":260,"sequence":8,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":1,"groupId":0,"options":0},"messageTag":16,"status":0,"message":{"type":"Buffer","data":[]}}
2024-01-01T16:31:46.893Z zigbee-herdsman:adapter:ezsp:uart <-- [1617b1a96b2a164fa6904b23aa546d499d58e80812ce67d5d97e]
2024-01-01T16:31:46.894Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (1,6,0): 1617b1a96b2a164fa6904b23aa546d499d58e80812ce67d5d97e
2024-01-01T16:31:46.894Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (2)
2024-01-01T16:31:46.895Z zigbee-herdsman:adapter:ezsp:uart --> [82503a7e]
2024-01-01T16:31:46.895Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 5590013f0003fdff0401060001ff000116cfa3ff0000
2024-01-01T16:31:46.896Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x3f: {"_cls_":"messageSentHandler","_id_":63,"_isRequest_":false,"type":3,"indexOrDestination":65533,"apsFrame":{"profileId":260,"sequence":163,"clusterId":6,"sourceEndpoint":1,"destinationEndpoint":255,"groupId":53014,"options":256},"messageTag":255,"status":0,"message":{"type":"Buffer","data":[]}}
2024-01-01T16:31:46.896Z zigbee-herdsman:adapter:ezsp:cast 53014 is already subscribed
2024-01-01T16:31:49.998Z zigbee-herdsman:adapter:ezsp:uart Port closed
2024-01-01T16:31:49.999Z zigbee-herdsman:adapter:ezsp:ezsp Close ezsp
2024-01-01T16:31:50.007Z zigbee-herdsman:adapter:ezsp:driv Close driver
2024-01-01T16:31:54.794Z zigbee-herdsman:adapter:ezsp:ezsp Time to watchdog ... 0
2024-01-01T16:31:54.795Z zigbee-herdsman:adapter:ezsp:ezsp ==> nop: null
2024-01-01T16:31:54.947Z zigbee-herdsman:adapter:ezsp:erro Watchdog heartbeat timeout Error: Connection not initialized
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:551:19)
    at Ezsp.watchdogHandler (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:660:24)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
2024-01-01T16:32:04.796Z zigbee-herdsman:adapter:ezsp:ezsp Time to watchdog ... 1
2024-01-01T16:32:04.796Z zigbee-herdsman:adapter:ezsp:ezsp ==> nop: null
2024-01-01T16:32:04.800Z zigbee-herdsman:adapter:ezsp:erro Watchdog heartbeat timeout Error: Connection not initialized
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:551:19)
    at Ezsp.watchdogHandler (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:660:24)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
2024-01-01T16:32:14.797Z zigbee-herdsman:adapter:ezsp:ezsp Time to watchdog ... 2
2024-01-01T16:32:14.798Z zigbee-herdsman:adapter:ezsp:ezsp ==> nop: null
2024-01-01T16:32:14.809Z zigbee-herdsman:adapter:ezsp:erro Watchdog heartbeat timeout Error: Connection not initialized
    at Ezsp.execCommand (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:551:19)
    at Ezsp.watchdogHandler (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:660:24)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
```

**Comment by Tiremo** [comment]
Issue persists in the current update 1.35.0-1.

**Comment by njbuch** [comment]
To me, it seems to have been fixed with the latest release, the Zigbee2mqtt does not crash anymore, and the device data streams are steady. Will report back the next few days.

**Comment by njbuch** [comment]
> To me, it seems to have been fixed with the latest release, the Zigbee2mqtt does not crash anymore, and the device data streams are steady. Will report back the next few days.

I was wrong, still failing after 40hours.

**Comment by Shamane2000** [comment]
I have the Issue from the TS too. 

SONOFF Zigbee 3.0 USB Dongle Plus E
System is HASSOS on a PROXMOX VM (USB Passthrough - Vendor ID) 

[14:04:15] INFO: Preparing to start...
[14:04:15] INFO: Socat not enabled
[14:04:15] INFO: Zigbee Herdsman debug logging enabled
[14:04:16] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2024-01-05 14:04:18: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2024-01-05 14:04:18: Logging to console and directory: '/config/zigbee2mqtt/log/2024-01-05.14-04-18' filename: log.txt
Zigbee2MQTT:debug 2024-01-05 14:04:18: Removing old log directory '/config/zigbee2mqtt/log/2024-01-05.12-09-01'
Zigbee2MQTT:info  2024-01-05 14:04:18: Starting Zigbee2MQTT version 1.35.0-dev (commit #b17c22b)
Zigbee2MQTT:info  2024-01-05 14:04:18: Starting zigbee-herdsman (0.30.0)
Zigbee2MQTT:debug 2024-01-05 14:04:18: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[33,203,14,38,70,232,183,105],"networkKey":"HIDDEN","panID":23673},"serialPort":{"adapter":"ezsp","path":"/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230804160602-if00"}}'
2024-01-05T13:04:18.257Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2024-01-05T13:04:18.258Z zigbee-herdsman:adapter:ezsp:debg Adapter concurrent: 8
2024-01-05T13:04:18.258Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[155,10,229,65,78,255,220,245,170,56,16,37,52,224,37,78],"panID":23673,"extendedPanID":[33,203,14,38,70,232,183,105],"channelList":[11]},"serialPort":{"path":"/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230804160602-if00","adapter":"ezsp"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"disableLED":false,"concurrent":null,"delay":null}}'
2024-01-05T13:04:18.260Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with {"path":"/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230804160602-if00","baudRate":115200,"rtscts":false,"autoOpen":false}
2024-01-05T13:04:18.266Z zigbee-herdsman:adapter:ezsp:uart Serialport opened
2024-01-05T13:04:18.266Z zigbee-herdsman:adapter:ezsp:uart Uart reseting
2024-01-05T13:04:18.266Z zigbee-herdsman:adapter:ezsp:uart --> Write reset
2024-01-05T13:04:18.267Z zigbee-herdsman:adapter:ezsp:uart --> [1ac038bc7e]
2024-01-05T13:04:18.268Z zigbee-herdsman:adapter:ezsp:uart -?- waiting reset
2024-01-05T13:04:28.272Z zigbee-herdsman:adapter:ezsp:uart --> Error: Error: {"sequence":-1} after 10000ms
2024-01-05T13:04:28.273Z zigbee-herdsman:adapter:ezsp:driv Reset connection. Try 0
2024-01-05T13:04:28.273Z zigbee-herdsman:adapter:ezsp:driv Stop driver
2024-01-05T13:04:28.273Z zigbee-herdsman:adapter:ezsp:ezsp Stop ezsp
2024-01-05T13:04:28.273Z zigbee-herdsman:adapter:ezsp:ezsp Close ezsp
2024-01-05T13:04:28.273Z zigbee-herdsman:adapter:ezsp:driv Close driver
Error: Reset error: Error: {"sequence":-1} after 10000ms
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:299:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)


As far as I see there musst be a problem with this setting of Proxmox.
ZHA is working flawless with this device. (Of course this integration is deinstalled, a lot of times reboot etc. ) 
I can provice more information about this (driver?) problem if I know what.

**Comment by burntoc** [comment]
Seeing the same issue here with my Skyconnect and my Hassio VM that was working fine.

**Comment by snurre0** [comment]
I've had the SkyConnect laying around for a while, finally decided to swap out my ConBee stick for the SkyConnect today.
Never got it to work, and I'm getting the exact same error message as all of the above.

**Comment by Tiremo** [comment]
> I've had the SkyConnect laying around for a while, finally decided to swap out my ConBee stick for the SkyConnect today. Never got it to work, and I'm getting the exact same error message as all of the above.

I went the opposite route, I had the sky connect running without issue until recently. Swapped now back to my conbee 2 stick without issues. I would argue the sky connect stick is fine, but something somewhere broke after an update. Let’s hope the developer can figure out the issue, the sky connect stick had better connectivity than the conbee.

**Comment by snurre0** [comment]
I actually just now figured out my issue. Can of course be a different issue for you all, but I had the exact startup error in Z2M as the first post here.

I went into settings -> system -> hardware on Home Assistant right after I plugged in the SkyConnect for the first time, to find a "Configure"-button saying it could enable the SkyConnect to work both with Zigbee and Thread. I thought that sounded like a good idea, without really knowing what I was doing, so I enabled it.
That ended up flashing the SkyConnect with the Multi-firmware automatically behind the scenes. And it no longer worked as a Zigbee-stick with Z2M.

So my solution was to go here: https://skyconnect.home-assistant.io/firmware-update/
and re-flash the Zigbee firmware to the SkyConnect, and it all started working. I've successfully paired my first devices back to Z2M.

**Comment by kihaki** [comment]
I am experiencing the same exact issue with Raspberry Pi 4 and Home Assistant OS

Core 2024.1.3
Supervisor 2023.12.0
Operating System 11.4
Frontend 20240104.0

Sonoff Zigbee Plus-P

I had everything working fine with Zigbee2Mqtt before, when I was using Home Assistant in a Docker container, with another docker container running Zigbee2Mqtt but since I switched to Home Assistant OS with the Zigbee2Mqtt Addon, the addon won't start with the same error message as above:

```
[12:07:51] INFO: Preparing to start...
[12:07:52] INFO: Socat not enabled
[12:07:54] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:info  2024-01-16 12:07:59: Logging to console and directory: '/config/zigbee2mqtt/log/2024-01-16.12-07-59' filename: log.txt
Zigbee2MQTT:info  2024-01-16 12:07:59: Starting Zigbee2MQTT version 1.35.1 (commit #unknown)
Zigbee2MQTT:info  2024-01-16 12:07:59: Starting zigbee-herdsman (0.30.0)
Error: Reset error: Error: {"sequence":-1} after 10000ms
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:299:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
```

**Comment by jochke** [comment]
I'm experiencing the same issue. Suddenly it's not working.

> Core 2024.1.5
Supervisor 2023.12.1
Operating System 11.4
Frontend 20240104.0

Hardware: `Home Assistant Yellow`

Zigbee2MQTT Config:

> data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt: {}
serial:
  adapter: ezsp
  port: /dev/ttyAMA1
  baudrate: 115200
  rtscts: true

Zigbee2MQTT Log:

> [20:25:26] INFO: Preparing to start...
[20:25:26] INFO: Socat not enabled
[20:25:29] INFO: Starting Zigbee2MQTT...
Zigbee2MQTT:debug 2024-01-21 20:25:36: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2024-01-21 20:25:36: Logging to console and directory: '/config/zigbee2mqtt/log/2024-01-21.20-25-36' filename: log.txt
Zigbee2MQTT:debug 2024-01-21 20:25:36: Removing old log directory '/config/zigbee2mqtt/log/2024-01-21.18-49-32'
Zigbee2MQTT:info  2024-01-21 20:25:36: Starting Zigbee2MQTT version 1.35.1 (commit #unknown)
Zigbee2MQTT:info  2024-01-21 20:25:36: Starting zigbee-herdsman (0.30.0)
Zigbee2MQTT:debug 2024-01-21 20:25:36: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","baudRate":115200,"path":"/dev/ttyAMA1","rtscts":true}}'
Error: Reset error: Error: {"sequence":-1} after 10000ms
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/uart.ts:299:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)

**Comment by jochke** [comment]
I got it working after a firmware upgrade from the official Ad-On Silicon Labs Flasher, on my Home Assistant Yellow. :)

**Comment by Tiremo** [comment]
> I got it working after a firmware upgrade from the official Ad-On Silicon Labs Flasher, on my Home Assistant Yellow. :)

I just ran the upgrade but nothing changed for me, running on a sky connect. Perhaps there are some other things in play with your HA Yellow

**Comment by janecekkrenek** [comment]
> I got it working after a firmware upgrade from the official Ad-On Silicon Labs Flasher, on my Home Assistant Yellow. :)

Which firmware file are you using for the upgrade in Home Assistant Yellow?

**Comment by jochke** [comment]
@janecekkrenek  I just used the newest version that this add-on installed: https://github.com/home-assistant/addons/tree/master/silabs_flasher

Can be found under Settings -> Add-ons -> Add-on Store -> Silicon Labs Flasher

**Comment by JericoPablo** [comment]
`Zigbee2MQTT:error 2024-02-05 20:07:10: Publish 'set' 'state' to 'Flurlicht' failed: 'Error: Command 0x0017880103b2b586/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 24511 - 11 - 56 - 6 - 11 after 10000ms)'`

getting this since the latest update of Zigbee2MQTT addon (HACS) and using HAOS. 

All lights and thermostats are broken. That’s really a critical issue.

**Comment by janecekkrenek** [comment]
> @janecekkrenek I just used the newest version that this add-on installed: https://github.com/home-assistant/addons/tree/master/silabs_flasher
> 
> Can be found under Settings -> Add-ons -> Add-on Store -> Silicon Labs Flasher

Many thank. It works for me (radio multiprotocol support and ZHA must be disabled)
