### ISSUE TITLE
Failure send clearKeyTable

### ISSUE THREAD

**Issue by gabry1609** [zigbee2mqtt/hassio-zigbee2mqtt#560]
### Description of the issue

Hello everyone,
I'm new to this world so I apologize if I'm saying something wrong.

I've recently bought a Sonoff ZigBee 3.0 dongle Plus V2 model E and I've flashed it using the online tool, to the fw version MultiPan RCP  v4.3.1 (latest one) but I can't get it to work with Zigbee2MQTT Hassio add-on.

I'm running my Hassio on a virtual machine environment, using a Synology DS423+ and I've connected the dongle using a USB 2.0 extension chord, after I've head to the virtual machine management on my Synology and changed the settings in order to connect the adapter to the VM. After that I can see it properly as "ttyACM0
/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230505135857-if00" inside Hassio.

I also have setup the MQTT Broker Add-on without any issues, as well as the SiliconLabs Multiprotocol add-on.

My config inside Zigbee2mqtt is as following:

<img width="515" alt="zigbee2mqtt config" src="https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/41947803/0ec477e6-44d6-436b-bc1d-5eb622ff29c2">

and I have the following logs from debug.

What can I do to fix the issue?

Thanks in advance.

### Addon version

1.35.1-1

### Platform

Core
2024.1.3

Supervisor
2023.12.0

Operating System
11.4

Frontend
20240104.0

### Logs of the issue (if applicable)

2024-01-13T10:29:03.646Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x2: {"_cls_":"addEndpoint","_id_":2,"_isRequest_":false,"status":0}
2024-01-13T10:29:03.647Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (5) success
2024-01-13T10:29:03.647Z zigbee-herdsman:adapter:ezsp:driv Ezsp adding endpoint: {"_cls_":"addEndpoint","_id_":2,"_isRequest_":false,"status":0}
2024-01-13T10:29:03.647Z zigbee-herdsman:adapter:ezsp:ezsp ==> addEndpoint: {"endpoint":242,"profileId":41440,"deviceId":97,"appFlags":0,"inputClusterCount":0,"outputClusterCount":1,"inputClusterList":[],"outputClusterList":[33]}
2024-01-13T10:29:03.648Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"addEndpoint","_id_":2,"_isRequest_":true,"endpoint":242,"profileId":41440,"deviceId":97,"appFlags":0,"inputClusterCount":0,"outputClusterCount":1,"inputClusterList":[],"outputClusterList":[33]}
2024-01-13T10:29:03.648Z zigbee-herdsman:adapter:ezsp:uart --> DATA (5,5,0): 1500010200f2e0a161000000012100
2024-01-13T10:29:03.648Z zigbee-herdsman:adapter:ezsp:uart --> [555721a9562ae752f8f54a25aa54b349a19c7e]
2024-01-13T10:29:03.649Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (6)
2024-01-13T10:29:03.649Z zigbee-herdsman:adapter:ezsp:uart <-- [5657a1a9562a15dc4a7e]
2024-01-13T10:29:03.650Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (5,6,0): 5657a1a9562a15dc4a7e
2024-01-13T10:29:03.650Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (6)
2024-01-13T10:29:03.651Z zigbee-herdsman:adapter:ezsp:uart --> [8610be7e]
2024-01-13T10:29:03.651Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 158001020000
2024-01-13T10:29:03.651Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x2: {"_cls_":"addEndpoint","_id_":2,"_isRequest_":false,"status":0}
2024-01-13T10:29:03.652Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (6) success
2024-01-13T10:29:03.652Z zigbee-herdsman:adapter:ezsp:driv Ezsp adding endpoint: {"_cls_":"addEndpoint","_id_":2,"_isRequest_":false,"status":0}
2024-01-13T10:29:03.652Z zigbee-herdsman:adapter:ezsp:ezsp Get EzspValueId.VALUE_VERSION_INFO
2024-01-13T10:29:03.653Z zigbee-herdsman:adapter:ezsp:ezsp ==> getValue: {"valueId":17}
2024-01-13T10:29:03.653Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"getValue","_id_":170,"_isRequest_":true,"valueId":17}
2024-01-13T10:29:03.653Z zigbee-herdsman:adapter:ezsp:uart --> DATA (6,6,0): 160001aa0011
2024-01-13T10:29:03.654Z zigbee-herdsman:adapter:ezsp:uart --> [665421a9fe2a047fda7e]
2024-01-13T10:29:03.654Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (7)
2024-01-13T10:29:03.654Z zigbee-herdsman:adapter:ezsp:uart <-- [6754a1a9fe2a15b559944d21aa5538]
2024-01-13T10:29:03.655Z zigbee-herdsman:adapter:ezsp:uart <-- [cf767e]
2024-01-13T10:29:03.655Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (6,7,0): 6754a1a9fe2a15b559944d21aa5538cf767e
2024-01-13T10:29:03.655Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (7)
2024-01-13T10:29:03.656Z zigbee-herdsman:adapter:ezsp:uart --> [87009f7e]
2024-01-13T10:29:03.656Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 168001aa000007000007040000aa
2024-01-13T10:29:03.657Z zigbee-herdsman:adapter:ezsp:ezsp <== 0xaa: {"_cls_":"getValue","_id_":170,"_isRequest_":false,"status":0,"value":{"type":"Buffer","data":[0,0,7,4,0,0,170]}}
2024-01-13T10:29:03.657Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (7) success
2024-01-13T10:29:03.657Z zigbee-herdsman:adapter:ezsp:ezsp Got EzspValueId.VALUE_VERSION_INFO = �
2024-01-13T10:29:03.658Z zigbee-herdsman:adapter:ezsp:driv EmberZNet version: 7.4.0.0 build 0
2024-01-13T10:29:03.659Z zigbee-herdsman:adapter:ezsp:ezsp ==> networkInit: null
2024-01-13T10:29:03.659Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"networkInit","_id_":23,"_isRequest_":true}
2024-01-13T10:29:03.659Z zigbee-herdsman:adapter:ezsp:uart --> DATA (7,7,0): 1700011700
2024-01-13T10:29:03.660Z zigbee-herdsman:adapter:ezsp:uart --> [775521a9432a0ae87e]
2024-01-13T10:29:03.660Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (0)
2024-01-13T10:29:03.661Z zigbee-herdsman:adapter:ezsp:uart <-- [7055a1a9432a8683907e]
2024-01-13T10:29:03.661Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (7,0,0): 7055a1a9432a8683907e
2024-01-13T10:29:03.661Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (0)
2024-01-13T10:29:03.661Z zigbee-herdsman:adapter:ezsp:uart --> [8070787e]
2024-01-13T10:29:03.662Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 178001170093
2024-01-13T10:29:03.662Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x17: {"_cls_":"networkInit","_id_":23,"_isRequest_":false,"status":147}
2024-01-13T10:29:03.662Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (0) success
2024-01-13T10:29:03.663Z zigbee-herdsman:adapter:ezsp:ezsp network init result:  {"_cls_":"networkInit","_id_":23,"_isRequest_":false,"status":147}
2024-01-13T10:29:03.663Z zigbee-herdsman:adapter:ezsp:ezsp Failure to init network
2024-01-13T10:29:03.663Z zigbee-herdsman:adapter:ezsp:ezsp ==> getNetworkParameters: null
2024-01-13T10:29:03.663Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"getNetworkParameters","_id_":40,"_isRequest_":true}
2024-01-13T10:29:03.664Z zigbee-herdsman:adapter:ezsp:uart --> DATA (0,0,0): 1800012800
2024-01-13T10:29:03.664Z zigbee-herdsman:adapter:ezsp:uart --> [005a21a97c2af7677e]
2024-01-13T10:29:03.664Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (1)
2024-01-13T10:29:03.665Z zigbee-herdsman:adapter:ezsp:uart <-- [015aa1a97c2a86b259944a25]
2024-01-13T10:29:03.665Z zigbee-herdsman:adapter:ezsp:uart <-- [aa5592499c4e27abedce678bfdc66389be047e]
2024-01-13T10:29:03.666Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (0,1,0): 015aa1a97c2a86b259944a25aa5592499c4e27abedce678bfdc66389be047e
2024-01-13T10:29:03.666Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (1)
2024-01-13T10:29:03.666Z zigbee-herdsman:adapter:ezsp:uart --> [8160597e]
2024-01-13T10:29:03.666Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 188001280093000000000000000000000000000000000000000000
2024-01-13T10:29:03.667Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x28: {"_cls_":"getNetworkParameters","_id_":40,"_isRequest_":false,"status":147,"nodeType":0,"parameters":{"extendedPanId":[0,0,0,0,0,0,0,0],"panId":0,"radioTxPower":0,"radioChannel":0,"joinMethod":0,"nwkManagerId":0,"nwkUpdateId":0,"channels":0}}
2024-01-13T10:29:03.668Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (1) success
2024-01-13T10:29:03.668Z zigbee-herdsman:adapter:ezsp:driv Current Node type: 0, Network parameters: EmberNetworkParameters: {"extendedPanId":[0,0,0,0,0,0,0,0],"panId":0,"radioTxPower":0,"radioChannel":0,"joinMethod":0,"nwkManagerId":0,"nwkUpdateId":0,"channels":0}
2024-01-13T10:29:03.668Z zigbee-herdsman:adapter:ezsp:ezsp ==> networkState: null
2024-01-13T10:29:03.669Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"networkState","_id_":24,"_isRequest_":true}
2024-01-13T10:29:03.669Z zigbee-herdsman:adapter:ezsp:uart --> DATA (1,1,0): 1900011800
2024-01-13T10:29:03.669Z zigbee-herdsman:adapter:ezsp:uart --> [7d315b21a94c2a07877e]
2024-01-13T10:29:03.669Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (2)
2024-01-13T10:29:03.670Z zigbee-herdsman:adapter:ezsp:uart <-- [125ba1a94c2a154f217e]
2024-01-13T10:29:03.670Z zigbee-herdsman:adapter:ezsp:uart <-- DATA (1,2,0): 125ba1a94c2a154f217e
2024-01-13T10:29:03.670Z zigbee-herdsman:adapter:ezsp:uart --> ACK  (2)
2024-01-13T10:29:03.670Z zigbee-herdsman:adapter:ezsp:uart --> [82503a7e]
2024-01-13T10:29:03.671Z zigbee-herdsman:adapter:ezsp:ezsp <== Frame: 198001180000
2024-01-13T10:29:03.671Z zigbee-herdsman:adapter:ezsp:ezsp <== 0x18: {"_cls_":"networkState","_id_":24,"_isRequest_":false,"status":0}
2024-01-13T10:29:03.671Z zigbee-herdsman:adapter:ezsp:uart -+- waiting (2) success
2024-01-13T10:29:03.672Z zigbee-herdsman:adapter:ezsp:driv Network state 0
2024-01-13T10:29:03.672Z zigbee-herdsman:adapter:ezsp:ezsp ==> clearKeyTable: null
2024-01-13T10:29:03.672Z zigbee-herdsman:adapter:ezsp:ezsp ==> {"_cls_":"clearKeyTable","_id_":177,"_isRequest_":true}
2024-01-13T10:29:03.672Z zigbee-herdsman:adapter:ezsp:uart --> DATA (2,2,0): 1a0001b100
2024-01-13T10:29:03.673Z zigbee-herdsman:adapter:ezsp:uart --> [225821a9e52aafdf7e]
2024-01-13T10:29:03.673Z zigbee-herdsman:adapter:ezsp:uart -?- waiting (3)
2024-01-13T10:29:05.674Z zigbee-herdsman:adapter:ezsp:uart --> Error: Error: {"sequence":3} after 2000ms
2024-01-13T10:29:05.674Z zigbee-herdsman:adapter:ezsp:uart -!- break waiting (3)
2024-01-13T10:29:05.674Z zigbee-herdsman:adapter:ezsp:uart Can't send DATA frame (2,2,0): 1a0001b100
2024-01-13T10:29:06.176Z zigbee-herdsman:adapter:ezsp:uart ->> DATA (2,2,1): 1a0001b100
2024-01-13T10:29:06.177Z zigbee-herdsman:adapter:ezsp:uart --> [2a5821a9e52aa29d7e]
2024-01-13T10:29:06.177Z zigbee-herdsman:adapter:ezsp:uart -?- rewaiting (3)
2024-01-13T10:29:08.180Z zigbee-herdsman:adapter:ezsp:uart --> Error: Error: {"sequence":3} after 2000ms
2024-01-13T10:29:08.180Z zigbee-herdsman:adapter:ezsp:uart -!- break rewaiting (3)
2024-01-13T10:29:08.180Z zigbee-herdsman:adapter:ezsp:uart Can't resend DATA frame (2,2,1): 1a0001b100
2024-01-13T10:29:08.180Z zigbee-herdsman:adapter:ezsp:driv Reset connection. Try 0
2024-01-13T10:29:08.180Z zigbee-herdsman:adapter:ezsp:driv Stop driver
2024-01-13T10:29:08.181Z zigbee-herdsman:adapter:ezsp:ezsp Stop ezsp
Zigbee2MQTT:error 2024-01-13 11:29:08: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-01-13 11:29:08: Failed to start zigbee
Zigbee2MQTT:error 2024-01-13 11:29:08: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-01-13 11:29:08: Exiting...
Zigbee2MQTT:error 2024-01-13 11:29:08: Error: Failure send clearKeyTable:{"type":"Buffer","data":[26,0,1,177,0]}
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:562:23
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
2024-01-13T10:29:08.276Z zigbee-herdsman:adapter:ezsp:uart Port closed
2024-01-13T10:29:08.276Z zigbee-herdsman:adapter:ezsp:ezsp Close ezsp
2024-01-13T10:29:08.276Z zigbee-herdsman:adapter:ezsp:driv Close driver

**Comment by mattiaskagstrom** [comment]
I have the same issue. Probobly due to this:
![image](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/assets/3661126/ce1fccec-a77e-42d2-9e0b-aeab19c2153e)

Gonna try an older version
