### ISSUE TITLE
cannot remove the device

### ISSUE THREAD

**Issue by papick-tol** [zigbee2mqtt/hassio-zigbee2mqtt#584]
### Description of the issue

After updating z2m, I have problems deleting devices.
The only solution I found:
1. Allow connection of new devices in z2m
2. Reset the device
3. As soon as the device disappears from the list in z2m, cut off the power to the device (so that it does not have time to connect again).

### Addon version

Current version: 1.36.0-1

### Platform

Core 2024.3.3
Supervisor 2024.03.0
Operating System debian
Frontend 20240307.0

**Comment by papick-tol** [comment]
error 2024-03-27 13:27:37Request 'zigbee2mqtt_1/bridge/request/device/remove' failed with error: 'Failed to remove device '0xa4c138ed0944ed91' (block: false, force: false) (Error: {"address":22668,"clusterId":32820,"sequence":214} after 10000ms)'
error 2024-03-27 13:28:07Failed to configure '0xa4c138ed0944ed91', attempt 1 (Error: Read 0xa4c138ed0944ed91/1 genBasic(["manufacturerName","zclVersion","appVersion","modelId","powerSource",65534], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 22668 - 1 - 165 - 0 - 1 after 10000ms) at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:63:23) at EZSPAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/adapter/ezspAdapter.ts:492:47) at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20) at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:79:20) at Endpoint.read (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:466:28) at Object.configureMagicPacket [as configure] (/app/node_modules/zigbee-herdsman-converters/src/lib/tuya.ts:378:9) at Configure.configure (/app/lib/extension/configure.ts:122:13) at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17))
