### ISSUE TITLE
What to doo

### ISSUE THREAD

**Issue by Maersk69** [zigbee2mqtt/hassio-zigbee2mqtt#616]
What to doo :(

[19:40:59] INFO: Preparing to start...
[19:40:59] INFO: Socat not enabled
[19:40:59] INFO: Starting Zigbee2MQTT...
[2024-06-05 19:41:01] info: 	z2m: Logging to console, file (filename: log.log)
[2024-06-05 19:41:01] info: 	z2m: Starting Zigbee2MQTT version 1.38.0 (commit #unknown)
[2024-06-05 19:41:01] info: 	z2m: Starting zigbee-herdsman (0.49.2)
[2024-06-05 19:41:02] info: 	zh:ember: Using default stack config.
[2024-06-05 19:41:02] info: 	zh:ember: ======== Ember Adapter Starting ========
[2024-06-05 19:41:02] info: 	zh:ember:ezsp: ======== EZSP starting ========
[2024-06-05 19:41:02] info: 	zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-06-05 19:41:02] info: 	zh:ember:uart:ash: RTS/CTS config is off, enabling software flow control.
[2024-06-05 19:41:02] info: 	zh:ember:uart:ash: Serial port opened
[2024-06-05 19:41:02] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-06-05 19:41:04] info: 	zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-06-05 19:41:04] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-06-05 19:41:07] info: 	zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-06-05 19:41:07] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-06-05 19:41:09] info: 	zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-06-05 19:41:09] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-06-05 19:41:12] info: 	zh:ember:uart:ash: ======== ASH NCP reset ========
[2024-06-05 19:41:12] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-06-05 19:41:14] error: 	z2m: Error while starting zigbee-herdsman
[2024-06-05 19:41:14] error: 	z2m: Failed to start zigbee
[2024-06-05 19:41:14] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-06-05 19:41:14] error: 	z2m: Exiting...
[2024-06-05 19:41:14] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:850:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:2683:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:127:29)
    at Zigbee.start (/app/lib/zigbee.ts:62:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)

### Addon version

??

### Platform

Core
2024.5.5
Supervisor
2024.05.1
Operating System
12.3
Brugerflade
20240501.1

**Comment by Lymkin** [comment]
Looks like you switched from ezsp to ember driver. I had the same issue. I had to manually edit the configuration.yaml and change the setting from "adapter: ezsp" to "adapter: ember". Restart addon. The Home Assistant integration where you are supposed to change it didn't reflect in this file.

**Comment by Nerivec** [comment]
When the adapter loops the `ASH starting` without success like this, it usually means the adapter firmware doesn't match the z2m configuration (`baudrate` most likely, if you didn't flash a 115200 firmware -default-, you need to specify which one you flashed in the z2m configuration). https://www.zigbee2mqtt.io/guide/configuration/adapter-settings.html#configuration-of-the-zigbee-adapter

If that doesn't work, can you switch log level to `debug` and post the logs?
