### ISSUE TITLE
after update to 1.39-01 ver Add-on try to start but fails

### ISSUE THREAD

**Issue by arripeo** [zigbee2mqtt/hassio-zigbee2mqtt#625]
### Description of the issue

After update to the last version the add-on try to star ricursively then fails and stop. 
this is my config file that was the same for all the past version

data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  base_topic: homeassistant
  server: mqtt://192.168.1.12:1883
  user: xxxxxxx
  password: xxxxxxx
serial:
  port: /dev/ttyUSB0
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
advanced:
  log_level: info
  pan_id: 6755
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}

### Addon version

1.39.0-1 

### Platform

Core  2024.6.4
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240610.1

### Logs of the issue (if applicable)

[09:34:55] INFO: Preparing to start...
[09:34:55] INFO: Socat not enabled
[09:34:56] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-07-02 09:34:59] info: 	z2m: Logging to console, file (filename: log.log)
Error: 'homeassistant.discovery_topic' cannot not be equal to the 'mqtt.base_topic' (got 'homeassistant')
    at new HomeAssistant (/app/lib/extension/homeassistant.ts:191:19)
    at new Controller (/app/lib/controller.ts:124:45)
    at start (/app/index.js:152:18)
[09:34:59] INFO: Preparing to start...
[09:35:00] INFO: Socat not enabled
[09:35:00] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-07-02 09:35:03] info: 	z2m: Logging to console, file (filename: log.log)
Error: 'homeassistant.discovery_topic' cannot not be equal to the 'mqtt.base_topic' (got 'homeassistant')
    at new HomeAssistant (/app/lib/extension/homeassistant.ts:191:19)
    at new Controller (/app/lib/controller.ts:124:45)
    at start (/app/index.js:152:18)
[09:35:04] INFO: Preparing to start...
[09:35:04] INFO: Socat not enabled
[09:35:05] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-07-02 09:35:07] info: 	z2m: Logging to console, file (filename: log.log)
Error: 'homeassistant.discovery_topic' cannot not be equal to the 'mqtt.base_topic' (got 'homeassistant')
    at new HomeAssistant (/app/lib/extension/homeassistant.ts:191:19)
    at new Controller (/app/lib/controller.ts:124:45)
    at start (/app/index.js:152:18)

**Comment by N3rdix** [comment]
Probably this issue: https://github.com/Koenkk/zigbee2mqtt/pull/23209

**Comment by arripeo** [comment]
my homeassistant.discovery and mqtt.basetopic are the same and are "homeassistant". I haven't understood if they should be different or equal. In my opinion shal be equal

**Comment by N3rdix** [comment]
They must not be the same topic, that's why it's failing

**Comment by arripeo** [comment]
So if i change the Mqtt base topic, will i lost all my entities and shall i re-enter all my entities? Thank

**Comment by arripeo** [comment]
Ok I've changed the base topic devices and entities was lost, then after a full bootstarp of the server everything goes up. The only thing that are missing are the alias of some entities but it's a small problem.

**Comment by arripeo** [comment]
The issue is solved
