### ISSUE TITLE
Zigbee2MQTT addon failes to start

### ISSUE THREAD

**Issue by hillmar** [zigbee2mqtt/hassio-zigbee2mqtt#634]
### Description of the issue

All of a sudden the Zigbee2MQTT addon fails to start. I have not done any changes in the config, or Zigbee-network prior to this.

I'm able to get the edge-version (how can I find the version I'm running???) running with the same config.

My config:
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt
  password: drOG7eVjkYrmu0LaYsQ5
serial:
  port: tcp://10.0.1.33:10004
  adapter: zstack
zigbee_herdsman_debug: false
watchdog: default

Zigbee coordinator: Sonoff ZBDongle-P (used trough ser2net on a raspberry)

### Addon version

v1.39.1-1

### Platform

Core: 2024.8.3
Supervisor: 2024.08.0
Operating System: 13.1

### Logs of the issue (if applicable)

[23:10:47] INFO: Preparing to start...
[23:10:47] INFO: Socat not enabled
[23:10:47] INFO: Enabled Zigbee2MQTT watchdog with value 'default'
[23:10:48] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT with watchdog (60000,300000,900000,1800000,3600000).
[2024-08-26 23:10:51] error: 	z2m: Error while starting zigbee-herdsman
[2024-08-26 23:10:51] error: 	z2m: Failed to start zigbee
[2024-08-26 23:10:51] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-08-26 23:10:51] error: 	z2m: Exiting...
[2024-08-26 23:10:51] error: 	z2m: RangeError: Attempt to access memory outside buffer bounds
    at new NodeError (node:internal/errors:405:5)
    at boundsError (node:internal/buffer:86:11)
    at Buffer.readUInt16BE (node:internal/buffer:334:5)
    at /app/node_modules/zigbee-herdsman/src/utils/backup.ts:113:89
    at Array.map (<anonymous>)
    at Object.fromUnifiedBackup (/app/node_modules/zigbee-herdsman/src/utils/backup.ts:112:33)
    at AdapterBackup.getStoredBackup (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/adapter-backup.ts:51:32)
    at ZnpAdapterManager.determineStrategy (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:130:24)
    at ZnpAdapterManager.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/manager.ts:57:26)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:127:29)

**Comment by onstat** [comment]
also have the same problem with mine

**Comment by heeeck** [comment]
same here

**Comment by Papadoma** [comment]
here too

**Comment by hillmar** [comment]
The issue seems to be fixed in v1.40.0-1. I do not know why, but thanks anyway.
