### ISSUE TITLE
Error while starting zigbee-herdsman

### ISSUE THREAD

**Issue by Chris3467893** [zigbee2mqtt/hassio-zigbee2mqtt#636]
### Description of the issue

Hi, I have a problem with the zigbee2mqtt Add-On on my home assistant green box. I use the Sonoff Zigbee Dongle 3.0 Plus which is connected via an USB extension cable. I installed the mosquito broker successfully and it is running. Yesterday I was able to start the zigbee2mqtt add-on and attached some devices. Then comes an error message that the zigbee Dongle recognized an error and that I should restore a backup. After I did this, I'm not longer able to start zigbee2mqtt. It reports always an error with the zigbee-herdsman. Among several other approaches I deleted all devices in mosquito broker and in zigbee, deinstalled mosquito and zigbee2mqtt and installed both again. But that doesn't help. 

### Addon version

1.40.1-1 

### Platform

Core 2024.9.1
Supervisor 2024.09.1
Operating System 13.1

### Logs of the issue (if applicable)

[23:42:57] INFO: Preparing to start...
[23:42:58] INFO: Socat not enabled
[23:43:03] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-09-13 23:43:13] info: 	z2m: Logging to console, file (filename: log.log)
[2024-09-13 23:43:13] info: 	z2m: Starting Zigbee2MQTT version 1.40.1 (commit #unknown)
[2024-09-13 23:43:13] info: 	z2m: Starting zigbee-herdsman (0.57.3)
[2024-09-13 23:43:14] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyUSB0","baudRate":115200,"rtscts":false,"autoOpen":false}
[2024-09-13 23:43:14] info: 	zh:zstack:znp: Serialport opened
[2024-09-13 23:43:14] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-09-13 23:43:16] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-09-13 23:43:34] error: 	z2m: Error while starting zigbee-herdsman
[2024-09-13 23:43:34] error: 	z2m: Failed to start zigbee
[2024-09-13 23:43:34] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-09-13 23:43:34] error: 	z2m: Exiting...
[2024-09-13 23:43:34] error: 	z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:123:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:138:29)
    at Zigbee.start (/app/lib/zigbee.ts:64:27)
    at Controller.start (/app/lib/controller.ts:140:27)
    at start (/app/index.js:154:5)

**Comment by Chris3467893** [comment]
I solved the problem. I wasn't aware, that the ZHA integration was still using the dongle. After I deactivated ZHA the problem was gone.

**Comment by Chris3467893** [comment]
I solved the problem. I wasn't aware, that the ZHA integration was still using the dongle. After I deactivated ZHA the problem was gone.

**Comment by CaesarNaykid** [comment]
how did you "deactivate" the ZHA? I removed it from Integrations but is that enough?
