### ISSUE TITLE
Addon not starting with HA OS 13.2

### ISSUE THREAD

**Issue by blitzdose** [zigbee2mqtt/hassio-zigbee2mqtt#651]
### Description of the issue

I just updated my HA OS running on a Raspberry Pi to 13.2 and the Zigbee2MQTT Add-On just stopped working. The container just doesn't start anymore. No error logs (Neither in the supervisor nor in the addon logs). I click start and basically nothing happens. The watchdog will also just give up after 10 tries without success. It was working wonderfully before the update.

### Addon version

1.40.2-1

### Platform

Core: 2024.10.4 Supervisor: 2024.10.3 Operating System: HA OS 13.2 on Raspberry Pi

**Comment by blitzdose** [comment]
Additional Info: Even starting the container from the command line returns nothing. With -ai to forward STDIN, STDERR and STDOUT the command just exits pretty much immediately. Status: **Exited (139)**

**Comment by delightfuldude** [comment]
I can confirm that behavior, addon doesn't start.

Hardware:
Raspberry Pi 3

Home Assistant:
Core 2024.10.4
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.4

Zigbee2MQTT
Current version: 1.40.2-1

**Comment by blitzdose** [comment]
Found the error, The `ghcr.io/home-assistant/aarch64-base:3.19` Image is not working with HA OS 13.2 on the raspberry pi. Even commands like `ls` just give Segmentation fault. Updating to version 3.20 (newest) fixes the problem. I will open a pull request

**Comment by delightfuldude** [comment]
Still doesn't work after recent updates:

**Hardware:**
Raspberry Pi 3

**Home Assistant:**
Core 2024.11.0
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.0

**Zigbee2MQTT**
Current version: 1.41.0-1

**Logs:**
[08:58:15] INFO: Preparing to start...
[08:58:16] INFO: Socat not enabled
[08:58:16] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-11-07 08:58:34] info: 	z2m: Logging to console, file (filename: log.log)
[2024-11-07 08:58:35] info: 	z2m: Starting Zigbee2MQTT version 1.41.0 (commit #unknown)
[2024-11-07 08:58:35] info: 	z2m: Starting zigbee-herdsman (2.1.7)
[2024-11-07 08:58:37] error: 	z2m: Error while starting zigbee-herdsman
[2024-11-07 08:58:37] error: 	z2m: Failed to start zigbee
[2024-11-07 08:58:37] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-11-07 08:58:37] error: 	z2m: Exiting...
[2024-11-07 08:58:37] error: 	z2m: Error: No path provided and failed to auto detect path
    at Function.create (/app/node_modules/zigbee-herdsman/src/adapter/adapter.ts:107:23)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:133:24)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)

    
Sorry, I'm new to Home Assistant. Are there any known workarounds to get this working?

**Comment by Koenkk** [comment]
This issue has been fixed in the mean time.

@delightfuldude in your case it cannot find the adapter, you need to configure it correctly, see step 7 of the [README](https://github.com/zigbee2mqtt/hassio-zigbee2mqtt?tab=readme-ov-file#installation)
