### ISSUE TITLE
z2m stop working

### ISSUE THREAD

**Issue by Leon3310** [zigbee2mqtt/hassio-zigbee2mqtt#657]
### Description of the issue

Good morning,

As of yesterday morning, zigbee2mqtt no longer works.  I had several events at the same time yesterday morning. Power cut and I updated Home asssitant to 2024.11 as well.

Does anyone have any ideas?

Thanks

```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: false
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: ***********
  password: *************
serial:
  port: /dev/ttyACM0
  adapter: ember

```

ttyACM0
/dev/serial/by-id/usb-ITEAD_SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2_20230804161618-if00

### Addon version

1.41.0-1

### Platform

Core 2024.11.0
Supervisor 2024.11.2
Operating System 13.2
Interface utilisateur 20241106.0

### Logs of the issue (if applicable)

[2024-11-07 09:10:15] info: 	z2m: Logging to console, file (filename: log.log)
[2024-11-07 09:10:15] info: 	z2m: Loaded external converter 't200.js'
[2024-11-07 09:10:15] debug: 	z2m: Loaded state from file /config/zigbee2mqtt/state.json
[2024-11-07 09:10:15] info: 	z2m: Starting Zigbee2MQTT version 1.41.0 (commit #unknown)
[2024-11-07 09:10:15] debug: 	z2m: sd-notify loaded
[2024-11-07 09:10:15] info: 	z2m: Starting zigbee-herdsman (2.1.7)
[2024-11-07 09:10:15] debug: 	z2m: Using zigbee-herdsman with settings: '"{\"network\":{\"panID\":19922,\"extendedPanID\":[156,113,22,196,5,49,113,166],\"channelList\":[11],\"networkKey\":\"HIDDEN\"},\"databasePath\":\"/config/zigbee2mqtt/database.db\",\"databaseBackupPath\":\"/config/zigbee2mqtt/database.db.backup\",\"backupPath\":\"/config/zigbee2mqtt/coordinator_backup.json\",\"serialPort\":{\"path\":\"/dev/ttyACM0\",\"adapter\":\"ember\"},\"adapter\":{\"disableLED\":false}}"'
[2024-11-07 09:10:16] debug: 	zh:adapter: Path '/dev/ttyACM0' is valid for 'EmberAdapter'
[2024-11-07 09:10:16] info: 	zh:ember: Using default stack config.
[2024-11-07 09:10:16] debug: 	zh:controller: Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":"HIDDEN","panID":19922,"extendedPanID":[156,113,22,196,5,49,113,166],"channelList":[11]},"serialPort":{"path":"/dev/ttyACM0","adapter":"ember"},"adapter":{"disableLED":false},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json"}'
[2024-11-07 09:10:16] info: 	zh:ember: ======== Ember Adapter Starting ========
[2024-11-07 09:10:16] info: 	zh:ember:ezsp: ======== EZSP starting ========
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash: ======== ASH Adapter reset ========
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash: RTS/CTS config is off, enabling software flow control.
[2024-11-07 09:10:16] debug: 	zh:ember:uart:ash: Opening serial port with {"path":"/dev/ttyACM0","baudRate":115200,"rtscts":false,"autoOpen":false,"parity":"none","stopBits":1,"xon":true,"xoff":true}
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash: ASH COUNTERS since last clear:
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   Total frames: RX=0, TX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   Cancelled   : RX=0, TX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   DATA frames : RX=0, TX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   DATA bytes  : RX=0, TX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   Retry frames: RX=0, TX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   ACK frames  : RX=0, TX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   NAK frames  : RX=0, TX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   nRdy frames : RX=0, TX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   CRC errors      : RX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   Comm errors     : RX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   Length < minimum: RX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   Length > maximum: RX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   Bad controls    : RX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   Bad lengths     : RX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   Bad ACK numbers : RX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   Out of buffers  : RX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   Retry dupes     : RX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   Out of sequence : RX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash:   ACK timeouts    : RX=0
[2024-11-07 09:10:16] info: 	zh:ember:uart:ash: ======== ASH stopped ========
[2024-11-07 09:10:16] error: 	zh:ember:uart:ash: Failed to init port with error Error: Error Resource temporarily unavailable Cannot lock port
[2024-11-07 09:10:16] error: 	z2m: Error while starting zigbee-herdsman
[2024-11-07 09:10:16] error: 	z2m: Failed to start zigbee
[2024-11-07 09:10:16] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-11-07 09:10:16] error: 	z2m: Exiting...
[2024-11-07 09:10:16] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:684:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1598:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)

**Comment by patriceB91** [comment]
Exact same problem... 1st after a updates to lasts HA versions.
A roll back to a previous backup solved temporarily. 
But the problem occurred again, with no  changes this time.
A restart or full reboot does not bring zigbee2mqtt alive.
==> ZB controler is the also SONOFF_Zigbee_3.0_USB_Dongle_Plus_V2
Double checked many ob the solution proposed by zigbee2mqtt from the link given in the log.
No success. 
I was in the process of switching from ZHA to Z2M.... finally I had less problems with ZHA... 
By the way I use two different Sonoff ZB controllers, one for each (ZHA / Z2M).
Can someone give some good fix please...
