### ISSUE TITLE
Update Zigbee2MQTT 1.42.0-2 from 1.41.0-1 crashes VirtualBox VM

### ISSUE THREAD

**Issue by danwooller** [zigbee2mqtt/hassio-zigbee2mqtt#669]
### Description of the issue

While running the update, HA crashes. It creates the backup and the new folder in addons, then just dies.

Restart of VirtualBox VM required

### Addon version

1.42.0-2

### Platform

Core 2024.12.0
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.4

### Logs of the issue (if applicable)

2024-12-06 17:09:50.021 INFO (MainThread) [supervisor.backups.manager] Backup 39db6845 starting stage addon_repositories
2024-12-06 17:09:50.021 INFO (MainThread) [supervisor.backups.manager] Backup 39db6845 starting stage docker_config
2024-12-06 17:09:50.021 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 39db6845
2024-12-06 17:09:50.024 INFO (MainThread) [supervisor.backups.manager] Backup 39db6845 starting stage addons
2024-12-06 17:09:50.053 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on 45df7312_zigbee2mqtt
2024-12-06 17:09:50.084 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon 45df7312_zigbee2mqtt
2024-12-06 17:09:50.084 INFO (MainThread) [supervisor.backups.manager] Backup 39db6845 starting stage finishing_file
2024-12-06 17:09:50.088 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 39db6845 completed
2024-12-06 17:09:50.089 INFO (MainThread) [supervisor.docker.addon] Updating image zigbee2mqtt/zigbee2mqtt-amd64:1.41.0-1 to zigbee2mqtt/zigbee2mqtt-amd64:1.42.0-2
2024-12-06 17:09:50.089 INFO (MainThread) [supervisor.docker.interface] Downloading docker image zigbee2mqtt/zigbee2mqtt-amd64 with tag 1.42.0-2.
2024-12-06 17:09:51.205 INFO (MainThread) [supervisor.addons.addon] Add-on '45df7312_zigbee2mqtt' successfully updated
2024-12-06 17:09:51.254 INFO (SyncWorker_0) [supervisor.docker.manager] Cleanup images: ['zigbee2mqtt/zigbee2mqtt-amd64:1.42.0-1']
2024-12-06 17:09:51.862 INFO (SyncWorker_0) [supervisor.docker.manager] Cleanup images: ['zigbee2mqtt/zigbee2mqtt-amd64:1.41.0-1']
2024-12-06 17:10:02.271 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_45df7312_zigbee2mqtt application
2024-12-06 17:10:03.198 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.42.0-2
2024-12-06 17:10:03.995 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2082' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1491> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1505, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-12-06 17:10:18.016 ERROR (SyncWorker_2) [supervisor.docker.manager] Container addon_45df7312_zigbee2mqtt is not running
2024-12-06 17:10:33.501 ERROR (SyncWorker_0) [supervisor.docker.manager] Container addon_45df7312_zigbee2mqtt is not running
2024-12-06 17:10:37.784 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_45df7312_zigbee2mqtt application
2024-12-06 17:10:38.215 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.42.0-2
2024-12-06 17:10:38.255 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
2024-12-06 17:10:38.701 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2191' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1491> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1505, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-12-06 17:10:51.198 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
2024-12-06 17:10:57.297 WARNING (MainThread) [supervisor.addons.manager] No update available for add-on 45df7312_zigbee2mqtt
2024-12-06 17:11:10.818 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_45df7312_zigbee2mqtt application
2024-12-06 17:11:11.251 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.42.0-2
2024-12-06 17:11:11.746 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2322' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1491> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1505, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-12-06 17:11:24.410 INFO (SyncWorker_5) [supervisor.docker.manager] Cleaning addon_45df7312_zigbee2mqtt application
2024-12-06 17:11:24.963 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.42.0-2
2024-12-06 17:11:25.484 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-2420' coro=<Addon.watchdog_container() done, defined at /usr/src/supervisor/supervisor/addons/addon.py:1491> exception=AddonsJobError('Rate limit exceeded, more than 10 calls in 0:30:00')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 1505, in watchdog_container
    await self._restart_after_problem(event.state)
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 291, in wrapper
    raise on_condition(
supervisor.exceptions.AddonsJobError: Rate limit exceeded, more than 10 calls in 0:30:00
2024-12-06 17:11:34.755 ERROR (SyncWorker_4) [supervisor.docker.manager] Container addon_45df7312_zigbee2mqtt is not running
2024-12-06 17:11:42.831 INFO (SyncWorker_4) [supervisor.docker.manager] Cleaning addon_45df7312_zigbee2mqtt application
2024-12-06 17:11:43.281 INFO (MainThread) [supervisor.docker.addon] Starting Docker add-on zigbee2mqtt/zigbee2mqtt-amd64 with version 1.42.0-2
2024-12-06 17:11:43.356 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
2024-12-06 17:11:43.808 ERROR (MainThread) [asyncio] Task exception was never retrieved

**Comment by danwooller** [comment]
Further, trying to stop container hangs...

VBoxManage controlvm "homeassistant" poweroff
0%...10%...20%...

The only way out is to kill the process.

**Comment by osheriff** [comment]
I experience the same exact issue. The update has remained in my update list since release

**Comment by danwooller** [comment]
No one seemed bothered, even to say it's you, dummy.
