### ISSUE TITLE
Error: serial.adapter should be equal to one of the allowed values - not accepting EZSP on 1.18.1-2

### ISSUE THREAD

**Issue by DanielPiccoli** [zigbee2mqtt/hassio-zigbee2mqtt#67]
Attempting to use Sonoff ZBbridge (EZSP)
stable ZIGBEE2MQTT  1.18.1-2

```
Core
core-2021.3.4

Supervisor
supervisor-2021.03.4

Operating System
Home Assistant OS 5.12
```

**Error shown:**
- serial.adapter should be equal to one of the allowed values

Despite CONFIG.JSON mentioning ezsp as being a valid and allowed value. - what am I missing?

```
    "serial": {
      "port": "str",
      "disable_led": "bool?",
      "adapter": "match(^zstack|deconz|zigate|ezsp$)?"
    },
```
Maybe @Koenkk has to update the settings.schema.json to allow the new adapter type?
```
         "adapter": {
          "type": ["string", "null"],
          "enum": ["deconz", "zstack", "zigate"],
```

**CONFIGURATION**:

```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto:1883'
  user: <USER>
  password: <PASS>
serial:
  adapter: ezsp
  port: 'tcp://10.0.2.23:8888'
advanced:
  log_level: warn
....
....
...
```

**LOGS**:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[10:40:35] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[10:40:35] INFO: MQTT available, fetching server detail ...
[10:40:35] INFO: Previous config file found, checking backup
[10:40:35] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[10:40:36] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[10:40:36] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            READ THIS CAREFULLY
Refusing to start because configuration is not valid, found the following errors:
**- serial.adapter should be equal to one of the allowed values**
If you don't know how to solve this, read https://www.zigbee2mqtt.io/information/configuration.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-14T13_40_38_565Z-debug.log
[10:40:38] INFO: Handing over control to Zigbee2mqtt Core ...
```

**Comment by DanielPiccoli** [comment]
Attempting the same setup on EDGE branch gives me:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[11:43:08] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[11:43:09] INFO: MQTT available, fetching server detail ...
[11:43:09] INFO: Previous config file found, checking backup
[11:43:09] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[11:43:09] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:43:10] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1-dev start /app
> node index.js
Zigbee2MQTT:info  2021-03-14 11:43:13: Logging to console and directory: '/config/zigbee2mqtt/log/2021-03-14.11-43-12' filename: log.txt
Zigbee2MQTT:info  2021-03-14 11:43:13: Starting Zigbee2MQTT version 1.18.1-dev (commit #7b54d18)
Zigbee2MQTT:info  2021-03-14 11:43:13: Starting zigbee-herdsman (0.13.79)
Assertion failed
Assertion failed
Assertion failed
Zigbee2MQTT:error 2021-03-14 11:43:29: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-14 11:43:29: Failed to start zigbee
Zigbee2MQTT:error 2021-03-14 11:43:29: Exiting...
Zigbee2MQTT:error 2021-03-14 11:43:29: Error: {"frameId":90,"sequence":43} after 10000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:67:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1-dev start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-14T14_43_29_477Z-debug.log
```

**Comment by Koenkk** [comment]
@kirovilya can you help with this?

**Comment by kirovilya** [comment]
@DanielPiccoli can you provide more logs https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

**Comment by DanielPiccoli** [comment]
> @DanielPiccoli can you provide more logs https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

same thing.

[15:31:16] INFO: Zigbee Herdsman debug logging enabled
[15:31:16] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            READ THIS CAREFULLY
Refusing to start because configuration is not valid, found the following errors:
- serial.adapter should be equal to one of the allowed values
If you don't know how to solve this, read https://www.zigbee2mqtt.io/information/configuration.html
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-16T18_31_17_145Z-debug.log

**Comment by DanielPiccoli** [comment]
> @DanielPiccoli can you provide more logs https://www.zigbee2mqtt.io/information/debug.html#zigbee-herdsman-debug-logging

This is the debuggin on EDGE version:

```
2021-03-16T18:36:31.312Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 171 (setValue) received: 36
2021-03-16T18:36:31.313Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 171 (setValue)   parsed: 54
Assertion failed
2021-03-16T18:36:31.315Z zigbee-herdsman:adapter:ezsp:log Set EzspValueId.VALUE_MAXIMUM_INCOMING_TRANSFER_SIZE = 82
2021-03-16T18:36:31.315Z zigbee-herdsman:adapter:ezsp:log ===> Send command setValue: (5,82)
2021-03-16T18:36:31.316Z zigbee-herdsman:adapter:ezsp:log ===> Send data    setValue: (2800ff00ab050052)
2021-03-16T18:36:31.316Z zigbee-herdsman:adapter:ezsp:uart Send DATA frame (0,0,0): 2800ff00ab050052
2021-03-16T18:36:31.317Z zigbee-herdsman:adapter:ezsp:uart waiting (1)
2021-03-16T18:36:31.317Z zigbee-herdsman:adapter:ezsp:uart --> [006a2157548110b20bd72b7e] [0,106,33,87,84,129,16,178,11,215,43,126]
2021-03-16T18:36:31.318Z zigbee-herdsman:adapter:ezsp:uart waiting (1) success
2021-03-16T18:36:31.366Z zigbee-herdsman:adapter:ezsp:uart <-- [016aa1575481238a307e] [1,106,161,87,84,129,35,138,48,126]
2021-03-16T18:36:31.367Z zigbee-herdsman:adapter:ezsp:uart Recv DATA frame (0,1,0): 016aa1575481238a307e
2021-03-16T18:36:31.367Z zigbee-herdsman:adapter:ezsp:uart Send ACK  frame (1)
2021-03-16T18:36:31.368Z zigbee-herdsman:adapter:ezsp:uart --> [8160597e] [129,96,89,126]
2021-03-16T18:36:31.369Z zigbee-herdsman:adapter:ezsp:log <=== Frame: 2880ff00ab36
2021-03-16T18:36:31.369Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 171 (setValue) received: 36
2021-03-16T18:36:31.370Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 171 (setValue)   parsed: 54
Assertion failed
2021-03-16T18:36:31.371Z zigbee-herdsman:adapter:ezsp:log Set EzspValueId.VALUE_END_DEVICE_KEEP_ALIVE_SUPPORT_MODE = 3
2021-03-16T18:36:31.371Z zigbee-herdsman:adapter:ezsp:log ===> Send command setValue: (63,3)
2021-03-16T18:36:31.371Z zigbee-herdsman:adapter:ezsp:log ===> Send data    setValue: (2900ff00ab3f0003)
2021-03-16T18:36:31.372Z zigbee-herdsman:adapter:ezsp:uart Send DATA frame (1,1,0): 2900ff00ab3f0003
2021-03-16T18:36:31.372Z zigbee-herdsman:adapter:ezsp:uart waiting (2)
2021-03-16T18:36:31.373Z zigbee-herdsman:adapter:ezsp:uart --> [7d316b215754812ab25a60957e] [125,49,107,33,87,84,129,42,178,90,96,149,126]
2021-03-16T18:36:31.373Z zigbee-herdsman:adapter:ezsp:uart waiting (2) success
2021-03-16T18:36:31.421Z zigbee-herdsman:adapter:ezsp:uart <-- [126ba15754812230487e] [18,107,161,87,84,129,34,48,72,126]
2021-03-16T18:36:31.421Z zigbee-herdsman:adapter:ezsp:uart Recv DATA frame (1,2,0): 126ba15754812230487e
2021-03-16T18:36:31.421Z zigbee-herdsman:adapter:ezsp:uart Send ACK  frame (2)
2021-03-16T18:36:31.421Z zigbee-herdsman:adapter:ezsp:uart --> [82503a7e] [130,80,58,126]
2021-03-16T18:36:31.422Z zigbee-herdsman:adapter:ezsp:log <=== Frame: 2980ff00ab37
2021-03-16T18:36:31.422Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 171 (setValue) received: 37
2021-03-16T18:36:31.422Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 171 (setValue)   parsed: 55
Assertion failed
2021-03-16T18:36:31.423Z zigbee-herdsman:adapter:ezsp:log ===> Send command setConcentrator: (true,65529,10,90,4,3,0)
2021-03-16T18:36:31.423Z zigbee-herdsman:adapter:ezsp:log ===> Send data    setConcentrator: (2a00ff001001f9ff0a005a00040300)
2021-03-16T18:36:31.423Z zigbee-herdsman:adapter:ezsp:uart Send DATA frame (2,2,0): 2a00ff001001f9ff0a005a00040300
2021-03-16T18:36:31.423Z zigbee-herdsman:adapter:ezsp:uart waiting (3)
2021-03-16T18:36:31.423Z zigbee-herdsman:adapter:ezsp:uart --> [22682157543a144ba69e4a7faa519149c1c37e] [34,104,33,87,84,58,20,75,166,158,74,127,170,81,145,73,193,195,126]
2021-03-16T18:36:31.423Z zigbee-herdsman:adapter:ezsp:uart waiting (3) success
2021-03-16T18:36:31.481Z zigbee-herdsman:adapter:ezsp:uart <-- [2368a157543a159b077e] [35,104,161,87,84,58,21,155,7,126]
2021-03-16T18:36:31.481Z zigbee-herdsman:adapter:ezsp:uart Recv DATA frame (2,3,0): 2368a157543a159b077e
2021-03-16T18:36:31.482Z zigbee-herdsman:adapter:ezsp:uart Send ACK  frame (3)
2021-03-16T18:36:31.482Z zigbee-herdsman:adapter:ezsp:uart --> [83401b7e] [131,64,27,126]
2021-03-16T18:36:31.482Z zigbee-herdsman:adapter:ezsp:log <=== Frame: 2a80ff001000
2021-03-16T18:36:31.482Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 16 (setConcentrator) received: 00
2021-03-16T18:36:31.482Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 16 (setConcentrator)   parsed: 0
2021-03-16T18:36:31.483Z zigbee-herdsman:adapter:ezsp:log Set concentrator type: 0
2021-03-16T18:36:31.483Z zigbee-herdsman:adapter:ezsp:log ===> Send command setSourceRouteDiscoveryMode: (1)
2021-03-16T18:36:31.483Z zigbee-herdsman:adapter:ezsp:log ===> Send data    setSourceRouteDiscoveryMode: (2b00ff005a01)
2021-03-16T18:36:31.483Z zigbee-herdsman:adapter:ezsp:uart Send DATA frame (3,3,0): 2b00ff005a01
2021-03-16T18:36:31.483Z zigbee-herdsman:adapter:ezsp:uart waiting (4)
2021-03-16T18:36:31.483Z zigbee-herdsman:adapter:ezsp:uart --> [33692157547014392a7e] [51,105,33,87,84,112,20,57,42,126]
2021-03-16T18:36:31.483Z zigbee-herdsman:adapter:ezsp:uart waiting (4) success
2021-03-16T18:36:31.533Z zigbee-herdsman:adapter:ezsp:uart <-- [3469a1575470612c8c7e] [52,105,161,87,84,112,97,44,140,126]
2021-03-16T18:36:31.535Z zigbee-herdsman:adapter:ezsp:uart Recv DATA frame (3,4,0): 3469a1575470612c8c7e
2021-03-16T18:36:31.535Z zigbee-herdsman:adapter:ezsp:uart Send ACK  frame (4)
2021-03-16T18:36:31.536Z zigbee-herdsman:adapter:ezsp:uart --> [8430fc7e] [132,48,252,126]
2021-03-16T18:36:31.536Z zigbee-herdsman:adapter:ezsp:log <=== Frame: 2b80ff005a74
2021-03-16T18:36:31.536Z zigbee-herdsman:adapter:ezsp:log <=== Application frame 90 (setSourceRouteDiscoveryMode) received: 74
2021-03-16T18:36:31.539Z zigbee-herdsman:adapter:ezsp:uart Error while parsing to ZpiObject 'RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at boundsError (internal/buffer.js:81:11)
    at Buffer.readUInt32LE (internal/buffer.js:217:5)
    at Buffer.readUIntLE (internal/buffer.js:175:17)
    at Function.deserialize (/app/node_modules/zigbee-herdsman/dist/adapter/ezsp/driver/types/basic.js:19:67)
    at Object.deserialize (/app/node_modules/zigbee-herdsman/dist/adapter/ezsp/driver/types/index.js:119:30)
    at Ezsp.onFrameReceived (/app/node_modules/zigbee-herdsman/dist/adapter/ezsp/driver/ezsp.js:114:28)
    at SerialDriver.emit (events.js:315:20)
    at SerialDriver.handleDATA (/app/node_modules/zigbee-herdsman/dist/adapter/ezsp/driver/uart.js:303:14)
    at SerialDriver.onParsed (/app/node_modules/zigbee-herdsman/dist/adapter/ezsp/driver/uart.js:262:26)
    at Parser.emit (events.js:315:20)'
2021-03-16T18:36:37.190Z zigbee-herdsman:adapter:ezsp:log Time to watchdog ... 0
2021-03-16T18:36:37.191Z zigbee-herdsman:adapter:ezsp:log ===> Send command nop: ()
2021-03-16T18:36:41.487Z zigbee-herdsman:adapter:ezsp:log ===> Send data    nop: (2c00ff0005)
2021-03-16T18:36:41.489Z zigbee-herdsman:adapter:ezsp:uart Send DATA frame (4,4,0): 2c00ff0005
2021-03-16T18:36:41.489Z zigbee-herdsman:adapter:ezsp:uart waiting (5)
2021-03-16T18:36:41.490Z zigbee-herdsman:adapter:ezsp:uart --> [446e2157542f39877e] [68,110,33,87,84,47,57,135,126]
2021-03-16T18:36:41.490Z zigbee-herdsman:adapter:ezsp:uart waiting (5) success
Zigbee2MQTT:error 2021-03-16 15:36:41: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-16 15:36:41: Failed to start zigbee
Zigbee2MQTT:error 2021-03-16 15:36:41: Exiting...
Zigbee2MQTT:error 2021-03-16 15:36:41: Error: {"frameId":90,"sequence":43} after 10000ms
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/dist/utils/waitress.js:67:35)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1-dev start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1-dev start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-16T18_36_41_531Z-debug.log
[15:36:41] INFO: Zigbee Herdsman debug logging enabled
[15:36:41] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1-dev start /app
> node index.js
```

**Comment by kirovilya** [comment]
@DanielPiccoli Thank you. I'll see. Thank you. I'll see

**Comment by kirovilya** [comment]
@DanielPiccoli try the latest version z2m-dev

**Comment by DanielPiccoli** [comment]
> @DanielPiccoli try the latest version z2m-dev

it is working now, but seems like i might have another problem to deal with - my Aqara sensors are not getting picked up - they fail at pairing just like: https://github.com/Koenkk/zigbee2mqtt/issues/5127 

BUT, your fix did the trick and it is launching and apparently communicating.

**Comment by kirovilya** [comment]
@DanielPiccoli It’s strange. Try pairing again. You can also enable debug logs and record the pairing process

**Comment by arripeo** [comment]
I've installed edge version with ezsp WiFi bridge, I don't know if it's linked to the adapter type but on network it's seems not able to recognize router device type. I mean that link between coordinator and router is green and it's only visible with the "isasibling" option enabled. It's small thing but I want to put your attention

**Comment by kirovilya** [comment]
@arripeo try checking on the latest dev-version of z2m

**Comment by arripeo** [comment]
> @arripeo try checking on the latest dev-version of z2m

I Will try but my system is Hassio so only the edge addon is available, I think that I got already the lastest version available. More over I've noticed that the adapter has difficult to send message instead of receive it. I will try to put here some logs

**Comment by ciotlosm** [comment]
Closing this in favor of #144
