### ISSUE TITLE
z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)

### ISSUE THREAD

**Issue by spatipan** [zigbee2mqtt/hassio-zigbee2mqtt#671]
### Description of the issue

I have SMLIGHT CC2652P Zigbee USB Adapter SLZB-02 Zigbee dongle  
connected to intel NUC at dev/ttyUSB0

I tried

```
ls -l /dev/serial/by-id
total 0
lrwxrwxrwx 1 root root 13 Dec 10 15:14 usb-1a86_USB_Serial-if00-port0 -> ../../ttyUSB0
```

```
test -w /dev/ttyUSB0 && echo success || echo failure
success
```

it seems zigbee-herdsman fail to start. I don't have idea how to fix this, please help.

### Z2M configuration
```
data_path: /config/zigbee2mqtt
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: "-d -d"
  log: true
mqtt:
  server: mqtt://localhost:1883
  user: ****
  password: ****
serial:
  port: /dev/ttyUSB0
```

### Addon version

1.42.0-2

### Platform

HA Core: 2024.12.2
HA Supervisor: 2024.11.4
HA OS: 14.0

### Logs of the issue (if applicable)

```
[10:11:06] INFO: Preparing to start...
[10:11:06] INFO: Socat not enabled
[10:11:06] INFO: Starting Zigbee2MQTT...
Starting Zigbee2MQTT without watchdog.
[2024-12-11 10:11:09] info: 	z2m: Logging to console, file (filename: log.log)
[2024-12-11 10:11:09] debug: 	z2m: Loaded state from file /config/zigbee2mqtt/state.json
[2024-12-11 10:11:09] info: 	z2m: Starting Zigbee2MQTT version 1.42.0 (commit #unknown)
[2024-12-11 10:11:09] debug: 	z2m: sd-notify loaded
[2024-12-11 10:11:09] info: 	z2m: Starting zigbee-herdsman (2.1.9)
[2024-12-11 10:11:09] debug: 	z2m: Using zigbee-herdsman with settings: '"{\"network\":{\"panID\":6754,\"extendedPanID\":[221,221,221,221,221,221,221,221],\"channelList\":[25],\"networkKey\":\"HIDDEN\"},\"databasePath\":\"/config/zigbee2mqtt/database.db\",\"databaseBackupPath\":\"/config/zigbee2mqtt/database.db.backup\",\"backupPath\":\"/config/zigbee2mqtt/coordinator_backup.json\",\"serialPort\":{\"path\":\"/dev/ttyUSB0\"},\"adapter\":{\"disableLED\":false}}"'
[2024-12-11 10:11:10] debug: 	zh:controller: Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":"HIDDEN","panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[25]},"serialPort":{"path":"/dev/ttyUSB0"},"adapter":{"disableLED":false},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json"}'
[2024-12-11 10:11:10] info: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/ttyUSB0","baudRate":115200,"rtscts":false,"autoOpen":false}
[2024-12-11 10:11:10] info: 	zh:zstack:znp: Serialport opened
[2024-12-11 10:11:10] debug: 	zh:zstack:znp: --> SREQ: SYS - ping - {"capabilities":1}
[2024-12-11 10:11:10] debug: 	zh:zstack:unpi:writer: --> frame [254,0,33,1,32]
[2024-12-11 10:11:10] info: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-12-11 10:11:10] debug: 	zh:zstack:unpi:writer: --> buffer [239]
[2024-12-11 10:11:11] debug: 	zh:zstack:znp: --> SREQ: SYS - ping - {"capabilities":1}
[2024-12-11 10:11:11] debug: 	zh:zstack:unpi:writer: --> frame [254,0,33,1,32]
[2024-12-11 10:11:12] info: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-12-11 10:11:12] debug: 	zh:zstack:znp: --> SREQ: SYS - ping - {"capabilities":1}
[2024-12-11 10:11:12] debug: 	zh:zstack:unpi:writer: --> frame [254,0,33,1,32]
[2024-12-11 10:11:18] debug: 	zh:zstack:znp: --> SREQ: SYS - ping - {"capabilities":1}
[2024-12-11 10:11:18] debug: 	zh:zstack:unpi:writer: --> frame [254,0,33,1,32]
[2024-12-11 10:11:24] debug: 	zh:zstack:znp: --> SREQ: SYS - ping - {"capabilities":1}
[2024-12-11 10:11:24] debug: 	zh:zstack:unpi:writer: --> frame [254,0,33,1,32]
[2024-12-11 10:11:30] error: 	z2m: Error while starting zigbee-herdsman
[2024-12-11 10:11:30] error: 	z2m: Failed to start zigbee
[2024-12-11 10:11:30] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-12-11 10:11:30] error: 	z2m: Exiting...
[2024-12-11 10:11:30] error: 	z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:113:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)
```

**Comment by Ppatou** [comment]
Hello I got the same problem with the same configuration. 
Can somobody check the code of the last update ?
Many Thanks
Patou

**Comment by RafaelDuncan** [comment]
hello, i had the same problem. 
By hard rebooting (disconnecting power) the raspberry pi4 I got a working add-on again.

I also changed the "serial" field to

port: /dev/ttyUSB0
in the past I had the full reference including the name of the stick, but not anymore.

**Comment by Wolfgang-03** [comment]
Hello, 
I have the same problem, see the log file [zigbee2mqtt_2024-12-17T07-07-00.298Z.log](https://github.com/user-attachments/files/18161828/zigbee2mqtt_2024-12-17T07-07-00.298Z.log) for details. Everything runs normally until 00:37:59, after which no more data is received. At 03:00:06 the following error occurs

```
[2024-12-17 03:00:06] [34mdebug[39m: 	zh:controller:endpoint: Error: ZCL command 0x003c84fffe21fdd6/1 manuSpecificTuya.dataRequest({"seq":1,"dpValues":[{"dp":2,"datatype":4,"data":[1]}]}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (SRSP - AF - dataRequest after 6000ms)
    at Object.start (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:59:23)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:285:45
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at Znp.request (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/znp/znp.ts:278:27)
    at ZStackAdapter.dataRequest (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:1034:24)
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:488:46)
    at /app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:422:31
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:26)
    at ZStackAdapter.sendZclFrameToEndpoint (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:420:33)
    at Request.func (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:299:36)
```

But actually nothing is running from 00:38:00 onwards, the "last seen" device is 'Heizung Schlafzimmer' at 00:37:59.

System: 
Home Assistant Core 2024.11.3 as virtual machine on QNAP-NAS

ttyUSB0
/dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0

**Comment by MoosJ80** [comment]
I have similar issues. These seem to be random. 
My setup was working perfect for a few years.
Any help or ideas are appreciated
----------------------------------------------------------------------------------
Zigbee2MQTT version 			       1.42.0 commit: unknown
Coordinator type 			                zStack3x0
Coordinator revision 			        20210120
zigbee-herdsman-converters version 	20.58.0
zigbee-herdsman version 		        2.1.9
--------------------------------------------------------------------------------- 
Config:

serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
  adapter: zstack
----------------------------------------------------------------------------------

LOG

[10:16:37] INFO: [32mStarting Zigbee2MQTT...[0m
Starting Zigbee2MQTT without watchdog.
[2024-12-21 10:16:47] [32minfo[39m: 	z2m: Logging to console, file (filename: log.log)
[2024-12-21 10:16:47] [34mdebug[39m: 	z2m: Loaded state from file /config/zigbee2mqtt/state.json
[2024-12-21 10:16:47] [32minfo[39m: 	z2m: Starting Zigbee2MQTT version 1.42.0 (commit #unknown)
[2024-12-21 10:16:47] [34mdebug[39m: 	z2m: sd-notify loaded
[2024-12-21 10:16:47] [32minfo[39m: 	z2m: Starting zigbee-herdsman (2.1.9)
[2024-12-21 10:16:47] [34mdebug[39m: 	z2m: Using zigbee-herdsman with settings: '"{\"network\":{\"panID\":6755,\"extendedPanID\":[221,221,221,221,221,221,221,221],\"channelList\":[11],\"networkKey\":\"HIDDEN\"},\"databasePath\":\"/config/zigbee2mqtt/database.db\",\"databaseBackupPath\":\"/config/zigbee2mqtt/database.db.backup\",\"backupPath\":\"/config/zigbee2mqtt/coordinator_backup.json\",\"serialPort\":{\"path\":\"/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0\",\"adapter\":\"zstack\"},\"adapter\":{\"disableLED\":false}}"'
[2024-12-21 10:16:48] [34mdebug[39m: 	zh:controller: Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":"HIDDEN","panID":6755,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0","adapter":"zstack"},"adapter":{"disableLED":false},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json"}'
[2024-12-21 10:16:48] [32minfo[39m: 	zh:zstack:znp: Opening SerialPort with {"path":"/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0","baudRate":115200,"rtscts":false,"autoOpen":false}
[2024-12-21 10:16:48] [32minfo[39m: 	zh:zstack:znp: Serialport opened
[2024-12-21 10:16:48] [34mdebug[39m: 	zh:zstack:znp: --> SREQ: SYS - ping - {"capabilities":1}
[2024-12-21 10:16:48] [34mdebug[39m: 	zh:zstack:unpi:writer: --> frame [254,0,33,1,32]
[2024-12-21 10:16:48] [32minfo[39m: 	zh:zstack:znp: Writing CC2530/CC2531 skip bootloader payload
[2024-12-21 10:16:48] [34mdebug[39m: 	zh:zstack:unpi:writer: --> buffer [239]
[2024-12-21 10:16:49] [34mdebug[39m: 	zh:zstack:znp: --> SREQ: SYS - ping - {"capabilities":1}
[2024-12-21 10:16:49] [34mdebug[39m: 	zh:zstack:unpi:writer: --> frame [254,0,33,1,32]
[2024-12-21 10:16:50] [32minfo[39m: 	zh:zstack:znp: Skip bootloader for CC2652/CC1352
[2024-12-21 10:16:50] [34mdebug[39m: 	zh:zstack:znp: --> SREQ: SYS - ping - {"capabilities":1}
[2024-12-21 10:16:50] [34mdebug[39m: 	zh:zstack:unpi:writer: --> frame [254,0,33,1,32]
[2024-12-21 10:16:56] [34mdebug[39m: 	zh:zstack:znp: --> SREQ: SYS - ping - {"capabilities":1}
[2024-12-21 10:16:56] [34mdebug[39m: 	zh:zstack:unpi:writer: --> frame [254,0,33,1,32]
[2024-12-21 10:17:02] [34mdebug[39m: 	zh:zstack:znp: --> SREQ: SYS - ping - {"capabilities":1}
[2024-12-21 10:17:02] [34mdebug[39m: 	zh:zstack:unpi:writer: --> frame [254,0,33,1,32]
[2024-12-21 10:17:08] [31merror[39m: 	z2m: Error while starting zigbee-herdsman
[2024-12-21 10:17:08] [31merror[39m: 	z2m: Failed to start zigbee
[2024-12-21 10:17:08] [31merror[39m: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-12-21 10:17:08] [31merror[39m: 	z2m: Exiting...
[2024-12-21 10:17:08] [31merror[39m: 	z2m: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:113:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:137:29)
    at Zigbee.start (/app/lib/zigbee.ts:69:27)
    at Controller.start (/app/lib/controller.ts:161:27)
    at start (/app/index.js:154:5)
[10:17:10] INFO: [32mPreparing to start...[0m
[10:17:10] INFO: [32mSocat not enabled[0m
[10:17:10] INFO: [32mStarting Zigbee2MQTT...[0m
Starting Zigbee2MQTT without watchdog.

**Comment by Wolfgang-03** [comment]
I don't know exactly where the problems came from, but I did a few downgrades and since then Zigbee2mqtt has been running stable for me again.

Home Assistant Operating System 13.2 -> Is fine
Home Assistant Core 2024.11.3 -> downgrade to 2024.11.1
Zigbee2MQTT 1.42.0-2 -> downgrade to 1.40.2-1
