### ISSUE TITLE
CC2358 on UART won`t talk to Z2M addon

### ISSUE THREAD

**Issue by Kosygor** [zigbee2mqtt/hassio-zigbee2mqtt#72]
**Description of problem:**
Zigbee-herdsman will not connect to adapter.
I`m not sure that this addon problem but as far as I investigate it it has to be something with socat. 

I`m switching from CC2531 to CC2538 -precisely [this ](https://pl.aliexpress.com/item/4001285481883.html?spm=a2g0s.9042311.0.0.22de5c0fWs8Kda) one.
I have flashed [JETHOME ](https://github.com/jethome-ru/zigbee-firmware/tree/master/ti/coordinator/cc2538_cc2592) fw.
Used esp2866 as serial bridge (tried both ESPeasy and tasmota).

My first concern is that it does not send anything*. So I am assuming that it has to get some request from Z2M - correct me if I am wrong.
\* - except `▒A▒` after pushing reset button with both FTDI/UART and ESP serial connection.
`link=/share/zigbee2mqtt/Z2M ` - it created a file but it was empty.
`link=/tmp/ttyZ2M` - it have not created file.
In both cases socat was not complaining about anything. 

Finally I have also to remove and re-install addon but that did not help.

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.18.1-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.0.111:1883'
  user: mqtt
  password: XXXXXXXX
serial:
  port: /tmp/ttyZ2M
advanced:
  log_level: info
  pan_id: 6755
  channel: 11
  network_key:
X
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: true
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:7777,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: true
zigbee_herdsman_debug: true
```
Below yaml config file I have tried few ports 8485, 7777 and so on - to bo honest I do not understand why You have to put port twice in config 
**Running platform (details from Suypervisor > System)**
```
Core: core-2021.3.4
Supervisor: supervisor-2021.03.6
Operating System: Debian GNU/Linux 10 (buster)
```

**Your logs from Home Assistant Supervisor**
All green. 

**Logs from addon**
```
Socat startup parameters:
Options:     -d -d
Master:      pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
Slave:       tcp-listen:7777,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
[20:59:46] INFO: Starting socat process ...
2021/03/21 20:59:46 socat[294] N PTY is /dev/pts/1
2021/03/21 20:59:46 socat[294] W ioctl(7, IOCTL_VM_SOCKETS_GET_LOCAL_CID, ...): Not a tty
2021/03/21 20:59:46 socat[294] N listening on AF=2 0.0.0.0:7777
> zigbee2mqtt@1.18.1 start /app
> node index.js
Zigbee2MQTT:info  2021-03-21 20:59:49: Logging to console and directory: '/share/zigbee2mqtt/log/2021-03-21.20-59-48' filename: log.txt
Zigbee2MQTT:info  2021-03-21 20:59:49: Starting Zigbee2MQTT version 1.18.1 (commit #1.18.1)
Zigbee2MQTT:info  2021-03-21 20:59:49: Starting zigbee-herdsman (0.13.71)
2021-03-21T19:59:49.799Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2021-03-21T19:59:49.801Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6755,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/tmp/ttyZ2M"},"databasePath":"/share/zigbee2mqtt/database.db","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","backupPath":"/share/zigbee2mqtt/coordinator_backup.json","adapter":{"concurrent":null,"delay":null}}'
2021-03-21T19:59:49.807Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /tmp/ttyZ2M and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2021-03-21T19:59:49.814Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
2021-03-21T19:59:50.275Z zigbee-herdsman:adapter:zStack:znp:log Writing skip bootloader payload
2021-03-21T19:59:50.276Z zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]
2021-03-21T19:59:51.281Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-03-21T19:59:51.283Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2021-03-21T19:59:57.291Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-03-21T19:59:57.292Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2021-03-21T20:00:03.297Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-03-21T20:00:03.297Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
Zigbee2MQTT:error 2021-03-21 21:00:09: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-21 21:00:09: Failed to start zigbee
Zigbee2MQTT:error 2021-03-21 21:00:09: Exiting...
Zigbee2MQTT:error 2021-03-21 21:00:09: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-21T20_00_09_350Z-debug.log
[21:00:09] INFO: Zigbee Herdsman debug logging enabled
[21:00:09] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
```

**Comment by Kosygor** [comment]
I have 
- tried switching to wall ac adapter. 
- getting sure that user [has write access](https://www.zigbee2mqtt.io/information/FAQ.html#verify-that-the-user-you-run-zigbee2mqtt-as-has-write-access-to-the-port) to `/usr/share/hassio/homeassistant/tmp/ttyZ2M`.
No improvement. 
I am assuming:
`2021/03/22 16:49:55 socat[295] N listening on AF=2 0.0.0.0:7777`
that by this it means that it is listening to whole port and it does not matter from witch IP.

**Comment by Kosygor** [comment]
Hmmm loooks like i do not understand how 
```
serial:
  port: 
```
and `link=` sections work.

I configured addon with `port: /usr/share/hassio/share/zigbee2mqtt/ttyZ2` and socat diabled.
and launched socat manually in debian terminal:
`sudo socat -d -d pty,raw,echo=0,link=/usr/share/hassio/share/zigbee2mqtt/ttyZ2M tcp-connect:192.168.0.126:7777`
and it just worked like a charm.
I just do not get what I am doing wrong when configuring addon.

**Comment by Kosygor** [comment]
After configuring Z2m Addon to 
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.0.111:1883'
  user: mqtt
  password: X
serial:
  port: /tmp/ttyZ2M
advanced:
  log_level: info
  pan_id: 6756
  channel: 11
  network_key:
X
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: true
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:7777,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: true
zigbee_herdsman_debug: true
```
I got sure that user that I`am running have acces to that directory according to: [Verify that the user you run Zigbee2MQTT as has write access to the ](porthttps://www.zigbee2mqtt.io/information/FAQ.html#verify-that-the-user-you-run-zigbee2mqtt-as-has-write-access-to-the-port).
I also have ensured that pan_id has naver used before value. 

```
[16:51:16] INFO: Zigbee Herdsman debug logging enabled
[16:51:16] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
Zigbee2MQTT:info  2021-03-23 16:51:19: Logging to console and directory: '/share/zigbee2mqtt/log/2021-03-23.16-51-18' filename: log.txt
Zigbee2MQTT:info  2021-03-23 16:51:19: Starting Zigbee2MQTT version 1.18.1 (commit #1.18.1)
Zigbee2MQTT:info  2021-03-23 16:51:19: Starting zigbee-herdsman (0.13.71)
2021-03-23T15:51:19.728Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2021-03-23T15:51:19.731Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6756,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/tmp/ttyZ2M"},"databasePath":"/share/zigbee2mqtt/database.db","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","backupPath":"/share/zigbee2mqtt/coordinator_backup.json","adapter":{"concurrent":null,"delay":null}}'
2021-03-23T15:51:19.737Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /tmp/ttyZ2M and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2021-03-23T15:51:19.744Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
2021-03-23T15:51:20.206Z zigbee-herdsman:adapter:zStack:znp:log Writing skip bootloader payload
2021-03-23T15:51:20.207Z zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]
2021-03-23T15:51:21.213Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-03-23T15:51:21.217Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2021-03-23T15:51:27.226Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-03-23T15:51:27.227Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2021-03-23T15:51:33.234Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-03-23T15:51:33.235Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
Zigbee2MQTT:error 2021-03-23 16:51:39: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-03-23 16:51:39: Failed to start zigbee
Zigbee2MQTT:error 2021-03-23 16:51:39: Exiting...
Zigbee2MQTT:error 2021-03-23 16:51:39: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:94:31)
    at Generator.throw (<anonymous>)
    at rejected (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/zStackAdapter.js:25:65)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-03-23T15_51_39_290Z-debug.log
```

**Comment by Kosygor** [comment]
Ain`t no pro so this took me while but it seems default configurations is not proper:

```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://192.168.0.111:1883'
  user: mqtt
  password: X
serial:
  port: /tmp/ttyZ2M
(...)
socat:
  enabled: true
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: >-
    tcp-connect:192.168.0.126:7777,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: true
zigbee_herdsman_debug: true
```
In another way 
`tcp-listen:PORT`
in this case should be
`tcp-connect:IP:PORT`
