### ISSUE TITLE
502: Bad Gateway

### ISSUE THREAD

**Issue by OBubnik** [zigbee2mqtt/hassio-zigbee2mqtt#81]
If I try OPEN WEB UI for this Add-on it ends with error "_502: Bad Gateway_"

The same result is from a sidebar
When I call UI directly from my browser by "_http://homeassistant:8485_" it works

```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://homeassistant'
  user: *MySerwer*
  password: '*MyPassword*'
serial:
  port: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
advanced:
  baudrate: 115200
  rtscts: false
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8485
experimental:
  transmit_power: 20
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
```
It's on RPi 4B:
```
Version	core-2021.3.4
Installation Type	Home Assistant OS
Development	false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.4.83-v8
CPU Architecture | aarch64
```

Log from Add-on looks fine:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[21:11:14] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[21:11:15] INFO: MQTT available, fetching server detail ...
[21:11:15] INFO: Previous config file found, checking backup
[21:11:15] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[21:11:15] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:11:17] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
```

**Comment by larray** [comment]
Confirmation of the same issue.  I cannot get to the interface from the Home Assistant interface (from Addon WebUI link or the Sidebar link) nor can I get to it via "http://homeassistant:8485".  I'm assuming @OBubnik was successful because they changed frontend: port: to 8485 and socat is not enabled?  (I couldn't replicate).

Config:
`data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if01-port0
  adapter: ezsp
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false
zigbee_herdsman_debug: true
`

**Comment by IoTNotes** [comment]
Chek out also the Supervisor register log (Supervisor->System) if you have any ERROR related to supervisor.api.ingress or any WARNING related to "unknown option" in Zigbee2Mqtt.
I had the same problem and from supervisor log I've discovered that:
1) I had some unknown options in my zigbee2mqtt config file
2) The supervisor.api.ingress tried to connect to the port 8099 while in my config was 8066. I changed the port to 8099 in my config too and all started to work

Hope this can help you.
Have a nice day.

**Comment by larray** [comment]
Thanks @IoTNotes  - 

I've cleaned up most of the errors - had to reload the add-on a few days ago.  The only related error I get now (that I can see - there may be other things in other logs) is:

```
21-04-14 12:16:06 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.6:8099 ssl:default [Connect call failed ('172.30.33.6', 8099)]
```

But if you look at my config above - I have:
frontend:
  port: 8099

I don't have public SSL certs set up - all internal right now and the Let's Encrypt portion is potentially "challenging" without a rip and replace of DNS or some hefty port forwarding voodoo.. its later down the list, but the error looks to be more of a failure to connect, not a SSL cert error. 

I've tried to change the port in the add-on configuration but it doesn't look like that alters the docker config, attempts to access the web still show in the log as going to port 8099. 

At this point I am under the assumption that it is either:
-  There is some internal (private portainer/docker) network snafu inside Home Assistant that is blocking access to port 8099 (I was able to get to the shell and ping 172.30.33.6 but didn't have an effective way I knew to interrogate 172.30.33.6:8099 for data/services.
- That the adapter / zigbee-herdsman is not fully initialized - but I don't know from looking at its log how to assess "started":
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[08:04:34] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[08:04:34] INFO: MQTT available, fetching server detail ...
[08:04:34] INFO: MQTT server settings not configured, trying to auto-discovering ...
[08:04:34] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[08:04:34] INFO: MQTT credentials not configured, trying to auto-discovering ...
[08:04:35] INFO: Configuring'addons' mqtt user
[08:04:35] INFO: Previous config file found, checking backup
[08:04:35] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[08:04:35] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[08:04:35] INFO: Zigbee Herdsman debug logging enabled
[08:04:35] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.2 start /app
> node index.js
Zigbee2MQTT:debug 2021-04-14 08:04:37: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2021-04-14 08:04:37: Logging to console and directory: '/config/zigbee2mqtt/log/2021-04-14.08-04-37' filename: log.txt
Zigbee2MQTT:debug 2021-04-14 08:04:37: Removing old log directory '/config/zigbee2mqtt/log/2021-04-12.14-35-06'
Zigbee2MQTT:info  2021-04-14 08:04:38: Starting Zigbee2MQTT version 1.18.2 (commit #1.18.2)
Zigbee2MQTT:info  2021-04-14 08:04:38: Starting zigbee-herdsman (0.13.88)
Zigbee2MQTT:debug 2021-04-14 08:04:38: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if01-port0"}}'
2021-04-14T12:04:38.285Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if01-port0","adapter":"ezsp"},"databasePath":"/config/zigbee2mqtt/database.db","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","backupPath":"/config/zigbee2mqtt/coordinator_backup.json","adapter":{"concurrent":null,"delay":null}}'
2021-04-14T12:04:38.288Z zigbee-herdsman:adapter:ezsp:uart Opening SerialPort with /dev/serial/by-id/usb-Silicon_Labs_HubZ_Smart_Home_Controller_81300027-if01-port0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2021-04-14T12:04:38.305Z zigbee-herdsman:adapter:ezsp:uart Serialport opened
2021-04-14T12:04:38.305Z zigbee-herdsman:adapter:ezsp:uart uart reseting
2021-04-14T12:04:38.306Z zigbee-herdsman:adapter:ezsp:uart Write reset
2021-04-14T12:04:38.307Z zigbee-herdsman:adapter:ezsp:uart --> [1ac038bc7e] [26,192,56,188,126]
Zigbee2MQTT:debug 2021-04-14 08:09:38: Saving state to file /config/zigbee2mqtt/state.json
```

**Comment by IoTNotes** [comment]
@larray ,
what I can say is that I had, in [supervisor.api.ingress] error log, "ssl:default" too. When I changed the port it has been enough. 
So, I suppose SSL is not related to your issue.

**Comment by larray** [comment]
Thanks.  I was concerned that possibly with the flashing I did for the zigbee adapter to get on the right coordinator level that I might have mucked the adapter.  I pulled zigbee2mqtt out and re-installed Zigbee Home Automation and all the devices came back in from the original implementation - so the hardware is functional at least.  Now it is just a matter of trying to get the interface to come up with zigbee2mqtt.

**Comment by larray** [comment]
**FOR THOSE THAT FOLLOW:**
Nortek HUSBZB-1 using ```ncp-uart-sw-6.7.8.ebl``` firmware the magic command in the configuration file is:
```
advanced:
  baudrate: 57600
```

The ```502 BAD GATEWAY``` is gone and the logs are full of 2 way communications and the web interface is up.

**Comment by ciotlosm** [comment]
The side bar only works with default port 8099 as that does some ingress magic to allow the add-on to proxy into the default UI using that port (regardless of SSL). 

The error "Ingress error: Cannot connect to host" just means that the container UI didn't start so your port is not yet opened. 

It really depends on the stick, sometimes you need to specify the type of adapter if you have deconz or some others. This should be in the documentation. 

Let me know if I can close this considering the original issue from @OBubnik

**Comment by Sebaht** [comment]
I have the same problem and i haven't solved it yet. What should i do?

this is my add-on log:

```
[19:44:15] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
Zigbee2MQTT:error 2021-08-19 19:44:19: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-08-19 19:44:19: Failed to start zigbee
Zigbee2MQTT:error 2021-08-19 19:44:19: Exiting...
Zigbee2MQTT:error 2021-08-19 19:44:19: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-19T22_44_19_859Z-debug.log
[19:44:20] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
Zigbee2MQTT:error 2021-08-19 19:44:24: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-08-19 19:44:24: Failed to start zigbee
Zigbee2MQTT:error 2021-08-19 19:44:24: Exiting...
Zigbee2MQTT:error 2021-08-19 19:44:24: Error: Error while opening serialport 'Error: Error: No such file or directory, cannot open /dev/ttyACM0'
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:136:32)
    at Generator.next (<anonymous>)
    at /app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:23:12)
    at SerialPort.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:134:49)
    at SerialPort._error (/app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:198:14)
    at /app/node_modules/zigbee-herdsman/node_modules/@serialport/stream/lib/index.js:242:12
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-08-19T22_44_24_692Z-debug.log
```

and my system log is:

`21-08-19 19:42:51 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.1:8099 ssl:default [Connect call failed ('172.30.33.1', 8099)]`


any help would be great(i'm really new in this)

sorry for my bad english

**Comment by ciotlosm** [comment]
@Sebaht your error is related to " Error: Error while opening serialport" which means your serial config in your z2m configuration is not the right one.

**Comment by Sebaht** [comment]
> @Sebaht your error is related to " Error: Error while opening serialport" which means your serial config in your z2m configuration is not the right one.
> 
> This:
> 
> ```
> /dev/ttyACM0
> ```
> 
> is not available on your setup and you must find the right one.

how do i find the rigth one?

**Comment by ciotlosm** [comment]
1. Go to: Supervisor > System > Host > ⋮ > Hardware
2. Search for "serial"

Should have something like: `/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0`

**Comment by kuduacz** [comment]
same problem here. how can i solve it?
zigbee2mqtt config:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: tcp://192.168.5.122:8888
  adapter: ezsp
advanced:
  log_level: debug
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
availability: false
socat:
  enabled: false
  master: pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777
  slave: tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5
  options: '-d -d'
  log: false
```

zigbee2mqtt log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[07:08:02] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[07:08:03] INFO: MQTT available, fetching server detail ...
[07:08:03] INFO: MQTT server settings not configured, trying to auto-discovering ...
[07:08:03] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[07:08:04] INFO: MQTT credentials not configured, trying to auto-discovering ...
[07:08:04] INFO: Configuring'addons' mqtt user
[07:08:04] INFO: Previous config file found, checking backup
[07:08:04] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[07:08:04] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[07:08:05] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.0-dev start
> node index.js
Zigbee2MQTT:debug 2021-11-29 07:08:12: Loaded state from file /config/zigbee2mqtt/state.json
Zigbee2MQTT:info  2021-11-29 07:08:12: Logging to console and directory: '/config/zigbee2mqtt/log/2021-11-29.07-08-09' filename: log.txt
Zigbee2MQTT:debug 2021-11-29 07:08:13: Removing old log directory '/config/zigbee2mqtt/log/2021-11-29.05-43-50'
Zigbee2MQTT:info  2021-11-29 07:08:13: Starting Zigbee2MQTT version 1.22.0-dev (commit #82f5ddb)
Zigbee2MQTT:info  2021-11-29 07:08:13: Starting zigbee-herdsman (0.13.174)
Zigbee2MQTT:debug 2021-11-29 07:08:13: Using zigbee-herdsman with settings: '{"adapter":{"concurrent":null,"delay":null,"disableLED":false},"backupPath":"/config/zigbee2mqtt/coordinator_backup.json","databaseBackupPath":"/config/zigbee2mqtt/database.db.backup","databasePath":"/config/zigbee2mqtt/database.db","network":{"channelList":[11],"extendedPanID":[221,221,221,221,221,221,221,221],"networkKey":"HIDDEN","panID":6754},"serialPort":{"adapter":"ezsp","path":"tcp://192.168.5.122:8888"}}'
```

and supervisor log:
```
21-11-29 07:57:11 ERROR (MainThread) [supervisor.api.ingress] Ingress error: Cannot connect to host 172.30.33.3:8099 ssl:default [Connect call failed ('172.30.33.3', 8099)]
```

All on rpi4b mosquitto broker and zigbee2mqtt as supervisor addons.
I using adguard home and remote ui (nabu casa)
