### ISSUE TITLE
[HA] Zigbee2Mqtt : Error starting after update HA (system and core) and reboot

### ISSUE THREAD

**Issue by PaulSka** [zigbee2mqtt/hassio-zigbee2mqtt#85]
**Description of problem:**

After update HA Sytem and Core, Zigbee2MQTT plugin doesn't start and crash. Everything works before.
I try to change USB port (on RPI, with or without USB extension), same error.
I use Slaesh's CC2652RB stick

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
Zigbee2MQTT plugin version : 1.18.1-1
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /share/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://core-mosquitto'
  user: xxx
  password: xxxx
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CC_49_14-if00-port0
advanced:
  log_level: info
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/dev/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  restartdelay: 1
  initialdelay: 1
  options: '-d -d'
  log: false
zigbee_herdsman_debug: true
```

**Running platform (details from Suypervisor > System)**
```
// Example
HA Core version : core-2021.4.2
HA Supervisor version : supervisor-2021.03.9
HA OS version : Home Assistant OS 5.13
```

**Your logs from Home Assistant Supervisor**
```
[10:24:19] INFO: Zigbee Herdsman debug logging enabled
[10:24:19] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.1 start /app
> node index.js
Zigbee2MQTT:info  2021-04-10 10:24:23: Logging to console and directory: '/share/zigbee2mqtt/log/2021-04-10.10-24-22' filename: log.txt
Zigbee2MQTT:info  2021-04-10 10:24:23: Starting Zigbee2MQTT version 1.18.1 (commit #1.18.1)
Zigbee2MQTT:info  2021-04-10 10:24:23: Starting zigbee-herdsman (0.13.71)
2021-04-10T08:24:23.709Z zigbee-herdsman:adapter Failed to validate path: 'Error: spawn udevadm ENOENT'
2021-04-10T08:24:23.715Z zigbee-herdsman:controller:log Starting with options '{"network":{"networkKeyDistribute":false,"networkKey":[1,3,5,7,9,11,13,15,0,2,4,6,8,10,12,13],"panID":6754,"extendedPanID":[221,221,221,221,221,221,221,221],"channelList":[11]},"serialPort":{"path":"/dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CC_49_14-if00-port0"},"databasePath":"/share/zigbee2mqtt/database.db","databaseBackupPath":"/share/zigbee2mqtt/database.db.backup","backupPath":"/share/zigbee2mqtt/coordinator_backup.json","adapter":{"concurrent":null,"delay":null}}'
2021-04-10T08:24:23.721Z zigbee-herdsman:adapter:zStack:znp:log Opening SerialPort with /dev/serial/by-id/usb-Silicon_Labs_slae.sh_cc2652rb_stick_-_slaesh_s_iot_stuff_00_12_4B_00_21_CC_49_14-if00-port0 and {"baudRate":115200,"rtscts":false,"autoOpen":false}
2021-04-10T08:24:23.742Z zigbee-herdsman:adapter:zStack:znp:log Serialport opened
2021-04-10T08:24:23.757Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [0]
2021-04-10T08:24:23.759Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [0]
2021-04-10T08:24:24.068Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [0]
2021-04-10T08:24:24.069Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [0,0]
2021-04-10T08:24:24.210Z zigbee-herdsman:adapter:zStack:znp:log Writing skip bootloader payload
2021-04-10T08:24:24.212Z zigbee-herdsman:adapter:zStack:unpi:writer --> buffer [239]
2021-04-10T08:24:25.125Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,6,65,128,0,2,1,2,7,1,192]
2021-04-10T08:24:25.126Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [0,0,254,6,65,128,0,2,1,2,7,1,192]
2021-04-10T08:24:25.128Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 6 - 2 - 1 - 128 - [0,2,1,2,7,1] - 192
2021-04-10T08:24:25.134Z zigbee-herdsman:adapter:zStack:znp:AREQ <-- SYS - resetInd - {"reason":0,"transportrev":2,"productid":1,"majorrel":2,"minorrel":7,"hwrev":1}
2021-04-10T08:24:25.136Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-04-10T08:24:25.220Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - ping - {"capabilities":1}
2021-04-10T08:24:25.225Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,1,32]
2021-04-10T08:24:25.230Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,1,89,6,61]
2021-04-10T08:24:25.231Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,1,89,6,61]
2021-04-10T08:24:25.231Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 1 - [89,6] - 61
2021-04-10T08:24:25.232Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - ping - {"capabilities":1625}
2021-04-10T08:24:25.233Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-04-10T08:24:25.234Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - version - {}
2021-04-10T08:24:25.235Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,0,33,2,35]
2021-04-10T08:24:25.239Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,10,97,2,2,1,2,7,1,66,62,52,1,0,39]
2021-04-10T08:24:25.239Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,10,97,2,2,1,2,7,1,66,62,52,1,0,39]
2021-04-10T08:24:25.240Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 10 - 3 - 1 - 2 - [2,1,2,7,1,66,62,52,1,0] - 39
2021-04-10T08:24:25.241Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - version - {"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20201026}
2021-04-10T08:24:25.241Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-04-10T08:24:25.242Z zigbee-herdsman:adapter:zStack:adapter Adapter concurrent: 16
2021-04-10T08:24:25.242Z zigbee-herdsman:adapter:zStack:adapter Detected znp version 'zStack3x0' ({"transportrev":2,"product":1,"majorrel":2,"minorrel":7,"maintrel":1,"revision":20201026})
2021-04-10T08:24:25.245Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":96,"offset":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2021-04-10T08:24:25.247Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,96,0,0,74]
2021-04-10T08:24:25.252Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,85,62]
2021-04-10T08:24:25.252Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,85,62]
2021-04-10T08:24:25.252Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,85] - 62
2021-04-10T08:24:25.253Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2021-04-10T08:24:25.254Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-04-10T08:24:25.255Z zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid
2021-04-10T08:24:25.257Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":96,"offset":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2021-04-10T08:24:25.258Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,96,0,0,74]
2021-04-10T08:24:25.262Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,3,97,8,0,1,85,62]
2021-04-10T08:24:25.262Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,3,97,8,0,1,85,62]
2021-04-10T08:24:25.263Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 3 - 3 - 1 - 8 - [0,1,85] - 62
2021-04-10T08:24:25.263Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":0,"len":1,"value":{"type":"Buffer","data":[85]}}
2021-04-10T08:24:25.263Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
2021-04-10T08:24:25.264Z zigbee-herdsman:adapter:zStack:startZnp Item 'hasConfigured' is valid
2021-04-10T08:24:25.265Z zigbee-herdsman:adapter:zStack:znp:SREQ --> SYS - osalNvRead - {"id":132,"len":4,"offset":0,"value":{"type":"Buffer","data":[0,8,0,0]}}
2021-04-10T08:24:25.266Z zigbee-herdsman:adapter:zStack:unpi:writer --> frame [254,3,33,8,132,0,0,174]
2021-04-10T08:24:25.272Z zigbee-herdsman:adapter:zStack:unpi:parser <-- [254,2,97,8,2,0,105]
2021-04-10T08:24:25.272Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext [254,2,97,8,2,0,105]
2021-04-10T08:24:25.272Z zigbee-herdsman:adapter:zStack:unpi:parser --> parsed 2 - 3 - 1 - 8 - [2,0] - 105
2021-04-10T08:24:25.273Z zigbee-herdsman:adapter:zStack:znp:SRSP <-- SYS - osalNvRead - {"status":2,"len":0,"value":{"type":"Buffer","data":[]}}
2021-04-10T08:24:25.273Z zigbee-herdsman:adapter:zStack:unpi:parser --- parseNext []
Zigbee2MQTT:error 2021-04-10 10:24:25: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-04-10 10:24:25: Failed to start zigbee
Zigbee2MQTT:error 2021-04-10 10:24:25: Exiting...
Zigbee2MQTT:error 2021-04-10 10:24:25: Error: SREQ '--> SYS - osalNvRead - {"id":132,"len":4,"offset":0,"value":{"type":"Buffer","data":[0,8,0,0]}}' failed with status '(0x02: INVALID_PARAM)' (expected '(0x00: SUCCESS)')
    at Znp.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:291:27)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/znp/znp.js:24:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.18.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.18.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-04-10T08_24_25_348Z-debug.log
```

**Comment by PaulSka** [comment]
I update to lastest version of this plugin (with the correct github) and same error

**Comment by PaulSka** [comment]
Update :
I test the Python script from author of this stick (https://slae.sh/projects/cc2652) : https://github.com/slaesh/cc2652-stick/tree/master/coordinator-test

No error

```
PS C:\Users\XXXX> $comports = Get-WMIObject Win32_SerialPort; $comports | Get-PnpDeviceProperty -InstanceId {$_.pnpdeviceid} -Keyname DEVPKEY_Device_BusReportedDeviceDesc | ForEach-Object { foreach($comport in $comports) { if ($comport.pnpdeviceid -eq $_.instanceid) { new-object psobject -property  @{COMPORT = $comport.deviceid; 'Device-Name' = $_.data} } } }

COMPORT Device-Name
------- -----------
COM1
COM3    slae.sh cc2652rb stick - slaesh's iot stuff
```

```
(env) C:\Users\XXX\>python test.py -p COM3
Opening port COM3, baud 115200

--> Bootloader is working!
--> ZigBee coordinator is working!
`---> transportrev 2, product 1, majorrel 2, minorrel 7, maintrel 1, revision: 20201026

Check done!
```

**Comment by Tamsy** [comment]
Upgrade to Zigbee2MQTT plugin version : 1.18.2-1

Change:

```
<snip>
frontend:
  port: 8099
experimental:
  new_api: true
socat:
  enabled: false
<snip>
```

to:

```
<snip>
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
<snip>

```
(Basically just remove the line "new_api: true")

**Comment by ciotlosm** [comment]
Is this valid anymore? Normally such bugs should be reported to https://github.com/Koenkk/zigbee2mqtt/issues
