### ISSUE TITLE
Issue at start: cannot read property stack

### ISSUE THREAD

**Issue by cacordina** [zigbee2mqtt/hassio-zigbee2mqtt#93]
**Description of problem:**
Hi, 
I try to install the plugin with a conbee II key but I got some errors in logs

**Zigbee2mqtt add-on version (if edge, please report commit hash):**
```
1.18.2-1 
```

**Your entire configuration from the frontend (with sensitive fields redacted)**:
```
data_path: /config/zigbee2mqtt
external_converters: []
devices: devices.yaml
groups: groups.yaml
homeassistant: true
permit_join: false
mqtt:
  base_topic: zigbee2mqtt
serial:
  port: /dev/ttyACM1
  adapter: deconz
advanced:
  log_level: warn
  pan_id: 6754
  channel: 11
  network_key:
    - 1
    - 3
    - 5
    - 7
    - 9
    - 11
    - 13
    - 15
    - 0
    - 2
    - 4
    - 6
    - 8
    - 10
    - 12
    - 13
  availability_blocklist: []
  availability_passlist: []
device_options: {}
blocklist: []
passlist: []
queue: {}
frontend:
  port: 8099
experimental: {}
socat:
  enabled: false
  master: 'pty,raw,echo=0,link=/tmp/ttyZ2M,mode=777'
  slave: 'tcp-listen:8485,keepalive,nodelay,reuseaddr,keepidle=1,keepintvl=1,keepcnt=5'
  options: '-d -d'
  log: false

```

**Running platform (details from Suypervisor > System)**
```

Version | core-2021.4.5
-- | --
Type d'installation | Home Assistant Supervised


```

**Your logs from Home Assistant Supervisor**
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[18:35:13] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[18:35:14] INFO: MQTT available, fetching server detail ...
[18:35:14] INFO: MQTT server settings not configured, trying to auto-discovering ...
[18:35:15] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[18:35:15] INFO: MQTT credentials not configured, trying to auto-discovering ...
[18:35:15] INFO: Configuring'addons' mqtt user
[18:35:15] INFO: Previous config file found, checking backup
[18:35:15] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[18:35:15] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[18:35:16] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.18.2 start /app
> node index.js
CREATED DECONZ ADAPTER
Zigbee2MQTT:error 2021-04-17 18:35:33: Failed to start zigbee
Zigbee2MQTT:error 2021-04-17 18:35:33: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-04-17 18:35:33: Exiting...
(node:365) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stack' of undefined
    at Controller.start (/app/lib/controller.js:114:32)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at listOnTimeout (internal/timers.js:523:9)
    at processTimers (internal/timers.js:497:7)
    at async start (/app/index.js:43:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:365) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:365) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by cacordina** [comment]
After upgrade on the last version, it works
